// AI-generated START - 模版选择页面 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_template%20_selection/providers/template_selection_provider.dart';
import 'package:omi/pages/mp_template%20_selection/widgets/ai_summary_template_header_card.dart';
import 'package:omi/pages/mp_template%20_selection/widgets/custom_template_card.dart';
import 'package:omi/pages/mp_template%20_selection/widgets/template_card.dart';
import 'package:omi/pages/mp_template%20_selection/widgets/template_category_tabs_card.dart';
import 'package:provider/provider.dart';

/// 模版选择页面
/// 显示AI总结模版列表，支持选择和预览
class TemplateSelectionPage extends StatefulWidget {
  // AI-generated START - 构造函数
  const TemplateSelectionPage({
    super.key,
    this.title = '模版选择',
  });
  // AI-generated END - 构造函数

  /// 页面标题
  final String title;

  // AI-generated START - 创建状态
  @override
  State<TemplateSelectionPage> createState() => _TemplateSelectionPageState();
  // AI-generated END - 创建状态
}

class _TemplateSelectionPageState extends State<TemplateSelectionPage> {
  // AI-generated START - 当前选中的分类索引
  int _selectedCategoryIndex = 0;
  // AI-generated END - 当前选中的分类索引

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: [
          IconButton(
            icon: const Icon(Icons.search),
            onPressed: () {
              debugPrint('搜索模版');
              // TODO: 实现搜索功能
            },
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // 标题和描述
                  const AISummaryTemplateHeaderCard(),
                  const SizedBox(height: 8.0),
                  // 分类标签栏
                  _buildCategoryTabs(),
                  const SizedBox(height: 8.0),
                  // 模版列表
                  _buildTemplateList(context),
                  const SizedBox(height: 8.0),
                  // 自定义模版卡片
                  const CustomTemplateCard(
                    onCreateTap: null, // TODO: 实现创建自定义模版逻辑
                  ),
                  const SizedBox(height: 16.0),
                ],
              ),
            ),
          ),
          // 底部应用按钮
          _buildApplyButton(context),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建分类标签栏
  Widget _buildCategoryTabs() {
    return TemplateCategoryTabsCard(
      categories: const [
        TemplateCategoryTab(
          label: '全部',
          icon: Icons.apps,
        ),
        TemplateCategoryTab(
          label: '会议',
          icon: Icons.people_outline,
        ),
        TemplateCategoryTab(
          label: '工作',
          icon: Icons.work_outline,
        ),
        TemplateCategoryTab(
          label: '学习',
          icon: Icons.menu_book_outlined,
        ),
      ],
      selectedIndex: _selectedCategoryIndex,
      onCategoryChanged: (index) {
        setState(() {
          _selectedCategoryIndex = index;
        });
        // TODO: 根据分类筛选模版
      },
    );
  }
  // AI-generated END - 构建分类标签栏

  // AI-generated START - 构建模版列表
  Widget _buildTemplateList(BuildContext context) {
    // 使用 Provider 获取模版列表
    return Consumer<TemplateSelectionProvider>(
      builder: (context, provider, child) {
        final templates = provider.templates;

        if (templates.isEmpty) {
          return const SizedBox.shrink();
        }

        // 显示所有模版卡片，并绑定正确的选择回调
        return Column(
          children: templates.asMap().entries.map((entry) {
            final index = entry.key;
            final template = entry.value;
            return TemplateCard(
              title: template.title,
              description: template.description,
              icon: template.icon,
              iconColor: template.iconColor,
              isSelected: template.isSelected,
              isHot: template.isHot,
              features: template.features,
              onPreview: template.onPreview,
              onSelect: () {
                provider.selectTemplate(index);
              },
            );
          }).toList(),
        );
      },
    );
  }
  // AI-generated END - 构建模版列表

  // AI-generated START - 构建应用按钮
  Widget _buildApplyButton(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.1),
            spreadRadius: 1,
            blurRadius: 4,
            offset: const Offset(0, -2),
          ),
        ],
      ),
      child: SizedBox(
        width: double.infinity,
        child: Consumer<TemplateSelectionProvider>(
          builder: (context, provider, child) {
            final hasSelection = provider.selectedIndex != null;
            return ElevatedButton(
              onPressed: hasSelection
                  ? () {
                      debugPrint('应用选中模版: ${provider.selectedTemplate?.title}');
                      // TODO: 实现应用模版逻辑
                    }
                  : null,
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 16.0),
                backgroundColor: const Color(0xFF2196F3), // 蓝色
                disabledBackgroundColor: Colors.grey[300],
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8.0),
                ),
              ),
              child: const Text(
                '应用选中模版',
                style: TextStyle(
                  fontSize: 16.0,
                  fontWeight: FontWeight.w500,
                  color: Colors.white,
                ),
              ),
            );
          },
        ),
      ),
    );
  }
  // AI-generated END - 构建应用按钮
}
// AI-generated END - template_selection_page.dart
