// AI-generated START - 模板详情页 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/backend/schema/mp/mp_data_model.dart';
import 'package:omi/pages/mp_custom_utils/mp_toast_utils.dart';
import 'package:omi/pages/mp_newsetting/home/widgets/mp_common_app_bar.dart';
import 'package:omi/pages/mp_template%20_selection/providers/template_detail_provider.dart';
import 'package:provider/provider.dart';

/// 模板详情页
/// 显示和编辑模板的详细信息
class MPTemplateDetailPage extends StatefulWidget {
  // AI-generated START - 构造函数
  const MPTemplateDetailPage({
    super.key,
    this.templateId,
    this.template,
    this.isMyTemplate = false,
  });
  // AI-generated END - 构造函数

  /// 模板ID
  final String? templateId;

  /// 模板数据（可选，如果提供则直接使用，否则从API加载）
  final MPTemplateStruct? template;

  /// 是否为自己的模板，默认为 false
  final bool isMyTemplate;

  @override
  State<MPTemplateDetailPage> createState() => _MPTemplateDetailPageState();
}

class _MPTemplateDetailPageState extends State<MPTemplateDetailPage> {
  // AI-generated START - 状态变量
  late TextEditingController _titleController;
  late TextEditingController _categoryController;
  late TextEditingController _promptController;
  // AI-generated END - 状态变量

  // AI-generated START - 最大字符数
  static const int _maxPromptLength = 5000;
  // AI-generated END - 最大字符数

  @override
  void initState() {
    super.initState();

    final provider = Provider.of<MPTemplateDetailProvider>(context, listen: false);

    // 初始化控制器
    _titleController = TextEditingController();
    _categoryController = TextEditingController();
    _promptController = TextEditingController();

    // 初始化 provider（根据 templateId 判断是新增还是编辑）
    provider.initializeTemplate(widget.templateId, widget.template).then((_) {
      if (mounted) {
        // 更新控制器
        if (provider.template != null) {
          _titleController.text = provider.template!.title ?? '';
          _categoryController.text = provider.category;
          _promptController.text = provider.template!.prompt ?? '';
        }
      }
    });
  }

  @override
  void dispose() {
    _titleController.dispose();
    _categoryController.dispose();
    _promptController.dispose();
    super.dispose();
  }

  // AI-generated START - 保存模板
  Future<void> _saveTemplate() async {
    final provider = Provider.of<MPTemplateDetailProvider>(context, listen: false);

    // 更新 provider 中的数据
    provider.updateTitle(_titleController.text);
    provider.updateContent(_promptController.text);
    provider.updateCategory(_categoryController.text);

    final success = await provider.saveTemplate();
    if (success) {
      MPToastUtils.showMessage('模板已保存');
      Navigator.pop(context, true);
    }
  }
  // AI-generated END - 保存模板

  // AI-generated START - 设置为默认模板
  Future<void> _setAsDefaultTemplate() async {
    final provider = Provider.of<MPTemplateDetailProvider>(context, listen: false);

    await provider.setAsDefaultTemplate();
  }
  // AI-generated END - 设置为默认模板

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Consumer<MPTemplateDetailProvider>(
      builder: (context, provider, child) {
        return Scaffold(
          backgroundColor: Colors.white,
          appBar: const MPCommonAppBar(
            title: '模板预览',
          ),
          body: provider.isLoading
              ? const Center(child: CircularProgressIndicator())
              : SingleChildScrollView(
                  child: Padding(
                    padding: const EdgeInsets.all(16.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        _buildTemplateNameField(provider),
                        const SizedBox(height: 24.0),
                        _buildCategoryField(provider),
                        const SizedBox(height: 24.0),
                        _buildPromptField(provider),
                      ],
                    ),
                  ),
                ),
          bottomNavigationBar: _buildBottomButtons(provider),
        );
      },
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建模板名称输入框
  Widget _buildTemplateNameField(MPTemplateDetailProvider provider) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          '模板名称',
          style: TextStyle(
            fontSize: 14.0,
            fontWeight: FontWeight.w500,
            color: Color(0xFF1F2937),
          ),
        ),
        const SizedBox(height: 8.0),
        Row(
          children: [
            _buildTemplateIcon(provider),
            const SizedBox(width: 8.0),
            Expanded(
              child: Container(
                decoration: BoxDecoration(
                  color: const Color(0xFFF9FAFB),
                  borderRadius: BorderRadius.circular(8.0),
                ),
                child: TextField(
                  controller: _titleController,
                  readOnly: !widget.isMyTemplate,
                  onChanged: widget.isMyTemplate
                      ? (value) {
                          provider.updateTitle(value);
                        }
                      : null,
                  decoration: const InputDecoration(
                    hintText: '模板名称',
                    hintStyle: TextStyle(
                      fontSize: 14.0,
                      color: Color(0xFF9CA3AF),
                    ),
                    border: InputBorder.none,
                    enabledBorder: InputBorder.none,
                    focusedBorder: InputBorder.none,
                    contentPadding: EdgeInsets.all(16.0),
                    isDense: true,
                    isCollapsed: true,
                    filled: true,
                  ),
                  style: const TextStyle(
                    fontSize: 14.0,
                    color: Color(0xFF111827),
                  ),
                ),
              ),
            ),
          ],
        )
      ],
    );
  }
  // AI-generated END - 构建模板名称输入框

  // AI-generated START - 构建模板图标
  /// 构建模板图标（网络图片或本地图标）
  Widget _buildTemplateIcon(MPTemplateDetailProvider provider) {
    final iconUrl = provider.template?.icon;

    if (iconUrl != null && iconUrl.isNotEmpty) {
      // 使用网络图片
      return ClipRRect(
        borderRadius: BorderRadius.circular(8.0),
        child: Image.network(
          iconUrl,
          width: 48.0,
          height: 48.0,
          fit: BoxFit.cover,
          errorBuilder: (context, error, stackTrace) {
            // 网络图片加载失败时，使用本地图标
            return _buildLocalIcon();
          },
          loadingBuilder: (context, child, loadingProgress) {
            if (loadingProgress == null) {
              return child;
            }
            // 显示加载指示器
            return Container(
              width: 48.0,
              height: 48.0,
              decoration: BoxDecoration(
                color: const Color(0xFFF9FAFB),
                borderRadius: BorderRadius.circular(8.0),
              ),
              child: Center(
                child: SizedBox(
                  width: 24.0,
                  height: 24.0,
                  child: CircularProgressIndicator(
                    strokeWidth: 2.0,
                    value: loadingProgress.expectedTotalBytes != null
                        ? loadingProgress.cumulativeBytesLoaded / loadingProgress.expectedTotalBytes!
                        : null,
                  ),
                ),
              ),
            );
          },
        ),
      );
    } else {
      // 没有网络图片时，使用本地图标
      return _buildLocalIcon();
    }
  }

  /// 构建本地图标
  Widget _buildLocalIcon() {
    return Container(
      width: 48.0,
      height: 48.0,
      decoration: BoxDecoration(
        color: const Color(0xFFFCE7F6),
        borderRadius: BorderRadius.circular(8.0),
      ),
      child: const Icon(
        Icons.description,
        color: Color(0xFFEC4899),
        size: 24.0,
      ),
    );
  }
  // AI-generated END - 构建模板图标

  // AI-generated START - 构建类别输入框
  Widget _buildCategoryField(MPTemplateDetailProvider provider) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          '类别',
          style: TextStyle(
            fontSize: 14.0,
            fontWeight: FontWeight.w500,
            color: Color(0xFF1F2937),
          ),
        ),
        const SizedBox(height: 8.0),
        Container(
          decoration: BoxDecoration(
            color: const Color(0xFFF9FAFB),
            borderRadius: BorderRadius.circular(8.0),
          ),
          child: TextField(
            controller: _categoryController,
            readOnly: !widget.isMyTemplate,
            decoration: InputDecoration(
              hintText: '请选择类别',
              hintStyle: const TextStyle(
                fontSize: 14.0,
                color: Color(0xFF9CA3AF),
              ),
              suffixIcon: widget.isMyTemplate
                  ? const Icon(
                      Icons.arrow_forward_ios,
                      size: 14.0,
                      color: Color(0xFF111827),
                    )
                  : null,
              border: InputBorder.none,
              enabledBorder: InputBorder.none,
              focusedBorder: InputBorder.none,
              contentPadding: const EdgeInsets.all(16.0),
              isDense: true,
              isCollapsed: true,
            ),
            style: const TextStyle(
              fontSize: 14.0,
              color: Color(0xFF111827),
            ),
            onTap: widget.isMyTemplate
                ? () {
                    // TODO: 实现类别选择
                    debugPrint('选择类别');
                    provider.updateCategory('工作');
                  }
                : null,
          ),
        )
      ],
    );
  }
  // AI-generated END - 构建类别输入框

  // AI-generated START - 构建Prompt输入框
  Widget _buildPromptField(MPTemplateDetailProvider provider) {
    final currentLength = _promptController.text.length;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            const Text(
              'Prompt',
              style: TextStyle(
                fontSize: 14.0,
                fontWeight: FontWeight.w500,
                color: Color(0xFF1F2937),
              ),
            ),
            Text(
              '$currentLength/$_maxPromptLength',
              style: TextStyle(
                fontSize: 12.0,
                color: currentLength > _maxPromptLength ? Colors.red : const Color(0xFF9CA3AF),
              ),
            ),
          ],
        ),
        const SizedBox(height: 4.0),
        const Text(
          '在发布过程中所做的修改将不会影响原本的自定义模板',
          style: TextStyle(
            fontSize: 12.0,
            color: Color(0xFF9CA3AF),
          ),
        ),
        const SizedBox(height: 8.0),
        Container(
          decoration: BoxDecoration(
            color: const Color(0xFFF9FAFB),
            borderRadius: BorderRadius.circular(8.0),
          ),
          child: TextField(
            controller: _promptController,
            readOnly: !widget.isMyTemplate,
            maxLines: null,
            minLines: 10,
            maxLength: _maxPromptLength,
            decoration: const InputDecoration(
              hintText: '请输入Prompt内容',
              hintStyle: TextStyle(
                fontSize: 14.0,
                color: Color(0xFF9CA3AF),
              ),
              border: InputBorder.none,
              enabledBorder: InputBorder.none,
              focusedBorder: InputBorder.none,
              filled: true,
              contentPadding: EdgeInsets.all(16.0),
            ),
            style: const TextStyle(
              fontSize: 14.0,
              color: Color(0xFF111827),
            ),
            onChanged: widget.isMyTemplate
                ? (value) {
                    provider.updateContent(value);
                    setState(() {}); // 更新字符计数
                  }
                : null,
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建Prompt输入框

  // AI-generated START - 构建底部按钮
  Widget _buildBottomButtons(MPTemplateDetailProvider provider) {
    return Container(
      padding: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.1),
            spreadRadius: 1,
            blurRadius: 4,
            offset: const Offset(0, -2),
          ),
        ],
      ),
      child: SafeArea(
        child: Row(
          children: [
            if (widget.isMyTemplate) ...[
              Expanded(
                child: OutlinedButton(
                  onPressed: provider.isLoading ? null : _saveTemplate,
                  style: OutlinedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16.0),
                    side: const BorderSide(color: Color(0xFF1F2937)),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8.0),
                    ),
                  ),
                  child: const Text(
                    '保存',
                    style: TextStyle(
                      fontSize: 16.0,
                      fontWeight: FontWeight.w500,
                      color: Color(0xFF1F2937),
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 12.0),
            ],
            Expanded(
              child: ElevatedButton(
                onPressed: provider.isLoading ? null : _setAsDefaultTemplate,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16.0),
                  backgroundColor: const Color(0xFF1F2937), // 黑色
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(8.0),
                  ),
                ),
                child: const Text(
                  '设置为默认模板',
                  style: TextStyle(
                    fontSize: 16.0,
                    fontWeight: FontWeight.w500,
                    color: Colors.white,
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建底部按钮
}
// AI-generated END - template_detail_page.dart
