// AI-generated START - 模版选择页面 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_custom_utils/mp_const_utils.dart';
import 'package:omi/pages/mp_custom_utils/mp_toast_utils.dart';
import 'package:omi/pages/mp_newsetting/home/widgets/mp_common_app_bar.dart';
import 'package:omi/pages/mp_template%20_selection/providers/template_detail_provider.dart';
import 'package:omi/pages/mp_template%20_selection/providers/template_selection_provider.dart';
import 'package:omi/pages/mp_template%20_selection/template_detail_page.dart';
import 'package:omi/pages/mp_template%20_selection/widgets/horizontal_scroll_template_card.dart';
import 'package:provider/provider.dart';

enum TemplateSelectionPageType {
  /// 已选模版
  select,

  /// 社区
  community,
}

extension TemplateSelectionPageTypeExtension on TemplateSelectionPageType {
  String get title {
    switch (this) {
      case TemplateSelectionPageType.select:
        return '选择模版';
      case TemplateSelectionPageType.community:
        return '模板社区';
    }
  }
}

/// 模版选择页面
/// 显示AI总结模版列表，支持选择和预览
class TemplateSelectionPage extends StatefulWidget {
  // AI-generated START - 构造函数
  const TemplateSelectionPage({
    super.key,
    this.type = TemplateSelectionPageType.community,
    this.onUseTemplate,
  });
  // AI-generated END - 构造函数

  final TemplateSelectionPageType type;

  /// 使用模版回调
  final Function(HorizontalScrollTemplateItem item)? onUseTemplate;

  // AI-generated START - 创建状态
  @override
  State<TemplateSelectionPage> createState() => _TemplateSelectionPageState();
  // AI-generated END - 创建状态
}

class _TemplateSelectionPageState extends State<TemplateSelectionPage> {
  // AI-generated START - 初始化方法
  @override
  void initState() {
    super.initState();
    // AI-generated START - 加载模版列表
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted) return;
      // 使用 Future.microtask 确保在下一帧执行，避免在构建过程中触发 notifyListeners
      Future.microtask(() {
        if (!mounted) return;
        final provider = Provider.of<TemplateSelectionProvider>(context, listen: false);
        provider.loadTemplates();
      });
    });
    // AI-generated END - 加载模版列表
  }
  // AI-generated END - 初始化方法

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: MPConstUtils.backgroundColorGrey,
      appBar: MPCommonAppBar(
        title: widget.type.title,
        actions: [
          IconButton(
            icon: const Icon(Icons.search),
            onPressed: () {
              MPToastUtils.showFeatureComingSoon();
            },
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildTemplateList(context),
                ],
              ),
            ),
          ),
          // 底部应用按钮
          _buildApplyButton(context),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建模版列表
  Widget _buildTemplateList(BuildContext context) {
    // 使用 Provider 获取模版列表
    return Consumer<TemplateSelectionProvider>(
      builder: (context, provider, child) {
        final cardItems = provider.templates;

        if (cardItems.isEmpty) {
          if (provider.isLoading) {
            return const Center(
              child: Padding(
                padding: EdgeInsets.all(20.0),
                child: CircularProgressIndicator(),
              ),
            );
          }
          if (provider.error != null) {
            return Center(
              child: Padding(
                padding: const EdgeInsets.all(20.0),
                child: Text(
                  provider.error!,
                  style: const TextStyle(color: Colors.red),
                ),
              ),
            );
          }
          return const SizedBox.shrink();
        }

        // 显示所有横向滑动模版卡片
        return Column(
          children: cardItems.asMap().entries.map((entry) {
            final cardItem = entry.value;
            return HorizontalScrollTemplateCard(
              item: cardItem,
              selectedItem: provider.selectedItem,
              onItemTap: (item) async {
                // 如果是创建模板项，导航到创建模板页面
                if (item.isCreateItem) {
                  await _navigateToCreateTemplate(context);
                  return;
                }
                if (widget.type == TemplateSelectionPageType.select) {
                  provider.selectTemplate(item);
                  return;
                }
                await _navigateToTemplateDetail(context, item.id, item.isMyTemplate);
              },
            );
          }).toList(),
        );
      },
    );
  }
  // AI-generated END - 构建模版列表

  // AI-generated START - 导航到创建模板页面
  /// 导航到创建模板页面
  Future<void> _navigateToCreateTemplate(BuildContext context) async {
    final result = await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => ChangeNotifierProvider(
          create: (_) => MPTemplateDetailProvider(),
          child: const MPTemplateDetailPage(
            templateId: null, // null 表示新增模式
            isMyTemplate: true,
          ),
        ),
      ),
    );

    // 如果返回 true，表示模板已保存，需要刷新页面
    if (result == true && mounted) {
      final provider = Provider.of<TemplateSelectionProvider>(context, listen: false);
      provider.loadTemplates();
    }
  }
  // AI-generated END - 导航到创建模板页面

  // AI-generated START - 导航到模板详情页面
  /// 导航到模板详情页面
  Future<void> _navigateToTemplateDetail(BuildContext context, String templateId, bool isMyTemplate) async {
    final result = await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => ChangeNotifierProvider(
          create: (_) => MPTemplateDetailProvider(),
          child: MPTemplateDetailPage(
            templateId: templateId,
            isMyTemplate: isMyTemplate,
          ),
        ),
      ),
    );

    // 如果返回 true，表示模板已保存，需要刷新页面
    if (result == true && mounted) {
      final provider = Provider.of<TemplateSelectionProvider>(context, listen: false);
      provider.loadTemplates();
    }
  }
  // AI-generated END - 导航到模板详情页面

  // AI-generated START - 构建应用按钮
  Widget _buildApplyButton(BuildContext context) {
    if (widget.type != TemplateSelectionPageType.select) {
      return const SizedBox.shrink();
    }
    return Container(
      padding: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.1),
            spreadRadius: 1,
            blurRadius: 4,
            offset: const Offset(0, -2),
          ),
        ],
      ),
      child: SizedBox(
        width: double.infinity,
        child: Consumer<TemplateSelectionProvider>(
          builder: (context, provider, child) {
            final hasSelection = provider.selectedItem != null;
            return ElevatedButton(
              onPressed: hasSelection
                  ? () {
                      widget.onUseTemplate?.call(provider.selectedItem!);
                      Navigator.pop(context);
                    }
                  : null,
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 16.0),
                backgroundColor: const Color(0xFF1F2937), // 黑色
                disabledBackgroundColor: Colors.grey[300],
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8.0),
                ),
              ),
              child: const Text(
                '使用此模版',
                style: TextStyle(
                  fontSize: 16.0,
                  fontWeight: FontWeight.w500,
                  color: Colors.white,
                ),
              ),
            );
          },
        ),
      ),
    );
  }
  // AI-generated END - 构建应用按钮
}
// AI-generated END - template_selection_page.dart
