// AI-generated START - 专家详情头像和名字卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';

/// 专家详情头像和名字卡片组件
/// 只读显示专家头像和名字
class MPExpertDetailAvatarNameCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const MPExpertDetailAvatarNameCard({
    super.key,
    required this.name,
    required this.avatar,
  });
  // AI-generated END - 构造函数

  /// 专家名字
  final String name;

  /// 专家头像URL
  final String avatar;

  // AI-generated START - 构建默认头像
  Widget _buildDefaultAvatar() {
    return Image.asset(
      Assets.images.mpAddExportRobot.path,
      width: 48.0,
      height: 48.0,
      fit: BoxFit.cover,
    );
  }
  // AI-generated END - _buildDefaultAvatar

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      padding: const EdgeInsets.all(24.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12.0),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withAlpha(5),
            blurRadius: 8.0,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        children: [
          // AI-generated START - 头像区域
          SizedBox(
            width: 96.0,
            height: 96.0,
            child: ClipOval(
              child: avatar.isNotEmpty
                  ? Image.network(
                      avatar,
                      fit: BoxFit.cover,
                      errorBuilder: (context, error, stackTrace) {
                        return _buildDefaultAvatar();
                      },
                    )
                  : _buildDefaultAvatar(),
            ),
          ),
          const SizedBox(height: 16.0),
          // AI-generated END - 头像区域

          // AI-generated START - 名字显示
          Text(
            name.isNotEmpty ? name : '未命名专家',
            style: const TextStyle(
              fontSize: 18.0,
              color: Color(0xFF212121),
              fontWeight: FontWeight.w600,
            ),
          ),
          // AI-generated END - 名字显示
        ],
      ),
    );
  }
  // AI-generated END - 构建方法
}
// AI-generated END - mp_expert_detail_avatar_name_card.dart

