// AI-generated START - 专家详情 Prompt 卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/providers/mp_add_export_provider.dart';

/// 专家详情 Prompt 卡片组件
/// 只读显示专家 Prompt
class MPExpertDetailPromptCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const MPExpertDetailPromptCard({
    super.key,
    required this.skillType,
    required this.prompt,
  });
  // AI-generated END - 构造函数

  /// 技能类型
  final MPExpertSkillType skillType;

  /// Prompt 内容
  final String prompt;

  // AI-generated START - 获取标题
  String _getTitle() {
    switch (skillType) {
      case MPExpertSkillType.chat:
        return '专家沟通技能描述 (Prompt)';
      case MPExpertSkillType.feedback:
        return '专家反馈技能描述 (Prompt)';
    }
  }
  // AI-generated END - _getTitle

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      padding: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12.0),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 8.0,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // AI-generated START - 标题
          Text(
            _getTitle(),
            style: const TextStyle(
              fontSize: 14.0,
              fontWeight: FontWeight.w500,
              color: Color(0xFF374151),
            ),
          ),
          const SizedBox(height: 12.0),
          // AI-generated END - 标题

          // AI-generated START - Prompt 内容（只读）
          Container(
            padding: const EdgeInsets.all(16.0),
            decoration: BoxDecoration(
              color: const Color(0xFFF9FAFB),
              borderRadius: BorderRadius.circular(8.0),
              border: Border.all(
                color: Colors.grey.shade300,
                width: 1.0,
              ),
            ),
            child: Text(
              prompt.isNotEmpty ? prompt : '暂无描述',
              style: TextStyle(
                fontSize: 14.0,
                color: prompt.isNotEmpty ? const Color(0xFF212121) : Colors.grey.shade400,
                height: 1.5,
              ),
            ),
          ),
          // AI-generated END - Prompt 内容
        ],
      ),
    );
  }
  // AI-generated END - 构建方法
}
// AI-generated END - mp_expert_detail_prompt_card.dart

