// AI-generated START - 专家详情介绍卡片组件 - Generated by AI
import 'package:flutter/material.dart';

/// 专家详情介绍卡片组件
/// 只读显示专家介绍
class MPExpertDetailIntroductionCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const MPExpertDetailIntroductionCard({
    super.key,
    required this.about,
  });
  // AI-generated END - 构造函数

  /// 专家介绍
  final String about;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      padding: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12.0),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withAlpha(5),
            blurRadius: 8.0,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // AI-generated START - 标题
          const Text(
            '专家介绍',
            style: TextStyle(
              fontSize: 14.0,
              fontWeight: FontWeight.w500,
              color: Color(0xFF374151),
            ),
          ),
          const SizedBox(height: 12.0),
          // AI-generated END - 标题

          // AI-generated START - 介绍内容
          Text(
            about.isNotEmpty ? about : '暂无介绍',
            style: TextStyle(
              fontSize: 14.0,
              color: about.isNotEmpty ? const Color(0xFF212121) : Colors.grey.shade400,
              height: 1.5,
            ),
          ),
          // AI-generated END - 介绍内容
        ],
      ),
    );
  }
  // AI-generated END - 构建方法
}
// AI-generated END - mp_expert_detail_introduction_card.dart

