// AI-generated START - 专家详情反馈时间卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_custom_widgets/mp_custom_switch.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/widgets/mp_feedback_time_picker_dialog.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/providers/mp_export_detail_provider.dart';
import 'package:provider/provider.dart';

/// 专家详情反馈时间卡片组件
/// 显示提供反馈时间和自动发送开关（可编辑）
class MPExpertDetailFeedbackTimeCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const MPExpertDetailFeedbackTimeCard({
    super.key,
  });
  // AI-generated END - 构造函数

  // AI-generated START - 格式化时间
  String _formatTime(TimeOfDay time) {
    return '${time.hour.toString().padLeft(2, '0')}:${time.minute.toString().padLeft(2, '0')}';
  }
  // AI-generated END - _formatTime

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Consumer<MPExportDetailProvider>(
      builder: (context, provider, child) {
        final time = provider.feedbackTime ?? const TimeOfDay(hour: 9, minute: 0);
        final timeText = _formatTime(time);

        return Container(
          margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
          padding: const EdgeInsets.all(16.0),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12.0),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withAlpha(5),
                blurRadius: 8.0,
                offset: const Offset(0, 2),
              ),
            ],
          ),
          child: Row(
            children: [
              // AI-generated START - 提供反馈时间
              const Expanded(
                child: Text(
                  '提供反馈时间',
                  style: TextStyle(
                    fontSize: 14.0,
                    fontWeight: FontWeight.w500,
                    color: Color(0xFF374151),
                  ),
                ),
              ),

              _buildFeedbackTime(context, provider, time, timeText),
              // AI-generated END - 提供反馈时间

              const SizedBox(width: 4.0),

              const Text(
                '自动发送',
                style: TextStyle(
                  fontSize: 12.0,
                  fontWeight: FontWeight.normal,
                  color: Color(0xFF4B5563),
                ),
              ),
              const SizedBox(width: 4.0),
              _buildAutoSend(context, provider),
            ],
          ),
        );
      },
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建反馈时间选择器
  Widget _buildFeedbackTime(
    BuildContext context,
    MPExportDetailProvider provider,
    TimeOfDay time,
    String timeText,
  ) {
    return GestureDetector(
      onTap: () async {
        final TimeOfDay? picked = await MPFeedbackTimePickerDialog.show(
          context,
          initialTime: time,
        );
        if (picked != null) {
          provider.updateFeedbackTime(picked);
        }
      },
      child: Container(
        width: 80.0,
        height: 32.0,
        decoration: BoxDecoration(
          color: const Color(0xFFEFF6FF), // 浅蓝色背景
          borderRadius: BorderRadius.circular(8.0),
          border: Border.all(
            color: const Color(0xFFBFDBFE), // 蓝色边框
            width: 1.0,
          ),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(
              Icons.access_time,
              color: Color(0xFF2563EB),
              size: 14.0,
            ),
            const SizedBox(width: 2.0),
            Text(
              timeText,
              style: const TextStyle(
                fontSize: 14.0,
                fontWeight: FontWeight.normal,
                color: Color(0xFF2563EB),
              ),
            ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - _buildFeedbackTime

  // AI-generated START - 构建自动发送开关
  Widget _buildAutoSend(BuildContext context, MPExportDetailProvider provider) {
    return MPCustomSwitch(
      value: provider.autoSend,
      onChanged: (value) {
        provider.updateAutoSend(value);
      },
    );
  }
  // AI-generated END - _buildAutoSend
}
// AI-generated END - mp_expert_detail_feedback_time_card.dart

