// AI-generated START - 专家详情操作按钮卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/providers/mp_export_detail_provider.dart';
import 'package:provider/provider.dart';

/// 专家详情操作按钮卡片组件
/// 显示添加/取消添加按钮
class MPExpertDetailActionCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const MPExpertDetailActionCard({
    super.key,
  });
  // AI-generated END - 构造函数

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Consumer<MPExportDetailProvider>(
      builder: (context, provider, child) {
        final isAdded = provider.isAdded;
        final isSubmitting = provider.isSubmitting;

        return Container(
          margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
          padding: const EdgeInsets.all(16.0),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12.0),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withAlpha(5),
                blurRadius: 8.0,
                offset: const Offset(0, 2),
              ),
            ],
          ),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              // AI-generated START - 左侧按钮（取消/取消添加）
              Expanded(
                child: _buildLeftButton(context, provider, isAdded, isSubmitting),
              ),
              // AI-generated END - 左侧按钮

              const SizedBox(width: 12.0),

              // AI-generated START - 右侧按钮（添加/保存）
              Expanded(
                child: _buildRightButton(context, provider, isAdded, isSubmitting),
              ),
              // AI-generated END - 右侧按钮
            ],
          ),
        );
      },
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建左侧按钮（取消/取消添加）
  Widget _buildLeftButton(
    BuildContext context,
    MPExportDetailProvider provider,
    bool isAdded,
    bool isSubmitting,
  ) {
    if (isAdded) {
      // 已添加状态：显示"取消添加"按钮（红色）
      return GestureDetector(
        onTap: isSubmitting
            ? null
            : () async {
                final success = await provider.removeExpert();
                if (context.mounted && success) {
                  Navigator.of(context).pop(true); // 返回 true 表示需要刷新列表
                }
              },
        child: Container(
          height: 56.0,
          decoration: BoxDecoration(
            color: isSubmitting ? Colors.grey.shade300 : const Color(0xFFEF4444), // 红色背景
            borderRadius: BorderRadius.circular(16.0),
            boxShadow: isSubmitting
                ? null
                : [
                    BoxShadow(
                      color: Colors.black.withAlpha(5),
                      blurRadius: 4.0,
                      offset: const Offset(0, 2),
                    ),
                  ],
          ),
          child: Center(
            child: isSubmitting
                ? const SizedBox(
                    width: 20.0,
                    height: 20.0,
                    child: CircularProgressIndicator(
                      strokeWidth: 2.0,
                      valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                    ),
                  )
                : const Text(
                    '取消添加',
                    style: TextStyle(
                      fontSize: 16.0,
                      fontWeight: FontWeight.w600,
                      color: Colors.white,
                    ),
                  ),
          ),
        ),
      );
    } else {
      // 未添加状态：显示"取消"按钮（浅灰色）
      return GestureDetector(
        onTap: isSubmitting
            ? null
            : () {
                Navigator.of(context).pop();
              },
        child: Container(
          height: 56.0,
          decoration: BoxDecoration(
            color: const Color(0xFFF3F4F6), // 浅灰色背景
            borderRadius: BorderRadius.circular(16.0),
            boxShadow: isSubmitting
                ? null
                : [
                    BoxShadow(
                      color: Colors.black.withAlpha(5),
                      blurRadius: 4.0,
                      offset: const Offset(0, 2),
                    ),
                  ],
          ),
          child: Center(
            child: Text(
              '取消',
              style: TextStyle(
                fontSize: 16.0,
                fontWeight: FontWeight.w600,
                color: isSubmitting ? Colors.grey.shade400 : const Color(0xFF374151),
              ),
            ),
          ),
        ),
      );
    }
  }
  // AI-generated END - _buildLeftButton

  // AI-generated START - 构建右侧按钮（添加/保存）
  Widget _buildRightButton(
    BuildContext context,
    MPExportDetailProvider provider,
    bool isAdded,
    bool isSubmitting,
  ) {
    if (isAdded) {
      // 已添加状态：显示"保存"按钮（蓝色，用于保存反馈时间）
      return GestureDetector(
        onTap: isSubmitting
            ? null
            : () async {
                final success = await provider.saveFeedbackTime();
                if (context.mounted && success) {
                  Navigator.of(context).pop(true); // 返回 true 表示需要刷新列表
                }
              },
        child: Container(
          height: 48.0,
          decoration: BoxDecoration(
            color: isSubmitting ? Colors.grey.shade300 : const Color(0xFF2563EB), // 蓝色背景
            borderRadius: BorderRadius.circular(16.0),
            boxShadow: isSubmitting
                ? null
                : [
                    BoxShadow(
                      color: Colors.black.withAlpha(5),
                      blurRadius: 4.0,
                      offset: const Offset(0, 2),
                    ),
                  ],
          ),
          child: Center(
            child: isSubmitting
                ? const SizedBox(
                    width: 20.0,
                    height: 20.0,
                    child: CircularProgressIndicator(
                      strokeWidth: 2.0,
                      valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                    ),
                  )
                : const Text(
                    '保存',
                    style: TextStyle(
                      fontSize: 16.0,
                      fontWeight: FontWeight.w600,
                      color: Colors.white,
                    ),
                  ),
          ),
        ),
      );
    } else {
      // 未添加状态：显示"添加"按钮（蓝色）
      return GestureDetector(
        onTap: isSubmitting
            ? null
            : () async {
                final success = await provider.addExpert();
                if (context.mounted && success) {
                  Navigator.of(context).pop(true); // 返回 true 表示需要刷新列表
                }
              },
        child: Container(
          height: 48.0,
          decoration: BoxDecoration(
            color: isSubmitting ? Colors.grey.shade300 : const Color(0xFF2563EB), // 蓝色背景
            borderRadius: BorderRadius.circular(16.0),
            boxShadow: isSubmitting
                ? null
                : [
                    BoxShadow(
                      color: Colors.black.withAlpha(5),
                      blurRadius: 4.0,
                      offset: const Offset(0, 2),
                    ),
                  ],
          ),
          child: Center(
            child: isSubmitting
                ? const SizedBox(
                    width: 20.0,
                    height: 20.0,
                    child: CircularProgressIndicator(
                      strokeWidth: 2.0,
                      valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                    ),
                  )
                : const Text(
                    '添加',
                    style: TextStyle(
                      fontSize: 16.0,
                      fontWeight: FontWeight.w600,
                      color: Colors.white,
                    ),
                  ),
          ),
        ),
      );
    }
  }
  // AI-generated END - _buildRightButton
}
// AI-generated END - mp_expert_detail_action_card.dart
