// AI-generated START - 专家详情类别卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/widgets/mp_expert_category_card.dart';

/// 专家详情类别卡片组件
/// 只读显示专家类别
class MPExpertDetailCategoryCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const MPExpertDetailCategoryCard({
    super.key,
    required this.type,
  });
  // AI-generated END - 构造函数

  /// 专家类别
  final String type;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    final categories = MPExpertCategoryCard.getDefaultCategories();
    final category = categories.firstWhere(
      (cat) => cat.id == type,
      orElse: () => categories.first,
    );

    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      padding: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12.0),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withAlpha(5),
            blurRadius: 8.0,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // AI-generated START - 标题
          const Text(
            '专家类别',
            style: TextStyle(
              fontSize: 14.0,
              fontWeight: FontWeight.w500,
              color: Color(0xFF374151),
            ),
          ),
          const SizedBox(height: 12.0),
          // AI-generated END - 标题

          // AI-generated START - 类别显示（只读）
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 14.0),
            decoration: BoxDecoration(
              color: const Color(0xFFF9FAFB),
              borderRadius: BorderRadius.circular(8.0),
            ),
            child: Row(
              children: [
                Expanded(
                  child: Text(
                    category.name,
                    style: const TextStyle(
                      fontSize: 14.0,
                      color: Color(0xFF111827),
                      fontWeight: FontWeight.normal,
                    ),
                  ),
                ),
              ],
            ),
          ),
          // AI-generated END - 类别显示
        ],
      ),
    );
  }
  // AI-generated END - 构建方法
}
// AI-generated END - mp_expert_detail_category_card.dart

