// AI-generated START - 专家详情技能卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/providers/mp_add_export_provider.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/widgets/mp_expert_skills_card.dart';

/// 专家详情技能卡片组件
/// 只读显示专家技能
class MPExpertDetailSkillsCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const MPExpertDetailSkillsCard({
    super.key,
    required this.capabilities,
  });
  // AI-generated END - 构造函数

  /// 专家能力列表
  final List<String> capabilities;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    final skills = MPExpertSkillsCard.getDefaultSkills();
    final selectedSkills = capabilities.map((cap) {
      if (cap == 'chat') return MPExpertSkillType.chat;
      if (cap == 'feedback') return MPExpertSkillType.feedback;
      return null;
    }).whereType<MPExpertSkillType>().toSet();

    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      padding: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12.0),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 8.0,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // AI-generated START - 标题
          const Text(
            '专家技能',
            style: TextStyle(
              fontSize: 14.0,
              fontWeight: FontWeight.w500,
              color: Color(0xFF374151),
            ),
          ),
          const SizedBox(height: 16.0),
          // AI-generated END - 标题

          // AI-generated START - 技能选项列表（只读）
          ...skills.where((skill) => selectedSkills.contains(skill.type)).map((skill) {
            return Padding(
              padding: const EdgeInsets.only(bottom: 8.0),
              child: _buildSkillOption(skill, true),
            );
          }),
          // AI-generated END - 技能选项列表
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建技能选项
  Widget _buildSkillOption(MPExpertSkillOption skill, bool isSelected) {
    return Container(
      padding: const EdgeInsets.all(12.0),
      decoration: BoxDecoration(
        color: isSelected ? skill.color.withAlpha(10) : Colors.white,
        borderRadius: BorderRadius.circular(12.0),
        border: Border.all(
          color: isSelected ? skill.color : const Color(0xFFE5E7EB),
          width: 1.0,
        ),
      ),
      child: Row(
        children: [
          // AI-generated START - 图标
          Image.asset(
            isSelected ? skill.selectedIcon! : skill.icon!,
            width: 40.0,
            height: 40.0,
            fit: BoxFit.contain,
          ),
          const SizedBox(width: 8.0),
          // AI-generated END - 图标

          // AI-generated START - 文本内容
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  skill.title,
                  style: TextStyle(
                    fontSize: 14.0,
                    fontWeight: FontWeight.w600,
                    color: isSelected ? skill.color : const Color(0xFF374151),
                  ),
                ),
                const SizedBox(height: 4.0),
                Text(
                  skill.description,
                  style: const TextStyle(
                    fontSize: 12.0,
                    color: Color(0xFF6B7280),
                  ),
                ),
              ],
            ),
          ),
          // AI-generated END - 文本内容

          // AI-generated START - 选中指示器
          Container(
            width: 20.0,
            height: 20.0,
            decoration: BoxDecoration(
              color: skill.color,
              shape: BoxShape.circle,
            ),
            child: Center(
              child: Assets.images.mpAddExportChoose.image(
                width: 13.0,
                height: 12.0,
                fit: BoxFit.contain,
              ),
            ),
          ),
          // AI-generated END - 选中指示器
        ],
      ),
    );
  }
  // AI-generated END - _buildSkillOption
}
// AI-generated END - mp_expert_detail_skills_card.dart

