// AI-generated START - 我的声音卡片组件 - Generated by AI
import 'package:flutter/material.dart';
// 导出枚举，方便外部使用
import 'package:omi/pages/mp_newsetting/voice_recognition/widgets/voice_item_card.dart';

/// 我的声音数据项
class MyVoiceItem {
  // AI-generated START - 构造函数
  const MyVoiceItem({
    required this.title,
    required this.duration,
    required this.date,
    this.icon,
    this.imageUrl,
    this.actionType,
    this.onTap,
    this.onActionTap,
  });
  // AI-generated END - 构造函数

  /// 标题
  final String title;

  /// 录音时长
  final String duration;

  /// 日期
  final String date;

  /// 本地图片路径（优先显示）
  final String? icon;

  /// 图标图片URL或资源路径（当icon为空时使用）
  final String? imageUrl;

  /// 操作类型（编辑或删除）
  final VoiceItemActionType? actionType;

  /// 卡片点击回调
  final VoidCallback? onTap;

  /// 按钮点击回调
  final Function(VoiceItemActionType)? onActionTap;
}

/// 我的声音卡片组件
/// 显示多个用户录制的语音信息，包括时长和日期
class MyVoiceCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const MyVoiceCard({
    super.key,
    required this.items,
  });
  // AI-generated END - 构造函数

  /// 声音数据项列表
  final List<MyVoiceItem> items;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    if (items.isEmpty) {
      return const SizedBox.shrink();
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // 标题（在外面，没有圆角）
        _buildHeader(),
        // 显示多个 item，每个 item 都是独立的圆角卡片
        ...items.map((item) => VoiceItemCard(
              item: item,
              actionType: item.actionType ?? VoiceItemActionType.edit, // 使用 item 的 actionType，默认为编辑
            )),
      ],
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建标题
  Widget _buildHeader() {
    return Padding(
      padding: const EdgeInsets.fromLTRB(16.0, 8.0, 16.0, 8.0),
      child: Text(
        '我的声音',
        style: const TextStyle(
          fontSize: 18.0,
          fontWeight: FontWeight.w600,
          color: Color(0xFF212121),
        ),
      ),
    );
  }
  // AI-generated END - 构建标题
}
// AI-generated END - my_voice_card.dart
