// AI-generated START - 我的声音卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';
import 'package:omi/pages/mp_newsetting/voice_recognition/widgets/voice_item_card.dart';

// 导出枚举，方便外部使用

/// 我的声音数据项
class MyVoiceItem {
  // AI-generated START - 构造函数
  const MyVoiceItem({
    required this.id,
    required this.title,
    required this.duration,
    required this.date,
    this.icon,
    this.imageUrl,
  });
  // AI-generated END - 构造函数

  /// 声音ID
  final String id;

  /// 标题
  final String title;

  /// 录音时长
  final String duration;

  /// 日期
  final String date;

  /// 本地图片路径（优先显示）
  final String? icon;

  /// 图标图片URL或资源路径（当icon为空时使用）
  final String? imageUrl;
}

/// 我的声音卡片组件
/// 显示多个用户录制的语音信息，包括时长和日期
class MyVoiceCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const MyVoiceCard({
    super.key,
    required this.items,
    this.onTap,
    this.onActionTap,
    this.onEmptyStateTap,
  });
  // AI-generated END - 构造函数

  /// 声音数据项列表
  final List<MyVoiceItem> items;

  /// 点击回调
  final Function(MyVoiceItem)? onTap;

  /// 按钮点击回调
  final Function(MyVoiceItem)? onActionTap;

  /// 空状态卡片点击回调（当没有录制声音时）
  final VoidCallback? onEmptyStateTap;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // 标题（在外面，没有圆角）
        _buildHeader(),
        // 如果列表为空，显示空状态卡片
        if (items.isEmpty)
          _buildEmptyStateCard()
        else
          // 显示多个 item，每个 item 都是独立的圆角卡片
          ...items.asMap().entries.map((entry) {
            final item = entry.value;
            return VoiceItemCard(
              item: item,
              onTap: () {
                onTap?.call(item);
              },
              onActionTap: () {
                onActionTap?.call(item);
              },
            );
          }),
      ],
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建标题
  Widget _buildHeader() {
    return const Padding(
      padding: EdgeInsets.fromLTRB(16.0, 8.0, 16.0, 8.0),
      child: Text(
        '我的声音',
        style: TextStyle(
          fontSize: 16.0,
          fontWeight: FontWeight.w600,
          color: Color(0xFF212121),
        ),
      ),
    );
  }
  // AI-generated END - 构建标题

  // AI-generated START - 构建空状态卡片
  Widget _buildEmptyStateCard() {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 12.0, vertical: 4.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12.0),
        border: Border.all(
          color: Colors.grey.shade300,
          width: 1.0,
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withValues(alpha: 0.1),
            spreadRadius: 1,
            blurRadius: 4,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: InkWell(
        onTap: onEmptyStateTap,
        borderRadius: BorderRadius.circular(12.0),
        child: Padding(
          padding: const EdgeInsets.all(12.0),
          child: Row(
            children: [
              // 左侧图标
              Assets.images.mpVoiceWaitingAdd.image(
                width: 56.0,
                height: 56.0,
                fit: BoxFit.contain,
              ),
              const SizedBox(width: 12.0),
              // 中间文本信息
              const Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      '我的声音',
                      style: TextStyle(
                        fontSize: 16.0,
                        fontWeight: FontWeight.w500,
                        color: Color(0xFF212121),
                      ),
                    ),
                    SizedBox(height: 2.0),
                    Text(
                      '等待录制',
                      style: TextStyle(
                        fontSize: 12.0,
                        color: Colors.grey,
                      ),
                    ),
                  ],
                ),
              ),
              // 右侧箭头图标
              Assets.images.settingRightArrow1.image(
                width: 19.0,
                height: 18.0,
              ),
            ],
          ),
        ),
      ),
    );
  }
  // AI-generated END - 构建空状态卡片
}
// AI-generated END - my_voice_card.dart
