// AI-generated START - 声纹识别信息卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';

/// 声纹识别信息卡片组件
/// 显示关于声纹识别的说明信息
class VoiceprintInfoCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const VoiceprintInfoCard({
    super.key,
    this.title = '关于声纹识别',
    this.content = '保存的声音可以帮助系统更准确地识别对话中的不同人物。每个声音至少需要90秒的录音样本。',
  });
  // AI-generated END - 构造函数

  /// 标题
  final String title;

  /// 内容文本
  final String content;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.all(16.0),
      padding: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12.0),
        border: Border.all(
          color: const Color(0xFFE0E7FF),
          width: 1.0,
        ),
        gradient: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFFEEF2FF), Color(0xFFFAF5FF)],
        ),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // 信息图标
          _buildInfoIcon(),
          const SizedBox(width: 16.0),
          // 文本内容
          Expanded(
            child: _buildContent(),
          ),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建信息图标
  Widget _buildInfoIcon() {
    return Assets.images.mpVoiceHelp.image(
      width: 40.0,
      height: 40.0,
    );
  }
  // AI-generated END - 构建信息图标

  // AI-generated START - 构建内容文本
  Widget _buildContent() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // 标题
        Text(
          title,
          style: const TextStyle(
            fontSize: 14.0,
            fontWeight: FontWeight.bold,
            color: Color(0xFF212121),
          ),
        ),
        const SizedBox(height: 2.0),
        // 内容
        Text(
          content,
          style: TextStyle(
            fontSize: 12.0,
            color: Colors.grey[700],
            height: 1.5,
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建内容文本
}
// AI-generated END - voiceprint_info_card.dart
