// AI-generated START - 应用集成状态管理Provider - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_apps_integration/models/app_integration_data.dart';
import 'package:omi/pages/mp_apps_integration/widgets/app_integration_card.dart';
/// 应用集成状态管理Provider
/// 管理应用集成列表数据
class AppsIntegrationProvider with ChangeNotifier {
  // AI-generated START - 应用集成列表
  List<AppIntegrationData> _integrations = [];
  // AI-generated END - 应用集成列表

  // AI-generated START - 获取应用集成列表
  List<AppIntegrationData> get integrations => _integrations;
  // AI-generated END - 获取应用集成列表

  // AI-generated START - 构造函数
  AppsIntegrationProvider() {
    _loadMockData();
  }
  // AI-generated END - 构造函数

  // AI-generated START - 加载模拟数据
  void _loadMockData() {
    _integrations = [
      AppIntegrationData(
        appName: 'Google Calendar',
        description: '自动同步会议和日程安排',
        icon: Icons.calendar_today,
        iconColor: const Color(0xFF4285F4), // 蓝色
        isConnected: true,
        features: [
          const FeatureTag(label: '自动创建日历事件'),
          const FeatureTag(label: '会议提醒'),
          const FeatureTag(label: '日程同步'),
        ],
        onViewDetails: () {
          debugPrint('查看 Google Calendar 详情');
        },
        onDisconnect: () {
          debugPrint('断开 Google Calendar 连接');
        },
      ),
      AppIntegrationData(
        appName: 'Notion',
        description: '将笔记和总结同步到Notion',
        icon: Icons.description,
        iconColor: Colors.grey[800]!,
        isConnected: false,
        features: [
          const FeatureTag(label: '自动创建页面'),
          const FeatureTag(label: '笔记同步'),
          const FeatureTag(label: '数据库集成'),
        ],
        onViewDetails: () {
          debugPrint('查看 Notion 详情');
        },
        onConnect: () {
          debugPrint('连接 Notion');
        },
      ),
    ];
    notifyListeners();
  }
  // AI-generated END - 加载模拟数据

  // AI-generated START - 添加应用集成
  void addIntegration(AppIntegrationData integration) {
    _integrations.add(integration);
    notifyListeners();
  }
  // AI-generated END - 添加应用集成

  // AI-generated START - 删除应用集成
  void removeIntegration(int index) {
    if (index >= 0 && index < _integrations.length) {
      _integrations.removeAt(index);
      notifyListeners();
    }
  }
  // AI-generated END - 删除应用集成

  // AI-generated START - 更新应用集成
  void updateIntegration(int index, AppIntegrationData integration) {
    if (index >= 0 && index < _integrations.length) {
      _integrations[index] = integration;
      notifyListeners();
    }
  }
  // AI-generated END - 更新应用集成

  // AI-generated START - 切换连接状态
  void toggleConnection(int index) {
    if (index >= 0 && index < _integrations.length) {
      final integration = _integrations[index];
      _integrations[index] = AppIntegrationData(
        appName: integration.appName,
        description: integration.description,
        icon: integration.icon,
        iconColor: integration.iconColor,
        isConnected: !integration.isConnected,
        features: integration.features,
        onViewDetails: integration.onViewDetails,
        onConnect: integration.onConnect,
        onDisconnect: integration.onDisconnect,
      );
      notifyListeners();
    }
  }
  // AI-generated END - 切换连接状态

  // AI-generated START - 刷新数据
  void refresh() {
    _loadMockData();
  }
  // AI-generated END - 刷新数据
}
// AI-generated END - apps_integration_provider.dart

