// AI-generated START - 关注我们卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/newsetting/personal/widgets/basic_info_card.dart';

/// 关注我们卡片组件
/// 显示社交媒体和官方渠道的关注选项
class FollowUsCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const FollowUsCard({
    super.key,
    this.items,
    this.onOfficialWebsiteTap,
    this.onTwitterTap,
    this.onFacebookTap,
    this.onInstagramTap,
    this.onTiktokTap,
    this.onRatingTap,
  });
  // AI-generated END - 构造函数

  /// 关注我们项列表（可选，如果传入则使用传入的，否则使用默认生成的）
  final List<BasicInfoItem>? items;

  /// 官方网站点击回调
  final VoidCallback? onOfficialWebsiteTap;

  /// X (Twitter) 点击回调
  final VoidCallback? onTwitterTap;

  /// Facebook 点击回调
  final VoidCallback? onFacebookTap;

  /// Instagram 点击回调
  final VoidCallback? onInstagramTap;

  /// Tiktok 点击回调
  final VoidCallback? onTiktokTap;

  /// 评分与反馈点击回调
  final VoidCallback? onRatingTap;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    // 如果传入了 items，则使用传入的；否则使用默认生成的
    final displayItems = items ??
        [
          BasicInfoItem(
            title: '官方网站',
            subtitle: '',
            icon: Icons.language,
            iconColor: const Color(0xFF2196F3), // 蓝色
            onTap: onOfficialWebsiteTap,
          ),
          BasicInfoItem(
            title: 'X (原 Twitter)',
            subtitle: '',
            icon: Icons.alternate_email,
            iconColor: const Color(0xFF000000), // 黑色
            onTap: onTwitterTap,
          ),
          BasicInfoItem(
            title: 'Facebook',
            subtitle: '',
            icon: Icons.facebook,
            iconColor: const Color(0xFF1877F2), // Facebook 蓝色
            onTap: onFacebookTap,
          ),
          BasicInfoItem(
            title: 'Instagram',
            subtitle: '',
            icon: Icons.camera_alt_outlined,
            iconColor: const Color(0xFFE4405F), // Instagram 粉红色
            onTap: onInstagramTap,
          ),
          BasicInfoItem(
            title: 'Tiktok',
            subtitle: '',
            icon: Icons.music_note,
            iconColor: const Color(0xFF000000), // 黑色
            onTap: onTiktokTap,
          ),
          BasicInfoItem(
            title: '评分与反馈',
            subtitle: '',
            icon: Icons.star_outline,
            iconColor: const Color(0xFFFFC107), // 黄色
            onTap: onRatingTap,
          ),
        ];

    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12.0),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // 标题
          _buildHeader(),
          // 列表项
          ...displayItems.asMap().entries.map((entry) {
            final index = entry.key;
            final item = entry.value;
            return _buildListItem(item, index < displayItems.length - 1);
          }).toList(),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建标题
  Widget _buildHeader() {
    return Padding(
      padding: const EdgeInsets.fromLTRB(16.0, 16.0, 16.0, 12.0),
      child: Text(
        '关注我们',
        style: const TextStyle(
          fontSize: 18.0,
          fontWeight: FontWeight.w600,
          color: Color(0xFF212121),
        ),
      ),
    );
  }
  // AI-generated END - 构建标题

  // AI-generated START - 构建列表项
  Widget _buildListItem(BasicInfoItem item, bool showDivider) {
    return Column(
      children: [
        InkWell(
          onTap: item.onTap,
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 16.0),
            child: Row(
              children: [
                // 图标
                Container(
                  width: 40.0,
                  height: 40.0,
                  decoration: BoxDecoration(
                    color: item.iconColor,
                    shape: BoxShape.circle,
                  ),
                  child: Icon(
                    item.icon,
                    color: Colors.white,
                    size: 20.0,
                  ),
                ),
                const SizedBox(width: 16.0),
                // 文本内容
                Expanded(
                  child: Text(
                    item.title,
                    style: const TextStyle(
                      fontSize: 16.0,
                      fontWeight: FontWeight.w500,
                      color: Color(0xFF212121),
                    ),
                  ),
                ),
                // 右箭头
                Icon(
                  Icons.chevron_right,
                  color: Colors.grey[400],
                  size: 20.0,
                ),
              ],
            ),
          ),
        ),
        // 分隔线
        if (showDivider)
          Divider(
            height: 1.0,
            thickness: 1.0,
            color: Colors.grey[200],
            indent: 72.0, // 对齐到文本开始位置
          ),
      ],
    );
  }
  // AI-generated END - 构建列表项
}
// AI-generated END - follow_us_card.dart
