// AI-generated START - 应用集成数据模型 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_apps_integration/widgets/app_integration_card.dart';

/// 应用集成数据模型
class AppIntegrationData {
  // AI-generated START - 构造函数
  const AppIntegrationData({
    required this.appName,
    required this.description,
    required this.icon,
    required this.iconColor,
    this.isConnected = false,
    this.features = const [],
    this.onViewDetails,
    this.onConnect,
    this.onDisconnect,
  });
  // AI-generated END - 构造函数

  /// 应用名称
  final String appName;

  /// 描述文字
  final String description;

  /// 应用图标
  final IconData icon;

  /// 图标背景颜色
  final Color iconColor;

  /// 是否已连接
  final bool isConnected;

  /// 功能标签列表
  final List<FeatureTag> features;

  /// 查看详情回调
  final VoidCallback? onViewDetails;

  /// 连接回调
  final VoidCallback? onConnect;

  /// 断开连接回调
  final VoidCallback? onDisconnect;

  // AI-generated START - 转换为 AppIntegrationCard
  AppIntegrationCard toCard() {
    return AppIntegrationCard(
      appName: appName,
      description: description,
      icon: icon,
      iconColor: iconColor,
      isConnected: isConnected,
      features: features,
      onViewDetails: onViewDetails,
      onConnect: onConnect,
      onDisconnect: onDisconnect,
    );
  }
  // AI-generated END - 转换为 AppIntegrationCard
}
// AI-generated END - app_integration_data.dart
