// AI-generated START - 声纹识别状态管理Provider - Generated by AI
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:omi/pages/newsetting/voice_recognition/widgets/my_voice_card.dart';
import 'package:omi/pages/newsetting/voice_recognition/widgets/voice_item_card.dart';

/// 声纹识别状态管理Provider
/// 管理声音列表数据
class VoiceRecognitionProvider with ChangeNotifier {
  // AI-generated START - 声音列表
  List<MyVoiceItem> _voiceList = [];
  // AI-generated END - 声音列表

  // AI-generated START - 已保存的声音列表
  List<MyVoiceItem> _savedVoicesList = [];
  // AI-generated END - 已保存的声音列表

  // AI-generated START - 获取声音列表
  List<MyVoiceItem> get voiceList => _voiceList;
  // AI-generated END - 获取声音列表

  // AI-generated START - 获取已保存的声音列表
  List<MyVoiceItem> get savedVoicesList => _savedVoicesList;
  // AI-generated END - 获取已保存的声音列表

  // AI-generated START - 构造函数
  VoiceRecognitionProvider() {
    _loadMockData();
    _loadSavedVoicesData();
  }
  // AI-generated END - 构造函数

  // AI-generated START - 加载模拟数据
  void _loadMockData() {
    _voiceList = [
      MyVoiceItem(
        title: '我的声音',
        duration: '120秒',
        date: '2024-01-20',
        icon: 'assets/images/voice_icon1.png', // 优先显示本地图片
        imageUrl: 'assets/images/voice_icon1_backup.png', // icon 存在时不会使用
        onTap: () {
          debugPrint('点击了声音1');
        },
        onActionTap: (type) {
          if (type == VoiceItemActionType.delete) {
            debugPrint('删除声音1');
          }
          if (type == VoiceItemActionType.edit) {
            debugPrint('编辑声音1');
          }
        },
      ),
      MyVoiceItem(
        title: '工作录音',
        duration: '90秒',
        date: '2024-01-21',
        icon: 'assets/images/work_voice_icon.png', // 使用本地图片
        onTap: () {
          debugPrint('点击了声音2');
        },
        onActionTap: (type) {
          if (type == VoiceItemActionType.delete) {
            debugPrint('删除声音2');
          }
          if (type == VoiceItemActionType.edit) {
            debugPrint('编辑声音2');
          }
        },
      ),
      MyVoiceItem(
        title: '会议记录',
        duration: '150秒',
        date: '2024-01-22',
        imageUrl: 'https://example.com/voice_icon.png', // 没有 icon 时使用网络图片
        actionType: VoiceItemActionType.delete, // 使用删除操作
        onTap: () {
          debugPrint('点击了声音3');
        },
        onActionTap: (type) {
          if (type == VoiceItemActionType.delete) {
            debugPrint('删除声音3');
          }
          if (type == VoiceItemActionType.edit) {
            debugPrint('编辑声音3');
          }
        },
      ),
    ];
    notifyListeners();
  }
  // AI-generated END - 加载模拟数据

  // AI-generated START - 添加声音
  void addVoice(MyVoiceItem item) {
    _voiceList.add(item);
    notifyListeners();
  }
  // AI-generated END - 添加声音

  // AI-generated START - 删除声音
  void removeVoice(int index) {
    if (index >= 0 && index < _voiceList.length) {
      _voiceList.removeAt(index);
      notifyListeners();
    }
  }
  // AI-generated END - 删除声音

  // AI-generated START - 更新声音
  void updateVoice(int index, MyVoiceItem item) {
    if (index >= 0 && index < _voiceList.length) {
      _voiceList[index] = item;
      notifyListeners();
    }
  }
  // AI-generated END - 更新声音

  // AI-generated START - 加载已保存的声音模拟数据
  void _loadSavedVoicesData() {
    _savedVoicesList = [
      MyVoiceItem(
        title: '叶成功',
        duration: '95秒',
        date: '2024-01-15',
        imageUrl: 'assets/images/ye_chenggong.png',
        actionType: VoiceItemActionType.delete,
        onTap: () {
          debugPrint('点击了叶成功');
        },
        onActionTap: (type) {
          if (type == VoiceItemActionType.delete) {
            debugPrint('删除叶成功');
          }
        },
      ),
      MyVoiceItem(
        title: '叶天命',
        duration: '110秒',
        date: '2024-01-14',
        imageUrl: 'assets/images/ye_tianming.png',
        actionType: VoiceItemActionType.delete,
        onTap: () {
          debugPrint('点击了叶天命');
        },
        onActionTap: (type) {
          if (type == VoiceItemActionType.delete) {
            debugPrint('删除叶天命');
          }
        },
      ),
      MyVoiceItem(
        title: '叶无敌',
        duration: '105秒',
        date: '2024-01-12',
        imageUrl: 'assets/images/ye_wudi.png',
        actionType: VoiceItemActionType.delete,
        onTap: () {
          debugPrint('点击了叶无敌');
        },
        onActionTap: (type) {
          if (type == VoiceItemActionType.delete) {
            debugPrint('删除叶无敌');
          }
        },
      ),
      MyVoiceItem(
        title: '叶疯狂',
        duration: '98秒',
        date: '2024-01-10',
        imageUrl: 'assets/images/ye_fengkuang.png',
        actionType: VoiceItemActionType.delete,
        onTap: () {
          debugPrint('点击了叶疯狂');
        },
        onActionTap: (type) {
          if (type == VoiceItemActionType.delete) {
            debugPrint('删除叶疯狂');
          }
        },
      ),
      MyVoiceItem(
        title: '叶智慧',
        duration: '115秒',
        date: '2024-01-08',
        imageUrl: 'assets/images/ye_zhihui.png',
        actionType: VoiceItemActionType.delete,
        onTap: () {
          debugPrint('点击了叶智慧');
        },
        onActionTap: (type) {
          if (type == VoiceItemActionType.delete) {
            debugPrint('删除叶智慧');
          }
        },
      ),
      MyVoiceItem(
        title: '叶勇敢',
        duration: '92秒',
        date: '2024-01-05',
        imageUrl: 'assets/images/ye_yonggan.png',
        actionType: VoiceItemActionType.delete,
        onTap: () {
          debugPrint('点击了叶勇敢');
        },
        onActionTap: (type) {
          if (type == VoiceItemActionType.delete) {
            debugPrint('删除叶勇敢');
          }
        },
      ),
    ];
    notifyListeners();
  }
  // AI-generated END - 加载已保存的声音模拟数据

  // AI-generated START - 刷新数据
  void refresh() {
    _loadMockData();
    _loadSavedVoicesData();
  }
  // AI-generated END - 刷新数据
}
// AI-generated END - voice_recognition_provider.dart
