// AI-generated START - 日历弹窗组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_canlendar/providers/calendar_provider.dart';
import 'package:provider/provider.dart';

/// 日历弹窗组件
/// 显示一个可选择的日历，支持事件标记和日期选择
class CalendarPopup extends StatelessWidget {
  // AI-generated START - 构造函数
  const CalendarPopup({
    super.key,
    this.onDateSelected,
    this.onClose,
  });
  // AI-generated END - 构造函数

  /// 日期选择回调
  final ValueChanged<DateTime>? onDateSelected;

  /// 关闭回调
  final VoidCallback? onClose;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Consumer<CalendarProvider>(builder: (context, provider, child) {
      return Container(
          margin: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 16.0),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(16.0),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.1),
                blurRadius: 10.0,
                offset: const Offset(0, 4),
              ),
            ],
          ),
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              mainAxisSize: MainAxisSize.min,
              children: [
                // 头部：年月和关闭按钮
                _buildHeader(context, provider),
                const SizedBox(height: 24.0),
                // 分隔线
                Divider(
                  height: 1.0,
                  thickness: 1.0,
                  color: Colors.grey[300],
                ),
                const SizedBox(height: 12.0),
                // 星期标题行
                _buildWeekdayHeaders(),
                const SizedBox(height: 8.0),
                // 日期网格
                _buildCalendarGrid(context, provider),
                const SizedBox(height: 16.0),
                // 底部按钮：回到今天
                _buildGoToTodayButton(context, provider),
              ],
            ),
          ));
    });
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建头部
  /// 构建头部：显示年月和关闭按钮
  Widget _buildHeader(BuildContext context, CalendarProvider provider) {
    final month = provider.currentMonth;
    final monthText = '${month.year}年${month.month}月';

    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          monthText,
          style: const TextStyle(
            fontSize: 18.0,
            fontWeight: FontWeight.w600,
            color: Color(0xFF212121),
          ),
        ),
        Material(
          color: Colors.transparent,
          child: InkWell(
            onTap: () {
              if (onClose != null) {
                onClose!();
              } else {
                Navigator.of(context).pop();
              }
            },
            borderRadius: BorderRadius.circular(16.0),
            child: Container(
              width: 32.0,
              height: 32.0,
              decoration: BoxDecoration(
                color: Colors.grey[100],
                shape: BoxShape.circle,
              ),
              child: const Icon(
                Icons.close,
                size: 20.0,
                color: Color(0xFF666666),
              ),
            ),
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建头部

  // AI-generated START - 构建星期标题行
  /// 构建星期标题行
  Widget _buildWeekdayHeaders() {
    const weekdays = ['日', '一', '二', '三', '四', '五', '六'];

    return Row(
      children: weekdays.map((day) {
        return Expanded(
          child: Center(
            child: Text(
              day,
              style: TextStyle(
                fontSize: 14.0,
                fontWeight: FontWeight.w500,
                color: Colors.grey[700],
              ),
            ),
          ),
        );
      }).toList(),
    );
  }
  // AI-generated END - 构建星期标题行

  // AI-generated START - 构建日历网格
  /// 构建日历网格
  Widget _buildCalendarGrid(BuildContext context, CalendarProvider provider) {
    final month = provider.currentMonth;
    final today = DateTime.now();

    // 获取该月第一天是星期几（0=周日，1=周一...）
    final firstDay = DateTime(month.year, month.month, 1);
    final firstDayWeekday = firstDay.weekday % 7; // 转换为0=周日

    // 获取该月有多少天
    final daysInMonth = DateTime(month.year, month.month + 1, 0).day;

    // 计算需要显示的总天数（包括上个月的末尾几天）
    final totalCells = firstDayWeekday + daysInMonth;
    final rows = (totalCells / 7).ceil();

    return Column(
      mainAxisSize: MainAxisSize.min,
      children: List.generate(rows, (rowIndex) {
        return Row(
          mainAxisSize: MainAxisSize.min,
          children: List.generate(7, (colIndex) {
            final cellIndex = rowIndex * 7 + colIndex;
            final dateIndex = cellIndex - firstDayWeekday;

            // 如果是上个月的日期，显示为空
            if (dateIndex < 0 || dateIndex >= daysInMonth) {
              return const Expanded(child: SizedBox());
            }

            final date = DateTime(month.year, month.month, dateIndex + 1);
            final isSelected = provider.selectedDate != null &&
                provider.selectedDate!.year == date.year &&
                provider.selectedDate!.month == date.month &&
                provider.selectedDate!.day == date.day;
            final hasEvent = provider.hasEvent(date);
            final isToday = date.year == today.year && date.month == today.month && date.day == today.day;

            return Expanded(
              child: _buildDateCell(
                context,
                provider,
                date,
                isSelected,
                hasEvent,
                isToday,
              ),
            );
          }),
        );
      }),
    );
  }
  // AI-generated END - 构建日历网格

  // AI-generated START - 构建日期单元格
  /// 构建单个日期单元格
  Widget _buildDateCell(
    BuildContext context,
    CalendarProvider provider,
    DateTime date,
    bool isSelected,
    bool hasEvent,
    bool isToday,
  ) {
    return InkWell(
      onTap: () {
        provider.selectDate(date);
        if (onDateSelected != null) {
          onDateSelected!(date);
          Navigator.of(context).pop();
        }
      },
      borderRadius: BorderRadius.circular(8.0),
      child: Container(
        margin: const EdgeInsets.all(8.0),
        height: 40.0,
        decoration: BoxDecoration(
          color: isSelected
              ? const Color(0xFF2196F3) // 选中：蓝色背景
              : hasEvent
                  ? const Color(0xFFE3F2FD) // 有事件：浅蓝色背景
                  : Colors.transparent,
          borderRadius: BorderRadius.circular(8.0),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              '${date.day}',
              style: TextStyle(
                fontSize: 16.0,
                fontWeight: isSelected ? FontWeight.w600 : FontWeight.w400,
                color: isSelected ? Colors.white : const Color(0xFF212121),
              ),
            ),
            if (hasEvent && !isSelected)
              Container(
                margin: const EdgeInsets.only(top: 2.0),
                width: 4.0,
                height: 4.0,
                decoration: const BoxDecoration(
                  color: Color(0xFF2196F3),
                  shape: BoxShape.circle,
                ),
              ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建日期单元格

  // AI-generated START - 构建回到今天按钮
  /// 构建"回到今天"按钮
  Widget _buildGoToTodayButton(BuildContext context, CalendarProvider provider) {
    return SizedBox(
      width: double.infinity,
      child: ElevatedButton(
        onPressed: () {
          provider.goToToday();
          if (onDateSelected != null && provider.selectedDate != null) {
            onDateSelected!(provider.selectedDate!);
            Navigator.of(context).pop();
          }
        },
        style: ElevatedButton.styleFrom(
          backgroundColor: const Color(0xFF2196F3),
          foregroundColor: Colors.white,
          padding: const EdgeInsets.symmetric(vertical: 14.0),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8.0),
          ),
          elevation: 0,
        ),
        child: const Text(
          '回到今天',
          style: TextStyle(
            fontSize: 16.0,
            fontWeight: FontWeight.w500,
          ),
        ),
      ),
    );
  }
  // AI-generated END - 构建回到今天按钮
}
// AI-generated END - calendar_popup.dart
