// AI-generated START - 日历弹窗组件 - Generated by AI
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_canlendar/providers/calendar_provider.dart';
import 'package:provider/provider.dart';

/// 日历弹窗组件
/// 显示一个可选择的日历，支持事件标记和日期选择
class CalendarPopup extends StatefulWidget {
  // AI-generated START - 构造函数
  const CalendarPopup({
    super.key,
    this.onDateSelected,
    this.onClose,
  });
  // AI-generated END - 构造函数

  /// 日期选择回调
  final ValueChanged<DateTime>? onDateSelected;

  /// 关闭回调
  final VoidCallback? onClose;

  @override
  State<CalendarPopup> createState() => _CalendarPopupState();
}

class _CalendarPopupState extends State<CalendarPopup> {
  /// PageController 用于控制月份滑动
  late PageController _pageController;

  /// 当前显示的月份索引（相对于基准年份的偏移）
  int _currentPageIndex = 0;

  /// 基准年份（2000年1月），用于计算索引，确保索引始终为正数
  static final DateTime _baseMonth = DateTime(2000, 1, 1);

  /// 滑动停止定时器，用于延迟调用接口
  Timer? _scrollEndTimer;

  @override
  void initState() {
    super.initState();
    final provider = Provider.of<CalendarProvider>(context, listen: false);
    final currentMonth = provider.currentMonth;
    // 计算当前月份相对于基准月份的索引
    _currentPageIndex = _getIndexFromMonth(currentMonth);
    _pageController = PageController(initialPage: _currentPageIndex);
  }

  @override
  void dispose() {
    _scrollEndTimer?.cancel();
    _pageController.dispose();
    super.dispose();
  }

  /// 根据月份计算索引（相对于基准月份）
  int _getIndexFromMonth(DateTime month) {
    return (month.year - _baseMonth.year) * 12 + (month.month - _baseMonth.month);
  }

  /// 根据索引获取月份
  DateTime _getMonthByIndex(int index) {
    return DateTime(_baseMonth.year, _baseMonth.month + index, 1);
  }

  /// 处理页面切换
  void _onPageChanged(int index) {
    setState(() {
      _currentPageIndex = index;
    });
    final provider = Provider.of<CalendarProvider>(context, listen: false);
    final newMonth = _getMonthByIndex(index);
    provider.setCurrentMonth(newMonth);

    // 取消之前的定时器
    _scrollEndTimer?.cancel();
    // 设置新的定时器，滑动停止后调用接口
    _scrollEndTimer = Timer(const Duration(milliseconds: 300), () {
      if (mounted) {
        final currentMonth = _getMonthByIndex(_currentPageIndex);
        provider.loadMemoryDays(currentMonth);
      }
    });
  }

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Consumer<CalendarProvider>(builder: (context, provider, child) {
      // 同步当前月份显示（当外部改变月份时，如点击"回到今天"）
      final currentMonth = provider.currentMonth;
      final expectedIndex = _getIndexFromMonth(currentMonth);
      if (expectedIndex != _currentPageIndex && _pageController.hasClients) {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (_pageController.hasClients) {
            _pageController.jumpToPage(expectedIndex);
            _currentPageIndex = expectedIndex;
          }
        });
      }

      return Container(
          margin: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 16.0),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(16.0),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.1),
                blurRadius: 10.0,
                offset: const Offset(0, 4),
              ),
            ],
          ),
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              mainAxisSize: MainAxisSize.min,
              children: [
                // 头部：年月和关闭按钮
                _buildHeader(context, provider),
                const SizedBox(height: 24.0),
                // 分隔线
                Divider(
                  height: 1.0,
                  thickness: 1.0,
                  color: Colors.grey[300],
                ),
                const SizedBox(height: 12.0),
                // 星期标题行
                _buildWeekdayHeaders(),
                const SizedBox(height: 8.0),
                // 日期网格（支持滑动）
                _buildCalendarGrid(context, provider),
                const SizedBox(height: 16.0),
                // 底部按钮：回到今天
                _buildGoToTodayButton(context, provider),
              ],
            ),
          ));
    });
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建头部
  /// 构建头部：显示年月和关闭按钮
  Widget _buildHeader(BuildContext context, CalendarProvider provider) {
    final month = provider.currentMonth;
    final monthText = '${month.year}年${month.month}月';

    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          monthText,
          style: const TextStyle(
            fontSize: 18.0,
            fontWeight: FontWeight.w600,
            color: Color(0xFF212121),
          ),
        ),
        Material(
          color: Colors.transparent,
          child: InkWell(
            onTap: () {
              if (widget.onClose != null) {
                widget.onClose!();
              } else {
                Navigator.of(context).pop();
              }
            },
            borderRadius: BorderRadius.circular(16.0),
            child: Container(
              width: 32.0,
              height: 32.0,
              decoration: BoxDecoration(
                color: Colors.grey[100],
                shape: BoxShape.circle,
              ),
              child: const Icon(
                Icons.close,
                size: 20.0,
                color: Color(0xFF666666),
              ),
            ),
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建头部

  // AI-generated START - 构建星期标题行
  /// 构建星期标题行
  Widget _buildWeekdayHeaders() {
    const weekdays = ['日', '一', '二', '三', '四', '五', '六'];

    return Row(
      children: weekdays.map((day) {
        return Expanded(
          child: Center(
            child: Text(
              day,
              style: TextStyle(
                fontSize: 14.0,
                fontWeight: FontWeight.w500,
                color: Colors.grey[700],
              ),
            ),
          ),
        );
      }).toList(),
    );
  }
  // AI-generated END - 构建星期标题行

  // AI-generated START - 构建日历网格
  /// 构建日历网格（支持左右滑动切换月份）
  Widget _buildCalendarGrid(BuildContext context, CalendarProvider provider) {
    return SizedBox(
      height: 280.0, // 固定高度，确保滑动体验一致
      child: PageView.builder(
        controller: _pageController,
        onPageChanged: _onPageChanged,
        itemBuilder: (context, index) {
          final month = _getMonthByIndex(index);
          return _buildMonthGrid(context, provider, month);
        },
      ),
    );
  }

  /// 构建单个月份的日历网格
  Widget _buildMonthGrid(BuildContext context, CalendarProvider provider, DateTime month) {
    final today = DateTime.now();

    // 获取该月第一天是星期几（0=周日，1=周一...）
    final firstDay = DateTime(month.year, month.month, 1);
    final firstDayWeekday = firstDay.weekday % 7; // 转换为0=周日

    // 获取该月有多少天
    final daysInMonth = DateTime(month.year, month.month + 1, 0).day;

    // 计算需要显示的总天数（包括上个月的末尾几天）
    final totalCells = firstDayWeekday + daysInMonth;
    final rows = (totalCells / 7).ceil();

    return Column(
      mainAxisSize: MainAxisSize.min,
      children: List.generate(rows, (rowIndex) {
        return Row(
          mainAxisSize: MainAxisSize.min,
          children: List.generate(7, (colIndex) {
            final cellIndex = rowIndex * 7 + colIndex;
            final dateIndex = cellIndex - firstDayWeekday;

            // 如果是上个月的日期，显示为空
            if (dateIndex < 0 || dateIndex >= daysInMonth) {
              return const Expanded(child: SizedBox());
            }

            final date = DateTime(month.year, month.month, dateIndex + 1);
            final isSelected = provider.selectedDate != null &&
                provider.selectedDate!.year == date.year &&
                provider.selectedDate!.month == date.month &&
                provider.selectedDate!.day == date.day;
            final hasEvent = provider.hasEvent(date);
            final isToday = date.year == today.year && date.month == today.month && date.day == today.day;

            return Expanded(
              child: _buildDateCell(
                context,
                provider,
                date,
                isSelected,
                hasEvent,
                isToday,
              ),
            );
          }),
        );
      }),
    );
  }
  // AI-generated END - 构建日历网格

  // AI-generated START - 构建日期单元格
  /// 构建单个日期单元格
  Widget _buildDateCell(
    BuildContext context,
    CalendarProvider provider,
    DateTime date,
    bool isSelected,
    bool hasEvent,
    bool isToday,
  ) {
    return InkWell(
      onTap: () {
        provider.selectDate(date);
        if (widget.onDateSelected != null) {
          widget.onDateSelected!(date);
          Navigator.of(context).pop();
        }
      },
      borderRadius: BorderRadius.circular(8.0),
      child: Container(
        margin: const EdgeInsets.all(8.0),
        height: 40.0,
        decoration: BoxDecoration(
          color: isSelected
              ? const Color(0xFF2196F3) // 选中：蓝色背景
              : hasEvent
                  ? const Color(0xFFE3F2FD) // 有事件：浅蓝色背景
                  : Colors.transparent,
          borderRadius: BorderRadius.circular(8.0),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              '${date.day}',
              style: TextStyle(
                fontSize: 16.0,
                fontWeight: isSelected ? FontWeight.w600 : FontWeight.w400,
                color: isSelected ? Colors.white : const Color(0xFF212121),
              ),
            ),
            if (hasEvent && !isSelected)
              Container(
                margin: const EdgeInsets.only(top: 2.0),
                width: 4.0,
                height: 4.0,
                decoration: const BoxDecoration(
                  color: Color(0xFF2196F3),
                  shape: BoxShape.circle,
                ),
              ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建日期单元格

  // AI-generated START - 构建回到今天按钮
  /// 构建"回到今天"按钮
  Widget _buildGoToTodayButton(BuildContext context, CalendarProvider provider) {
    return SizedBox(
      width: double.infinity,
      child: ElevatedButton(
        onPressed: () {
          provider.goToToday();
          // 同步页面索引
          final today = DateTime.now();
          final newIndex = _getIndexFromMonth(DateTime(today.year, today.month, 1));
          if (_pageController.hasClients) {
            _pageController.jumpToPage(newIndex);
            _currentPageIndex = newIndex;
          }
          if (widget.onDateSelected != null && provider.selectedDate != null) {
            widget.onDateSelected!(provider.selectedDate!);
            Navigator.of(context).pop();
          }
        },
        style: ElevatedButton.styleFrom(
          backgroundColor: const Color(0xFF2196F3),
          foregroundColor: Colors.white,
          padding: const EdgeInsets.symmetric(vertical: 14.0),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8.0),
          ),
          elevation: 0,
        ),
        child: const Text(
          '回到今天',
          style: TextStyle(
            fontSize: 16.0,
            fontWeight: FontWeight.w500,
          ),
        ),
      ),
    );
  }
  // AI-generated END - 构建回到今天按钮
}
// AI-generated END - calendar_popup.dart
