// AI-generated START - 应用集成页面 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_apps_integration/providers/apps_integration_provider.dart';
import 'package:omi/pages/mp_apps_integration/widgets/automation_workflow_card.dart';
import 'package:omi/pages/mp_apps_integration/widgets/category_tabs_card.dart';
import 'package:omi/pages/mp_apps_integration/widgets/help_guide_card.dart';
import 'package:omi/pages/mp_newsetting/home/widgets/mp_common_app_bar.dart';
import 'package:provider/provider.dart';

/// 应用集成页面
/// 显示应用集成列表和相关功能
class AppsIntegrationPage extends StatefulWidget {
  // AI-generated START - 构造函数
  const AppsIntegrationPage({
    super.key,
    this.title = '应用集成',
  });
  // AI-generated END - 构造函数

  /// 页面标题
  final String title;
  // AI-generated START - 创建状态
  @override
  State<AppsIntegrationPage> createState() => _AppsIntegrationPageState();
  // AI-generated END - 创建状态
}

class _AppsIntegrationPageState extends State<AppsIntegrationPage> {
  // AI-generated START - 当前选中的分类索引
  int _selectedCategoryIndex = 0;
  // AI-generated END - 当前选中的分类索引

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: MPCommonAppBar(
        title: widget.title,
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // 自动化工作流卡片
            const AutomationWorkflowCard(),
            const SizedBox(height: 8.0),
            // 分类标签栏
            _buildCategoryTabs(),
            const SizedBox(height: 8.0),
            // 应用集成列表
            _buildIntegrationList(context),
            const SizedBox(height: 8.0),
            // 帮助指南卡片
            const HelpGuideCard(),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建分类标签栏
  Widget _buildCategoryTabs() {
    return CategoryTabsCard(
      categories: const [
        CategoryTab(
          label: '全部',
          icon: Icons.apps,
        ),
        CategoryTab(
          label: '效率工具',
          icon: Icons.notifications_outlined,
        ),
        CategoryTab(
          label: '沟通协作',
          icon: Icons.chat_bubble_outline,
        ),
      ],
      selectedIndex: _selectedCategoryIndex,
      onCategoryChanged: (index) {
        setState(() {
          _selectedCategoryIndex = index;
        });
      },
    );
  }
  // AI-generated END - 构建分类标签栏

  // AI-generated START - 构建应用集成列表
  Widget _buildIntegrationList(BuildContext context) {
    // 使用 Consumer 获取应用集成列表
    return Consumer<AppsIntegrationProvider>(
      builder: (context, provider, child) {
        final integrations = provider.integrations;

        if (integrations.isEmpty) {
          return const SizedBox.shrink();
        }

        // 显示所有应用集成卡片
        return Column(
          children: integrations.map((integration) {
            return integration.toCard();
          }).toList(),
        );
      },
    );
  }
  // AI-generated END - 构建应用集成列表
}
// AI-generated END - apps_integration_page.dart
