// AI-generated START - 声纹识别页面 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_add_voive_recognition/mp_add_voice_recognition_page.dart';
import 'package:omi/pages/mp_add_voive_recognition/providers/mp_add_voice_recognition_provider.dart';
import 'package:omi/pages/mp_custom_utils/mp_const_utils.dart';
import 'package:omi/pages/mp_newsetting/home/widgets/mp_common_app_bar.dart';
import 'package:omi/pages/mp_newsetting/voice_recognition/providers/voice_recognition_provider.dart';
import 'package:omi/pages/mp_newsetting/voice_recognition/widgets/my_voice_card.dart';
import 'package:omi/pages/mp_newsetting/voice_recognition/widgets/record_voiceprint_card.dart';
import 'package:omi/pages/mp_newsetting/voice_recognition/widgets/saved_voices_card.dart';
import 'package:omi/pages/mp_newsetting/voice_recognition/widgets/voiceprint_info_card.dart';
import 'package:omi/pages/mp_voice_congnition_detail/mp_voice_recognition_detail_page.dart';
import 'package:provider/provider.dart';

/// 声纹识别页面
/// 显示声纹识别相关的信息和功能
class VoiceRecognitionPage extends StatelessWidget {
  // AI-generated START - 构造函数
  const VoiceRecognitionPage({
    super.key,
    this.title = '声纹识别',
  });
  // AI-generated END - 构造函数

  /// 页面标题
  final String title;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: MPConstUtils.backgroundColorGrey,
      appBar: MPCommonAppBar(
        title: title,
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const VoiceprintInfoCard(),
            // 我的声音部分
            _buildMyVoiceSection(context),
            const SizedBox(height: 8.0),
            // 已保存的声音部分
            _buildSavedVoicesSection(context),
            const SizedBox(height: 8.0),
            // 录制声纹卡片
            RecordVoiceprintCard(
              onRecordTap: () {
                Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (context) => ChangeNotifierProvider<MPAddVoiceRecognitionProvider>(
                      create: (_) => MPAddVoiceRecognitionProvider(),
                      child: const MPAddVoiceRecognitionPage(),
                    ),
                  ),
                );
              }, // 可以在这里添加录制逻辑
            ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建我的声音部分
  Widget _buildMyVoiceSection(BuildContext context) {
    // 使用 Provider 获取声音列表
    final voiceProvider = Provider.of<VoiceRecognitionProvider>(context);
    final voiceList = voiceProvider.voiceList;

    final displayItems = voiceList.toList();

    // 我的声音卡片（支持多个item，标题在卡片内部）
    return MyVoiceCard(
      items: displayItems,
      onTap: (item) {
        Navigator.of(context).push(
          MaterialPageRoute(
            builder: (context) => MPVoiceRecognitionDetailPage(
              voiceId: item.id,
              initialName: item.title,
              isMyselfVoice: true,
            ),
          ),
        );
      },
      onActionTap: (item) {
        Navigator.of(context).push(
          MaterialPageRoute(
            builder: (context) => MPVoiceRecognitionDetailPage(
              voiceId: item.id,
              initialName: item.title,
              isMyselfVoice: true,
            ),
          ),
        );
      },
      onEmptyStateTap: () {
        Navigator.of(context).push(
          MaterialPageRoute(
            builder: (context) => const MPAddVoiceRecognitionPage(
              isMyselfVoice: true,
            ),
          ),
        );
      },
    );
  }
  // AI-generated END - 构建我的声音部分

  // AI-generated START - 构建已保存的声音部分
  Widget _buildSavedVoicesSection(BuildContext context) {
    // 使用 Provider 获取已保存的声音列表
    final voiceProvider = Provider.of<VoiceRecognitionProvider>(context);
    final savedVoicesList = voiceProvider.savedVoicesList;

    // 如果没有数据，不显示
    if (savedVoicesList.isEmpty) {
      return const SizedBox.shrink();
    }

    // 已保存的声音卡片（支持多个item，默认使用删除操作）
    return SavedVoicesCard(
      items: savedVoicesList,
      onTap: (item) {
        Navigator.of(context).push(
          MaterialPageRoute(
            builder: (context) => MPVoiceRecognitionDetailPage(
                voiceId: item.id, isEditMode: true, initialName: item.title, isMyselfVoice: false),
          ),
        );
      },
      onActionTap: (item) {
        Navigator.of(context).push(
          MaterialPageRoute(
            builder: (context) => MPVoiceRecognitionDetailPage(
                voiceId: item.id, isEditMode: true, initialName: item.title, isMyselfVoice: false),
          ),
        );
      },
    );
  }
  // AI-generated END - 构建已保存的声音部分
}
// AI-generated END - voice_recognition_page.dart
