// AI-generated START - 添加专家状态管理Provider - Generated by AI
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:omi/backend/http/mp_api/mp_expert.dart';
import 'package:omi/backend/schema/mp/mp_expert.dart';

/// 专家技能类型枚举
enum MPExpertSkillType {
  chat, // 对话交流
  feedback, // 专业反馈
}

/// 添加专家状态管理Provider
/// 管理创建/添加专家的表单数据和提交逻辑
class MPAddExportProvider with ChangeNotifier {
  // AI-generated START - 专家名称
  String _name = '';
  // AI-generated END - _name

  // AI-generated START - 专家头像URL
  String _avatar = '';
  // AI-generated END - _avatar

  // AI-generated START - 专家头像文件
  File? _avatarFile;
  // AI-generated END - _avatarFile

  // AI-generated START - 专家简介
  String _about = '';
  // AI-generated END - _about

  // AI-generated START - 专家能力列表
  List<String> _capabilities = [];
  // AI-generated END - _capabilities

  // AI-generated START - 专家提示词
  String _prompt = '';
  // AI-generated END - _prompt

  // AI-generated START - 聊天 Prompt
  String _chatPrompt = '';
  // AI-generated END - _chatPrompt

  // AI-generated START - 反馈 Prompt
  String _feedbackPrompt = '';
  // AI-generated END - _feedbackPrompt

  // AI-generated START - 聊天个性
  String _chatPersonality = '';
  // AI-generated END - _chatPersonality

  // AI-generated START - 选中的技能类型集合（支持多选）
  Set<MPExpertSkillType> _selectedSkills = {};
  // AI-generated END - _selectedSkills

  // AI-generated START - 专家类别
  String _type = '';
  // AI-generated END - _category

  // AI-generated START - 提供反馈时间
  TimeOfDay? _feedbackTime;
  // AI-generated END - _feedbackTime

  // AI-generated START - 自动发送
  bool _autoSend = false;
  // AI-generated END - _autoSend

  // AI-generated START - 是否正在提交
  bool _isSubmitting = false;
  // AI-generated END - _isSubmitting

  // AI-generated START - 错误信息
  String? _error;
  // AI-generated END - _error

  // AI-generated START - 获取专家名称
  String get name => _name;
  // AI-generated END - name

  // AI-generated START - 获取专家头像URL
  String get avatar => _avatar;
  // AI-generated END - avatar

  // AI-generated START - 获取专家头像文件
  File? get avatarFile => _avatarFile;
  // AI-generated END - avatarFile

  // AI-generated START - 获取专家简介
  String get about => _about;
  // AI-generated END - about

  // AI-generated START - 获取专家能力列表
  List<String> get capabilities => _capabilities;
  // AI-generated END - capabilities

  // AI-generated START - 获取专家提示词
  String get prompt => _prompt;
  // AI-generated END - prompt

  // AI-generated START - 获取聊天 Prompt
  String get chatPrompt => _chatPrompt;
  // AI-generated END - chatPrompt

  // AI-generated START - 获取反馈 Prompt
  String get feedbackPrompt => _feedbackPrompt;
  // AI-generated END - feedbackPrompt

  // AI-generated START - 获取聊天个性
  String get chatPersonality => _chatPersonality;
  // AI-generated END - chatPersonality

  // AI-generated START - 获取选中的技能类型集合
  Set<MPExpertSkillType> get selectedSkills => _selectedSkills;
  // AI-generated END - selectedSkills

  // AI-generated START - 获取选中的技能类型（兼容旧代码，返回第一个选中的技能）
  MPExpertSkillType? get selectedSkill => _selectedSkills.isEmpty ? null : _selectedSkills.first;
  // AI-generated END - selectedSkill

  // AI-generated START - 检查技能是否被选中
  bool isSkillSelected(MPExpertSkillType skill) => _selectedSkills.contains(skill);
  // AI-generated END - isSkillSelected

  // AI-generated START - 获取专家类别
  String get type => _type;
  // AI-generated END - category

  // AI-generated START - 获取提供反馈时间
  TimeOfDay? get feedbackTime => _feedbackTime;
  // AI-generated END - feedbackTime

  // AI-generated START - 获取自动发送
  bool get autoSend => _autoSend;
  // AI-generated END - autoSend

  // AI-generated START - 获取是否正在提交
  bool get isSubmitting => _isSubmitting;
  // AI-generated END - isSubmitting

  // AI-generated START - 获取错误信息
  String? get error => _error;
  // AI-generated END - error

  // AI-generated START - 更新专家名称
  void updateName(String name) {
    _name = name;
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updateName

  // AI-generated START - 更新专家头像URL
  void updateAvatar(String avatar) {
    _avatar = avatar;
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updateAvatar

  // AI-generated START - 更新专家头像文件
  void updateAvatarFile(File? file) {
    _avatarFile = file;
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updateAvatarFile

  // AI-generated START - 更新专家简介
  void updateAbout(String about) {
    _about = about;
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updateAbout

  // AI-generated START - 更新专家能力列表
  void updateCapabilities(List<String> capabilities) {
    _capabilities = capabilities;
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updateCapabilities

  // AI-generated START - 添加能力
  void addCapability(String capability) {
    if (capability.isNotEmpty && !_capabilities.contains(capability)) {
      _capabilities.add(capability);
      _error = null;
      notifyListeners();
    }
  }
  // AI-generated END - addCapability

  // AI-generated START - 移除能力
  void removeCapability(String capability) {
    _capabilities.remove(capability);
    _error = null;
    notifyListeners();
  }
  // AI-generated END - removeCapability

  // AI-generated START - 更新专家提示词
  void updatePrompt(String prompt) {
    _prompt = prompt;
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updatePrompt

  // AI-generated START - 更新聊天 Prompt
  void updateChatPrompt(String chatPrompt) {
    _chatPrompt = chatPrompt;
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updateChatPrompt

  // AI-generated START - 更新反馈 Prompt
  void updateFeedbackPrompt(String feedbackPrompt) {
    _feedbackPrompt = feedbackPrompt;
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updateFeedbackPrompt

  // AI-generated START - 更新聊天个性
  void updateChatPersonality(String chatPersonality) {
    _chatPersonality = chatPersonality;
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updateChatPersonality

  // AI-generated START - 切换技能选中状态（支持多选和反选）
  void toggleSkill(MPExpertSkillType skill) {
    if (_selectedSkills.contains(skill)) {
      _selectedSkills.remove(skill);
    } else {
      _selectedSkills.add(skill);
    }
    _error = null;
    notifyListeners();
  }
  // AI-generated END - toggleSkill

  // AI-generated START - 更新选中的技能类型（兼容旧代码，设置为单个技能）
  void updateSelectedSkill(MPExpertSkillType? skill) {
    if (skill == null) {
      _selectedSkills.clear();
    } else {
      _selectedSkills = {skill};
    }
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updateSelectedSkill

  // AI-generated START - 更新专家类别
  void updateCategory(String category) {
    _type = category;
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updateCategory

  // AI-generated START - 更新提供反馈时间
  void updateFeedbackTime(TimeOfDay? time) {
    _feedbackTime = time;
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updateFeedbackTime

  // AI-generated START - 更新自动发送
  void updateAutoSend(bool autoSend) {
    _autoSend = autoSend;
    _error = null;
    notifyListeners();
  }
  // AI-generated END - updateAutoSend

  // AI-generated START - 验证表单
  bool validateForm() {
    if (_name.isEmpty) {
      _error = '请输入专家名称';
      notifyListeners();
      return false;
    }
    if (_about.isEmpty) {
      _error = '请输入专家简介';
      notifyListeners();
      return false;
    }
    if (_selectedSkills.isEmpty) {
      _error = '请至少选择一项专家技能';
      notifyListeners();
      return false;
    }
    if (_selectedSkills.contains(MPExpertSkillType.chat) && _chatPrompt.isEmpty) {
      _error = '请输入专家沟通技能描述';
      notifyListeners();
      return false;
    }
    if (_selectedSkills.contains(MPExpertSkillType.feedback) && _feedbackPrompt.isEmpty) {
      _error = '请输入专家反馈技能描述';
      notifyListeners();
      return false;
    }
    _error = null;
    notifyListeners();
    return true;
  }
  // AI-generated END - validateForm

  // AI-generated START - 将技能类型转换为字符串列表
  List<String> _skillsToStringList() {
    return _selectedSkills.map((skill) {
      switch (skill) {
        case MPExpertSkillType.chat:
          return 'chat';
        case MPExpertSkillType.feedback:
          return 'feedback';
      }
    }).toList();
  }
  // AI-generated END - _skillsToStringList

  // AI-generated START - 格式化反馈时间
  String? _formatFeedbackTime() {
    if (_feedbackTime == null) return null;
    return '${_feedbackTime!.hour.toString().padLeft(2, '0')}:${_feedbackTime!.minute.toString().padLeft(2, '0')}';
  }
  // AI-generated END - _formatFeedbackTime

  // AI-generated START - 提交表单
  Future<bool> submitForm() async {
    if (!validateForm()) {
      return false;
    }

    _isSubmitting = true;
    _error = null;
    notifyListeners();

    try {
      // 构建创建专家请求
      final request = MPCreateExpertRequest(
        name: _name,
        avatar: _avatar,
        about: _about,
        capabilities: _skillsToStringList(),
        type: _type.isNotEmpty ? _type : 'business', // 默认类别
        chatPrompt: _selectedSkills.contains(MPExpertSkillType.chat) ? _chatPrompt : null,
        feedbackPrompt: _selectedSkills.contains(MPExpertSkillType.feedback) ? _feedbackPrompt : null,
        feedbackCronAt: _selectedSkills.contains(MPExpertSkillType.feedback) ? _formatFeedbackTime() : null,
        autoSend: _selectedSkills.contains(MPExpertSkillType.feedback) ? _autoSend : null,
      );

      // 调用创建专家的 API
      final response = await createExpert(
        request,
        avatarFile: _avatarFile,
      );

      if (response == null) {
        _error = '创建失败，请稍后重试';
        _isSubmitting = false;
        notifyListeners();
        return false;
      }

      // 检查响应状态
      if (response.baseResp.code != 0) {
        _error = response.baseResp.message.isNotEmpty ? response.baseResp.message : '创建失败，请稍后重试';
        _isSubmitting = false;
        notifyListeners();
        return false;
      }

      _isSubmitting = false;
      notifyListeners();
      return true;
    } catch (e) {
      _error = '提交失败: $e';
      _isSubmitting = false;
      notifyListeners();
      return false;
    }
  }
  // AI-generated END - submitForm

  // AI-generated START - 重置表单
  void resetForm() {
    _name = '';
    _avatar = '';
    _avatarFile = null;
    _about = '';
    _capabilities = [];
    _prompt = '';
    _chatPrompt = '';
    _feedbackPrompt = '';
    _chatPersonality = '';
    _selectedSkills.clear();
    _type = '';
    _feedbackTime = null;
    _autoSend = false;
    _error = null;
    _isSubmitting = false;
    notifyListeners();
  }
  // AI-generated END - resetForm
}
// AI-generated END - mp_add_export_provider.dart
