// AI-generated START - 模板详情状态管理Provider - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/backend/http/mp_api/mp_template.dart' as mp_template_api;
import 'package:omi/backend/schema/mp/mp_data_model.dart';
import 'package:omi/backend/schema/mp/mp_template.dart';
import 'package:omi/pages/mp_custom_utils/mp_toast_utils.dart';

/// 模板详情状态管理Provider
/// 管理模板详情数据和操作
class MPTemplateDetailProvider with ChangeNotifier {
  // AI-generated START - 状态变量
  MPTemplateStruct? _template;

  bool _isLoading = false;
  String _category = '通用';
  // AI-generated END - 状态变量

  // AI-generated START - Getters
  MPTemplateStruct? get template => _template;
  bool get isLoading => _isLoading;
  String get category => _category;

  /// 是否为新增模式（templateId 为 null 或 'new'）
  bool get isCreateMode => _templateId == null;

  /// 是否为编辑模式
  bool get isEditMode => !isCreateMode;
  // AI-generated END - Getters

  // AI-generated START - 模板ID
  String? _templateId;
  // AI-generated END - 模板ID

  // AI-generated START - 初始化模板
  /// 根据 templateId 初始化模板（新增或编辑）
  Future<void> initializeTemplate(String? templateId, MPTemplateStruct? template) async {
    _templateId = templateId;

    if (template != null) {
      // 如果提供了模板数据，直接使用
      setState(() {
        _template = template;
        _category = template.type ?? '通用';
        _isLoading = false;
      });
    } else if (isCreateMode) {
      // 新增模式：创建新模板
      setState(() {
        _template = MPTemplateStruct(
          id: null,
          title: null,
          icon: null,
          type: null,
          prompt: null,
        );
        _category = '通用';
        _isLoading = false;
      });
    } else if (_templateId != null) {
      // 编辑模式：从 API 加载模板详情
      await loadTemplateDetail(_templateId!);
    }
  }
  // AI-generated END - 初始化模板

  // AI-generated START - 加载模板详情
  /// 从 API 加载模板详情
  Future<void> loadTemplateDetail(String templateId) async {
    setState(() {
      _isLoading = true;
    });

    try {
      // 模拟网络延迟
      await Future.delayed(const Duration(milliseconds: 500));

      // 使用模拟数据
      final mockResponse = _createMockTemplateDetailResponse(templateId);

      if (mockResponse != null && mockResponse.baseResp.code == 0) {
        setState(() {
          _template = mockResponse.template;
          _isLoading = false;
        });
      } else {
        setState(() {
          MPToastUtils.showMessage(mockResponse?.baseResp.message ?? '加载模板详情失败');
          _isLoading = false;
        });
      }

      // 实际 API 调用（注释掉，使用模拟数据）
      // final request = MPGetTemplateDetailRequest(templateId: templateId);
      // final response = await mp_template_api.getTemplateDetail(request);
      // if (response != null) {
      //   if (response.baseResp.code == 0) {
      //     setState(() {
      //       _template = response.template;
      //       _isLoading = false;
      //     });
      //   } else {
      //     setState(() {
      //       _error = response.baseResp.message;
      //       _isLoading = false;
      //     });
      //   }
      // } else {
      //   setState(() {
      //     _error = '加载模板详情失败';
      //     _isLoading = false;
      //   });
      // }
    } catch (e) {
      setState(() {
        MPToastUtils.showMessage(e.toString());
        _isLoading = false;
      });
    }
  }
  // AI-generated END - 加载模板详情

  // AI-generated START - 更新模板标题
  /// 更新模板标题
  void updateTitle(String title) {
    setState(() {
      _template = MPTemplateStruct(
        id: _template?.id,
        title: title,
        icon: _template?.icon,
        type: _template?.type ?? _category,
        prompt: _template?.prompt,
      );
    });
  }
  // AI-generated END - 更新模板标题

  // AI-generated START - 更新模板类别
  /// 更新模板类别
  void updateCategory(String category) {
    setState(() {
      _category = category;
    });
  }
  // AI-generated END - 更新模板类别

  // AI-generated START - 更新模板内容
  /// 更新模板内容（Prompt）
  void updateContent(String content) {
    setState(() {
      _template = MPTemplateStruct(
        id: _template?.id,
        title: _template?.title,
        icon: _template?.icon,
        type: _template?.type ?? _category,
        prompt: content,
      );
    });
  }
  // AI-generated END - 更新模板内容

  // AI-generated START - 保存模板
  /// 保存模板
  Future<bool> saveTemplate() async {
    if (_template == null) {
      MPToastUtils.showMessage('模板数据为空');
      notifyListeners();
      return false;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      if (isCreateMode) {
        // 创建新模板
        final title = _template!.title ?? '';
        final prompt = _template!.prompt ?? '';

        if (title.isEmpty) {
          setState(() {
            _isLoading = false;
          });
          MPToastUtils.showMessage('请输入模板名称');
          return false;
        }

        if (prompt.isEmpty) {
          setState(() {
            _isLoading = false;
          });
          MPToastUtils.showMessage('请输入Prompt内容');
          return false;
        }

        final request = MPCreateTemplateRequest(
          title: title,
          icon: _template!.icon ?? '',
          prompt: prompt,
          type: _category,
        );
        final response = await mp_template_api.createTemplate(request);

        if (response != null && response.baseResp.code == 0) {
          setState(() {
            _isLoading = false;
          });
          MPToastUtils.showMessage('创建模板成功');
          return true;
        } else {
          setState(() {
            _isLoading = false;
          });
          MPToastUtils.showMessage(response?.baseResp.message ?? '创建模板失败');
          return false;
        }
      } else {
        // TODO: 更新现有模板的 API 调用
        // 目前先返回成功（模拟）
        setState(() {
          _isLoading = false;
        });
        MPToastUtils.showMessage('更新模板成功');
        return true;
      }
    } catch (e) {
      setState(() {
        MPToastUtils.showMessage(e.toString());
        _isLoading = false;
      });
      return false;
    }
  }
  // AI-generated END - 保存模板

  // AI-generated START - 设置为默认模板
  /// 设置为默认模板
  Future<bool> setAsDefaultTemplate() async {
    if (_template == null) {
      MPToastUtils.showMessage('模板数据为空');

      notifyListeners();
      return false;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      // 调用 API 设置默认模板
      final request = MPSetTemplateDefaultRequest(
        templateId: _template!.id ?? '',
      );
      final response = await mp_template_api.setTemplateDefault(request);

      if (response != null && response.baseResp.code == 0) {
        setState(() {
          _isLoading = false;
        });
        debugPrint('设置为默认模板成功: ${_template!.title}');
        return true;
      } else {
        setState(() {
          MPToastUtils.showMessage(response?.baseResp.message ?? '设置默认模板失败');
          _isLoading = false;
        });
        return false;
      }
    } catch (e) {
      setState(() {
        MPToastUtils.showMessage(e.toString());
        _isLoading = false;
      });
      return false;
    }
  }
  // AI-generated END - 设置为默认模板

  // AI-generated START - 创建模拟模板详情响应
  /// 创建模拟的模板详情响应数据
  MPGetTemplateDetailResponse? _createMockTemplateDetailResponse(String templateId) {
    // 根据 templateId 返回不同的模拟数据

    // 默认模板
    MPTemplateStruct mockTemplate = MPTemplateStruct(
      id: templateId,
      title: '通用会议记录模板',
      type: '通用',
      prompt:
          '**Meeting Summary**\n\n**Date:** [Date]\n**Attendees:** [List of attendees]\n**Duration:** [Duration]\n\n**Agenda Items:**\n1. [Item 1]\n2. [Item 2]\n3. [Item 3]\n\n**Key Discussion Points:**\n- [Point 1]\n- [Point 2]\n- [Point 3]\n\n**Decisions Made:**\n- [Decision 1]\n- [Decision 2]\n\n**Action Items:**\n- [ ] [Action 1] - Owner: [Name] - Due: [Date]\n- [ ] [Action 2] - Owner: [Name] - Due: [Date]\n\n**Next Steps:**\n- [Next step 1]\n- [Next step 2]\n\n**Notes:**\n[Additional notes or observations]',
    );
    final baseResp = MPBaseResp(
      code: 0,
      message: 'success',
      logid: 'mock_logid_${DateTime.now().millisecondsSinceEpoch}',
    );

    return MPGetTemplateDetailResponse(
      template: mockTemplate,
      baseResp: baseResp,
    );
  }
  // AI-generated END - 创建模拟模板详情响应

  // AI-generated START - 设置状态
  /// 设置状态并通知监听者
  void setState(VoidCallback fn) {
    fn();
    notifyListeners();
  }
  // AI-generated END - 设置状态

  // AI-generated START - 重置状态
  /// 重置所有状态
  void reset() {
    _template = null;
    _isLoading = false;
    _category = '通用';
    notifyListeners();
  }
  // AI-generated END - 重置状态
}
// AI-generated END - template_detail_provider.dart
