// AI-generated START - 模版选择状态管理Provider - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_template%20_selection/models/template_data.dart';
import 'package:omi/pages/mp_template%20_selection/widgets/template_card.dart';

/// 模版选择状态管理Provider
/// 管理模版列表数据和选中状态
class TemplateSelectionProvider with ChangeNotifier {
  // AI-generated START - 模版列表
  List<TemplateData> _templates = [];
  // AI-generated END - 模版列表

  // AI-generated START - 当前选中的模版索引
  int? _selectedIndex;
  // AI-generated END - 当前选中的模版索引

  // AI-generated START - 获取模版列表
  List<TemplateData> get templates => _templates;
  // AI-generated END - 获取模版列表

  // AI-generated START - 获取当前选中的模版索引
  int? get selectedIndex => _selectedIndex;
  // AI-generated END - 获取当前选中的模版索引

  // AI-generated START - 获取当前选中的模版
  TemplateData? get selectedTemplate =>
      _selectedIndex != null && _selectedIndex! < _templates.length
          ? _templates[_selectedIndex!]
          : null;
  // AI-generated END - 获取当前选中的模版

  // AI-generated START - 构造函数
  TemplateSelectionProvider() {
    _loadMockData();
  }
  // AI-generated END - 构造函数

  // AI-generated START - 加载模拟数据
  void _loadMockData() {
    _templates = [
      TemplateData(
        title: '会议纪要模版',
        description: '自动提取会议要点、决策事项和行动计划,生成结构化会议纪要',
        icon: Icons.people,
        iconColor: const Color(0xFF64B5F6), // 浅蓝色
        isSelected: true,
        isHot: true,
        features: [
          const TemplateFeature(label: '会议主题'),
          const TemplateFeature(label: '讨论要点'),
          const TemplateFeature(label: '行动计划'),
          const TemplateFeature(label: '参与人员'),
          const TemplateFeature(label: '决策事项'),
          const TemplateFeature(label: '下次会议安排'),
        ],
        onPreview: () {
          debugPrint('预览会议纪要模版');
        },
        onSelect: () {
          selectTemplate(0);
        },
      ),
      TemplateData(
        title: '项目总结模版',
        description: '梳理项目进展、风险点和里程碑,形成完整的项目状态报告',
        icon: Icons.assessment,
        iconColor: const Color(0xFF81C784), // 绿色
        isSelected: false,
        isHot: false,
        features: [
          const TemplateFeature(label: '项目概述'),
          const TemplateFeature(label: '风险识别'),
          const TemplateFeature(label: '资源需求'),
          const TemplateFeature(label: '进展情况'),
          const TemplateFeature(label: '里程碑'),
          const TemplateFeature(label: '下步计划'),
        ],
        onPreview: () {
          debugPrint('预览项目总结模版');
        },
        onSelect: () {
          selectTemplate(1);
        },
      ),
      TemplateData(
        title: '学习笔记模版',
        description: '整理学习内容的核心知识点,构建知识体系和思维导图',
        icon: Icons.menu_book,
        iconColor: const Color(0xFFBA68C8), // 紫色
        isSelected: false,
        isHot: false,
        features: [
          const TemplateFeature(label: '核心概念'),
          const TemplateFeature(label: '案例分析'),
          const TemplateFeature(label: '练习题目'),
          const TemplateFeature(label: '知识要点'),
          const TemplateFeature(label: '思维导图'),
          const TemplateFeature(label: '延伸阅读'),
        ],
        onPreview: () {
          debugPrint('预览学习笔记模版');
        },
        onSelect: () {
          selectTemplate(2);
        },
      ),
      TemplateData(
        title: '面试记录模版',
        description: '记录面试过程中的关键信息,辅助招聘决策',
        icon: Icons.person_outline,
        iconColor: const Color(0xFF9575CD), // 浅紫色
        isSelected: false,
        isHot: false,
        features: [
          const TemplateFeature(label: '候选人信息'),
          const TemplateFeature(label: '面试表现'),
          const TemplateFeature(label: '改进建议'),
          const TemplateFeature(label: '技能评估'),
          const TemplateFeature(label: '优势分析'),
          const TemplateFeature(label: '录用建议'),
        ],
        onPreview: () {
          debugPrint('预览面试记录模版');
        },
        onSelect: () {
          selectTemplate(3);
        },
      ),
    ];
    _selectedIndex = 0; // 默认选中第一个
    notifyListeners();
  }
  // AI-generated END - 加载模拟数据

  // AI-generated START - 选择模版
  void selectTemplate(int index) {
    if (index >= 0 && index < _templates.length) {
      // 取消之前选中的模版
      if (_selectedIndex != null && _selectedIndex! < _templates.length) {
        _templates[_selectedIndex!] = TemplateData(
          title: _templates[_selectedIndex!].title,
          description: _templates[_selectedIndex!].description,
          icon: _templates[_selectedIndex!].icon,
          iconColor: _templates[_selectedIndex!].iconColor,
          isSelected: false,
          isHot: _templates[_selectedIndex!].isHot,
          features: _templates[_selectedIndex!].features,
          onPreview: _templates[_selectedIndex!].onPreview,
          onSelect: _templates[_selectedIndex!].onSelect,
        );
      }
      // 选中新的模版
      _selectedIndex = index;
      _templates[index] = TemplateData(
        title: _templates[index].title,
        description: _templates[index].description,
        icon: _templates[index].icon,
        iconColor: _templates[index].iconColor,
        isSelected: true,
        isHot: _templates[index].isHot,
        features: _templates[index].features,
        onPreview: _templates[index].onPreview,
        onSelect: _templates[index].onSelect,
      );
      notifyListeners();
    }
  }
  // AI-generated END - 选择模版

  // AI-generated START - 添加模版
  void addTemplate(TemplateData template) {
    _templates.add(template);
    notifyListeners();
  }
  // AI-generated END - 添加模版

  // AI-generated START - 删除模版
  void removeTemplate(int index) {
    if (index >= 0 && index < _templates.length) {
      _templates.removeAt(index);
      if (_selectedIndex == index) {
        _selectedIndex = null;
      } else if (_selectedIndex != null && _selectedIndex! > index) {
        _selectedIndex = _selectedIndex! - 1;
      }
      notifyListeners();
    }
  }
  // AI-generated END - 删除模版

  // AI-generated START - 刷新数据
  void refresh() {
    _loadMockData();
  }
  // AI-generated END - 刷新数据
}
// AI-generated END - template_selection_provider.dart

