// AI-generated START - 模版选择状态管理Provider - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/backend/http/mp_api/mp_template.dart' as mp_template_api;
import 'package:omi/backend/schema/mp/mp_data_model.dart';
import 'package:omi/backend/schema/mp/mp_template.dart';
import 'package:omi/pages/mp_template%20_selection/widgets/horizontal_scroll_template_card.dart';

/// 模版选择状态管理Provider
/// 管理模版列表数据和选中状态
class TemplateSelectionProvider with ChangeNotifier {
  // AI-generated START - 模版列表
  List<CardItem> _templates = [];
  // AI-generated END - 模版列表

  // AI-generated START - 当前选中的模版索引
  int? _selectedIndex;
  // AI-generated END - 当前选中的模版索引

  // AI-generated START - 是否正在加载
  bool _isLoading = false;
  // AI-generated END - _isLoading

  // AI-generated START - 错误信息
  String? _error;
  // AI-generated END - _error

  // AI-generated START - 是否还有更多数据
  bool _hasMore = true;
  // AI-generated END - _hasMore

  // AI-generated START - 分页游标
  String _cursor = '';
  // AI-generated END - _cursor

  // AI-generated START - 获取模版列表
  List<CardItem> get templates => _templates;
  // AI-generated END - 获取模版列表

  // AI-generated START - 获取当前选中的模版索引
  int? get selectedIndex => _selectedIndex;
  // AI-generated END - 获取当前选中的模版索引

  // AI-generated START - 获取是否正在加载
  bool get isLoading => _isLoading;
  // AI-generated END - isLoading

  // AI-generated START - 获取错误信息
  String? get error => _error;
  // AI-generated END - error

  // AI-generated START - 获取是否还有更多数据
  bool get hasMore => _hasMore;
  // AI-generated END - hasMore

  // AI-generated START - 构造函数
  TemplateSelectionProvider() {
    loadTemplates();
  }
  // AI-generated END - 构造函数

  // AI-generated START - 加载模版列表
  /// 从 API 加载模版列表
  Future<void> loadTemplates() async {
    _isLoading = true;
    _error = null;
    _hasMore = true;
    _cursor = '';
    notifyListeners();

    try {
      //真实API调用（已注释）
      final request = MPGetTemplateListRequest(
        pageSize: 20,
        cursor: _cursor,
      );
      final response = await mp_template_api.getTemplateList(request);
      if (response == null) {
        _error = '获取模版列表失败';
        _templates = [];
        return;
      }
      // 检查响应状态
      if (response.baseResp.code != 0) {
        _error = response.baseResp.message;
        _templates = [];
      } else {
        // 根据后台返回的数据结构创建 CardItem 列表
        _templates = <CardItem>[];

        // 1. 最近使用的模板（如果有）
        if (response.recentTemplate != null) {
          _templates.add(CardItem(
            title: '最近使用',
            items: [
              _convertToHorizontalScrollItem(response.recentTemplate!),
            ],
          ));
        }

        // 2. 推荐模板
        if (response.recommendTemplates.isNotEmpty) {
          _templates.add(CardItem(
            title: '推荐模板',
            items: response.recommendTemplates.map((template) => _convertToHorizontalScrollItem(template)).toList(),
          ));
        }

        // 3. 自定义模板
        final customTemplateItems = response.customTemplates
            .map((template) => _convertToHorizontalScrollItem(template, isMyTemplate: true))
            .toList();

        // 添加"创建模板"项到自定义模板列表的开头
        customTemplateItems.insert(
            0,
            const HorizontalScrollTemplateItem(
              id: 'create_template',
              title: '创建模板',
              isCreateItem: true,
            ));

        _templates.add(CardItem(
          title: '自定义模板',
          items: customTemplateItems,
        ));

        // 4. templates map 中的模板（按 key 分组）
        if (response.templates.isNotEmpty) {
          // 遍历 Map，将 key 作为 title，value（List）作为 items
          response.templates.forEach((key, templatesList) {
            if (templatesList.isNotEmpty) {
              final templateItems = templatesList.map((template) => _convertToHorizontalScrollItem(template)).toList();
              _templates.add(CardItem(
                title: key, // 使用 Map 的 key 作为 title
                items: templateItems, // 使用 Map 的 value（List）作为 items
              ));
            }
          });
        }

        _hasMore = response.hasMore;
        // 更新游标
        if (_templates.isNotEmpty && _templates.last.items.isNotEmpty) {
          _cursor = _templates.last.items.last.title;
        }
      }

      notifyListeners();
    } catch (e) {
      _error = e.toString();
      debugPrint('加载模版列表失败: $e');
      notifyListeners();
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }
  // AI-generated END - 加载模版列表

  // AI-generated START - 转换数据模型
  /// 将 MPTemplateStruct 转换为 HorizontalScrollTemplateItem
  HorizontalScrollTemplateItem _convertToHorizontalScrollItem(
    MPTemplateStruct template, {
    bool isMyTemplate = false,
  }) {
    // 优先使用 template.icon 作为网络图片URL
    // 如果没有 template.icon，则使用默认图标和颜色
    final iconUrl = template.icon;
    IconData? iconData;
    Color? iconColor;

    if (iconUrl == null || iconUrl.isEmpty) {
      // 如果没有 icon URL，使用默认图标和颜色
      iconData = _getIconForTemplate(template.title ?? '');
      iconColor = _getColorForTemplate(template.title ?? '');
    }

    return HorizontalScrollTemplateItem(
      id: template.id ?? '',
      title: template.title ?? '',
      imageUrl: iconUrl,
      icon: iconData,
      iconColor: iconColor,
      backgroundColor: Colors.white,
      isMyTemplate: isMyTemplate,
    );
  }
  // AI-generated END - 转换数据模型

  // AI-generated START - 获取图标
  /// 根据模版标题获取对应的图标
  IconData _getIconForTemplate(String title) {
    if (title.contains('会议') || title.contains('会议纪要')) {
      return Icons.people;
    } else if (title.contains('项目') || title.contains('项目总结')) {
      return Icons.assessment;
    } else if (title.contains('学习') || title.contains('笔记')) {
      return Icons.menu_book;
    } else if (title.contains('面试')) {
      return Icons.person_outline;
    } else if (title.contains('通话') || title.contains('摘要')) {
      return Icons.phone;
    } else {
      return Icons.description; // 默认图标
    }
  }
  // AI-generated END - 获取图标

  // AI-generated START - 获取颜色
  /// 根据模版标题获取对应的颜色
  Color _getColorForTemplate(String title) {
    if (title.contains('会议') || title.contains('会议纪要')) {
      return const Color(0xFF64B5F6); // 浅蓝色
    } else if (title.contains('项目') || title.contains('项目总结')) {
      return const Color(0xFF81C784); // 绿色
    } else if (title.contains('学习') || title.contains('笔记')) {
      return const Color(0xFFBA68C8); // 紫色
    } else if (title.contains('面试')) {
      return const Color(0xFF9575CD); // 浅紫色
    } else if (title.contains('通话') || title.contains('摘要')) {
      return const Color(0xFF22C55E); // 绿色
    } else {
      return const Color(0xFF9CA3AF); // 默认灰色
    }
  }
  // AI-generated END - 获取颜色

  // AI-generated START - 选择模版
  void selectTemplate(int cardIndex, int itemIndex) {
    if (cardIndex >= 0 && cardIndex < _templates.length) {
      final card = _templates[cardIndex];
      if (itemIndex >= 0 && itemIndex < card.items.length) {
        _selectedIndex = cardIndex;
        notifyListeners();
      }
    }
  }
  // AI-generated END - 选择模版

  // AI-generated START - 添加模版
  void addTemplate(CardItem template) {
    _templates.add(template);
    notifyListeners();
  }
  // AI-generated END - 添加模版

  // AI-generated START - 删除模版
  void removeTemplate(int index) {
    if (index >= 0 && index < _templates.length) {
      _templates.removeAt(index);
      if (_selectedIndex == index) {
        _selectedIndex = null;
      } else if (_selectedIndex != null && _selectedIndex! > index) {
        _selectedIndex = _selectedIndex! - 1;
      }
      notifyListeners();
    }
  }
  // AI-generated END - 删除模版

  // AI-generated START - 刷新数据
  /// 刷新模版列表
  Future<void> refresh() async {
    await loadTemplates();
  }
  // AI-generated END - 刷新数据

  // AI-generated START - 加载更多模版
  /// 加载更多模版数据
  Future<void> loadMoreTemplates() async {
    if (_isLoading || !_hasMore) return;

    _isLoading = true;
    notifyListeners();

    try {
      // 调用 API 加载更多模版数据
      final request = MPGetTemplateListRequest(
        pageSize: 20,
        cursor: _cursor,
      );

      final response = await mp_template_api.getTemplateList(request);

      if (response != null) {
        if (response.baseResp.code != 0) {
          debugPrint('加载更多模版失败: ${response.baseResp.message}');
        } else {
          // 根据后台返回的数据结构创建 CardItem 列表并追加
          final moreCardItems = <CardItem>[];

          // 1. 最近使用的模板（如果有）
          if (response.recentTemplate != null) {
            moreCardItems.add(CardItem(
              title: '最近使用',
              items: [
                _convertToHorizontalScrollItem(response.recentTemplate!),
              ],
            ));
          }

          // 2. 推荐模板
          if (response.recommendTemplates.isNotEmpty) {
            moreCardItems.add(CardItem(
              title: '推荐模板',
              items: response.recommendTemplates.map((template) => _convertToHorizontalScrollItem(template)).toList(),
            ));
          }

          // 3. 自定义模板
          final moreCustomTemplateItems = response.customTemplates
              .map((template) => _convertToHorizontalScrollItem(template, isMyTemplate: true))
              .toList();

          // 添加"创建模板"项到自定义模板列表的开头
          moreCustomTemplateItems.insert(
              0,
              const HorizontalScrollTemplateItem(
                id: 'create_template',
                title: '创建模板',
                isCreateItem: true,
              ));

          moreCardItems.add(CardItem(
            title: '自定义模板',
            items: moreCustomTemplateItems,
          ));

          // 4. templates map 中的模板（按 key 分组）
          if (response.templates.isNotEmpty) {
            // 遍历 Map，将 key 作为 title，value（List）作为 items
            response.templates.forEach((key, templatesList) {
              if (templatesList.isNotEmpty) {
                final templateItems =
                    templatesList.map((template) => _convertToHorizontalScrollItem(template)).toList();
                moreCardItems.add(CardItem(
                  title: key, // 使用 Map 的 key 作为 title
                  items: templateItems, // 使用 Map 的 value（List）作为 items
                ));
              }
            });
          }

          _templates.addAll(moreCardItems);
          _hasMore = response.hasMore;
          // 更新游标
          if (moreCardItems.isNotEmpty && moreCardItems.last.items.isNotEmpty) {
            _cursor = moreCardItems.last.items.last.title;
          }
        }
      } else {
        debugPrint('加载更多模版失败: 响应为空');
      }

      notifyListeners();
    } catch (e) {
      debugPrint('加载更多模版失败: $e');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }
  // AI-generated END - 加载更多模版
}
// AI-generated END - template_selection_provider.dart
