// AI-generated START - 编辑任务弹窗组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_popup/new_task_popup.dart';

/// 编辑任务弹窗组件
/// 用于编辑现有任务的详细信息
class EditTaskPopup extends StatefulWidget {
  // AI-generated START - 构造函数
  const EditTaskPopup({
    super.key,
    required this.title,
    this.dueDate,
    this.priority,
    this.isCompleted = false,
    this.onComplete,
    this.onDelete,
    this.onCancel,
    this.maxTitleLength = 200,
  });
  // AI-generated END - 构造函数

  /// 任务标题
  final String title;

  /// 截止日期
  final DateTime? dueDate;

  /// 优先级
  final TaskPriority? priority;

  /// 是否已完成
  final bool isCompleted;

  /// 完成回调，参数为任务标题、截止日期、优先级和完成状态
  final Function(String title, DateTime? dueDate, TaskPriority? priority, bool isCompleted)? onComplete;

  /// 删除回调
  final VoidCallback? onDelete;

  /// 取消回调
  final VoidCallback? onCancel;

  /// 标题最大字符长度（默认200）
  final int maxTitleLength;

  // AI-generated START - 创建状态
  @override
  State<EditTaskPopup> createState() => _EditTaskPopupState();
  // AI-generated END - 创建状态

  // AI-generated START - 显示弹窗静态方法
  /// 显示编辑任务弹窗（底部显示）
  static Future<T?> show<T>({
    required BuildContext context,
    required String title,
    DateTime? dueDate,
    TaskPriority? priority,
    bool isCompleted = false,
    Function(String title, DateTime? dueDate, TaskPriority? priority, bool isCompleted)? onComplete,
    VoidCallback? onDelete,
    VoidCallback? onCancel,
    int maxTitleLength = 200,
  }) {
    return showModalBottomSheet<T>(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) {
        final keyboardHeight = MediaQuery.of(context).viewInsets.bottom;

        return Padding(
          padding: EdgeInsets.only(bottom: keyboardHeight),
          child: GestureDetector(
            onTap: () {}, // 阻止事件冒泡
            child: Container(
              decoration: const BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(20.0),
                  topRight: Radius.circular(20.0),
                ),
              ),
              child: SafeArea(
                child: EditTaskPopup(
                  title: title,
                  dueDate: dueDate,
                  priority: priority,
                  isCompleted: isCompleted,
                  onComplete: onComplete,
                  onDelete: onDelete,
                  onCancel: onCancel ?? () => Navigator.of(context).pop(),
                  maxTitleLength: maxTitleLength,
                ),
              ),
            ),
          ),
        );
      },
    );
  }
  // AI-generated END - 显示弹窗静态方法
}

class _EditTaskPopupState extends State<EditTaskPopup> {
  // AI-generated START - 文本编辑控制器
  late final TextEditingController _titleController;
  // AI-generated END - 文本编辑控制器

  // AI-generated START - 截止日期
  DateTime? _dueDate;
  // AI-generated END - 截止日期

  // AI-generated START - 优先级
  TaskPriority? _priority;
  // AI-generated END - 优先级

  // AI-generated START - 完成状态
  late bool _isCompleted;
  // AI-generated END - 完成状态

  // AI-generated START - 初始化状态
  @override
  void initState() {
    super.initState();
    _titleController = TextEditingController(text: widget.title);
    _dueDate = widget.dueDate;
    _priority = widget.priority;
    _isCompleted = widget.isCompleted;
  }
  // AI-generated END - 初始化状态

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(20.0),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // 顶部：关闭按钮、标题和完成按钮
          _buildHeader(context),
          const SizedBox(height: 24.0),
          // Mark complete复选框
          _buildCompleteCheckbox(),
          const SizedBox(height: 20.0),
          // 任务标题输入框
          _buildTitleInput(),
          const SizedBox(height: 20.0),
          // Due date字段
          _buildDueDateField(context),
          const SizedBox(height: 16.0),
          // Priority字段
          _buildPriorityField(context),
          const SizedBox(height: 24.0),
          // 删除任务按钮
          _buildDeleteButton(context),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建头部
  /// 构建头部：关闭按钮、标题和完成按钮
  Widget _buildHeader(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        // 关闭按钮
        GestureDetector(
          onTap: () {
            if (widget.onCancel != null) {
              widget.onCancel!();
            } else {
              Navigator.of(context).pop();
            }
          },
          child: Container(
            width: 32.0,
            height: 32.0,
            decoration: BoxDecoration(
              color: Colors.grey[100],
              shape: BoxShape.circle,
            ),
            child: const Icon(
              Icons.close,
              size: 20.0,
              color: Color(0xFF212121),
            ),
          ),
        ),
        // 标题（显示任务标题）
        Expanded(
          child: Text(
            widget.title,
            textAlign: TextAlign.center,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
            style: const TextStyle(
              fontSize: 18.0,
              fontWeight: FontWeight.bold,
              color: Color(0xFF212121),
            ),
          ),
        ),
        // 完成按钮
        TextButton(
          onPressed: _titleController.text.trim().isNotEmpty
              ? () {
                  if (widget.onComplete != null) {
                    widget.onComplete!(
                      _titleController.text.trim(),
                      _dueDate,
                      _priority,
                      _isCompleted,
                    );
                  }
                  Navigator.of(context).pop();
                }
              : null,
          style: TextButton.styleFrom(
            foregroundColor: const Color(0xFF2196F3),
            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
          ),
          child: const Text(
            '完成',
            style: TextStyle(
              fontSize: 16.0,
              fontWeight: FontWeight.w600,
            ),
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建头部

  // AI-generated START - 构建完成复选框
  /// 构建Mark complete复选框
  Widget _buildCompleteCheckbox() {
    return Row(
      children: [
        Checkbox(
          value: _isCompleted,
          onChanged: (value) {
            setState(() {
              _isCompleted = value ?? false;
            });
          },
        ),
        const Text(
          'Mark complete',
          style: TextStyle(
            fontSize: 16.0,
            color: Color(0xFF212121),
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建完成复选框

  // AI-generated START - 构建标题输入框
  /// 构建任务标题输入框
  Widget _buildTitleInput() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        TextField(
          controller: _titleController,
          maxLength: widget.maxTitleLength,
          decoration: InputDecoration(
            hintText: '输入任务标题...',
            hintStyle: TextStyle(
              fontSize: 16.0,
              color: Colors.grey[400],
            ),
            border: InputBorder.none,
            contentPadding: EdgeInsets.zero,
            counterText: '',
          ),
          style: const TextStyle(
            fontSize: 16.0,
            color: Color(0xFF212121),
          ),
          onChanged: (value) {
            setState(() {});
          },
        ),
        const SizedBox(height: 4.0),
        // 字符计数
        Text(
          '${_titleController.text.length}/${widget.maxTitleLength}',
          textAlign: TextAlign.right,
          style: TextStyle(
            fontSize: 12.0,
            color: Colors.grey[500],
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建标题输入框

  // AI-generated START - 构建截止日期字段
  /// 构建截止日期字段
  Widget _buildDueDateField(BuildContext context) {
    return GestureDetector(
      onTap: () async {
        final pickedDate = await showDatePicker(
          context: context,
          initialDate: _dueDate ?? DateTime.now(),
          firstDate: DateTime.now(),
          lastDate: DateTime.now().add(const Duration(days: 365)),
        );
        if (pickedDate != null) {
          setState(() {
            _dueDate = pickedDate;
          });
        }
      },
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12.0),
        decoration: BoxDecoration(
          border: Border(
            bottom: BorderSide(
              color: Colors.grey[300]!,
              width: 1.0,
            ),
          ),
        ),
        child: Row(
          children: [
            Icon(
              Icons.calendar_today,
              size: 20.0,
              color: Colors.grey[600],
            ),
            const SizedBox(width: 12.0),
            const Text(
              'Due date',
              style: TextStyle(
                fontSize: 16.0,
                fontWeight: FontWeight.w500,
                color: Color(0xFF212121),
              ),
            ),
            const Spacer(),
            Text(
              _dueDate != null
                  ? '${_dueDate!.year}-${_dueDate!.month.toString().padLeft(2, '0')}-${_dueDate!.day.toString().padLeft(2, '0')}'
                  : '-/-/-',
              style: TextStyle(
                fontSize: 16.0,
                color: _dueDate != null ? const Color(0xFF212121) : Colors.grey[400],
              ),
            ),
            const SizedBox(width: 8.0),
            if (_dueDate != null)
              GestureDetector(
                onTap: () {
                  setState(() {
                    _dueDate = null;
                  });
                },
                child: Icon(
                  Icons.close,
                  size: 18.0,
                  color: Colors.grey[400],
                ),
              )
            else
              Icon(
                Icons.calendar_today,
                size: 18.0,
                color: Colors.grey[400],
              ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建截止日期字段

  // AI-generated START - 构建优先级字段
  /// 构建优先级字段
  Widget _buildPriorityField(BuildContext context) {
    return GestureDetector(
      onTap: () {
        showModalBottomSheet(
          context: context,
          builder: (context) {
            return SafeArea(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  ListTile(
                    leading: const Icon(Icons.flag, color: Colors.grey),
                    title: const Text('低'),
                    onTap: () {
                      setState(() {
                        _priority = TaskPriority.low;
                      });
                      Navigator.pop(context);
                    },
                  ),
                  ListTile(
                    leading: const Icon(Icons.flag, color: Colors.orange),
                    title: const Text('普通'),
                    onTap: () {
                      setState(() {
                        _priority = TaskPriority.normal;
                      });
                      Navigator.pop(context);
                    },
                  ),
                  ListTile(
                    leading: const Icon(Icons.flag, color: Colors.red),
                    title: const Text('高'),
                    onTap: () {
                      setState(() {
                        _priority = TaskPriority.high;
                      });
                      Navigator.pop(context);
                    },
                  ),
                ],
              ),
            );
          },
        );
      },
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12.0),
        decoration: BoxDecoration(
          border: Border(
            bottom: BorderSide(
              color: Colors.grey[300]!,
              width: 1.0,
            ),
          ),
        ),
        child: Row(
          children: [
            Icon(
              Icons.flag,
              size: 20.0,
              color: _getPriorityColor(),
            ),
            const SizedBox(width: 12.0),
            const Text(
              'Priority',
              style: TextStyle(
                fontSize: 16.0,
                fontWeight: FontWeight.w500,
                color: Color(0xFF212121),
              ),
            ),
            const Spacer(),
            Text(
              _getPriorityText(),
              style: TextStyle(
                fontSize: 16.0,
                color: _priority != null ? const Color(0xFF212121) : Colors.grey[400],
              ),
            ),
            const SizedBox(width: 8.0),
            Icon(
              Icons.keyboard_arrow_down,
              size: 20.0,
              color: Colors.grey[400],
            ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建优先级字段

  // AI-generated START - 构建删除按钮
  /// 构建删除任务按钮
  Widget _buildDeleteButton(BuildContext context) {
    return GestureDetector(
      onTap: () {
        if (widget.onDelete != null) {
          widget.onDelete!();
        }
        Navigator.of(context).pop();
      },
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(
            Icons.delete_outline,
            size: 20.0,
            color: Colors.red[400],
          ),
          const SizedBox(width: 8.0),
          Text(
            '删除任务',
            style: TextStyle(
              fontSize: 16.0,
              color: Colors.red[400],
              fontWeight: FontWeight.w500,
            ),
          ),
        ],
      ),
    );
  }
  // AI-generated END - 构建删除按钮

  // AI-generated START - 获取优先级文本
  /// 获取优先级文本
  String _getPriorityText() {
    switch (_priority) {
      case TaskPriority.low:
        return '低';
      case TaskPriority.normal:
        return '普通';
      case TaskPriority.high:
        return '高';
      case null:
        return '选择优先级';
    }
  }
  // AI-generated END - 获取优先级文本

  // AI-generated START - 获取优先级颜色
  /// 获取优先级颜色
  Color _getPriorityColor() {
    switch (_priority) {
      case TaskPriority.low:
        return Colors.grey;
      case TaskPriority.normal:
        return Colors.orange;
      case TaskPriority.high:
        return Colors.red;
      case null:
        return Colors.grey[400]!;
    }
  }
  // AI-generated END - 获取优先级颜色

  // AI-generated START - 清理资源
  @override
  void dispose() {
    _titleController.dispose();
    super.dispose();
  }
  // AI-generated END - 清理资源
}
// AI-generated END - edit_task_popup.dart
