// AI-generated START - 灵感详情弹窗组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_popup/mp_center_popup.dart';

/// 灵感详情弹窗组件
/// 用于显示和编辑灵感/备忘录的详细信息
class InspirationDetailPopup extends StatefulWidget {
  // AI-generated START - 构造函数
  const InspirationDetailPopup({
    super.key,
    required this.title,
    required this.content,
    required this.dateTime,
    this.tags = const [],
    this.onSave,
    this.onClose,
  });
  // AI-generated END - 构造函数

  /// 标题
  final String title;

  /// 内容文本
  final String content;

  /// 日期时间
  final String dateTime;

  /// 标签列表
  final List<String> tags;

  /// 保存回调，参数为编辑后的内容
  final ValueChanged<String>? onSave;

  /// 关闭回调
  final VoidCallback? onClose;

  // AI-generated START - 创建状态
  @override
  State<InspirationDetailPopup> createState() => _InspirationDetailPopupState();
  // AI-generated END - 创建状态

  // AI-generated START - 显示弹窗静态方法
  /// 显示灵感详情弹窗
  static Future<T?> show<T>({
    required BuildContext context,
    required String title,
    required String content,
    required String dateTime,
    List<String> tags = const [],
    ValueChanged<String>? onSave,
    VoidCallback? onClose,
    double maxWidthScale = 0.9,
    double maxHeightScale = 0.8,
  }) {
    return MPCenterPopup.show<T>(
      context: context,
      contentWidget: InspirationDetailPopup(
        title: title,
        content: content,
        dateTime: dateTime,
        tags: tags,
        onSave: onSave,
        onClose: onClose ?? () => Navigator.of(context).pop(),
      ),
      maxWidthScale: maxWidthScale,
      maxHeightScale: maxHeightScale,
    );
  }
  // AI-generated END - 显示弹窗静态方法
}

class _InspirationDetailPopupState extends State<InspirationDetailPopup> {
  // AI-generated START - 文本编辑控制器
  late final TextEditingController _contentController;
  // AI-generated END - 文本编辑控制器

  // AI-generated START - 初始化状态
  @override
  void initState() {
    super.initState();
    _contentController = TextEditingController(text: widget.content);
  }
  // AI-generated END - 初始化状态

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
        margin: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 16.0),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16.0),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.1),
              blurRadius: 10.0,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Container(
          padding: const EdgeInsets.all(20.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // 顶部：标题和关闭按钮
              _buildHeader(context),
              const SizedBox(height: 20.0),
              // 主标题
              Text(
                widget.title,
                style: const TextStyle(
                  fontSize: 20.0,
                  fontWeight: FontWeight.bold,
                  color: Color(0xFF212121),
                ),
              ),
              const SizedBox(height: 12.0),
              // 日期时间和标签
              Row(
                children: [
                  Text(
                    widget.dateTime,
                    style: TextStyle(
                      fontSize: 14.0,
                      color: Colors.grey[600],
                    ),
                  ),
                  if (widget.tags.isNotEmpty) ...[
                    const SizedBox(width: 12.0),
                    ...widget.tags.map((tag) => Padding(
                          padding: const EdgeInsets.only(right: 8.0),
                          child: _buildTag(tag),
                        )),
                  ],
                ],
              ),
              const SizedBox(height: 20.0),
              // 内容输入框（可编辑）
              Flexible(
                child: TextField(
                  controller: _contentController,
                  maxLines: null,
                  expands: false,
                  textAlignVertical: TextAlignVertical.top,
                  decoration: InputDecoration(
                    hintText: '输入内容...',
                    hintStyle: TextStyle(
                      fontSize: 16.0,
                      color: Colors.grey[400],
                    ),
                    border: InputBorder.none,
                    contentPadding: EdgeInsets.zero,
                    isDense: true,
                  ),
                  style: const TextStyle(
                    fontSize: 16.0,
                    color: Color(0xFF212121),
                    height: 1.5,
                  ),
                ),
              ),
              const SizedBox(height: 24.0),
              // 保存按钮
              _buildSaveButton(context),
            ],
          ),
        ));
  }
  // AI-generated END - 构建方法

  // AI-generated START - 清理资源
  @override
  void dispose() {
    _contentController.dispose();
    super.dispose();
  }
  // AI-generated END - 清理资源

  // AI-generated START - 构建头部
  /// 构建头部：标题和关闭按钮
  Widget _buildHeader(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        const Text(
          '灵感详情',
          style: TextStyle(
            fontSize: 18.0,
            fontWeight: FontWeight.bold,
            color: Color(0xFF212121),
          ),
        ),
        GestureDetector(
          onTap: () {
            if (widget.onClose != null) {
              widget.onClose!();
            } else {
              Navigator.of(context).pop();
            }
          },
          child: Container(
            width: 32.0,
            height: 32.0,
            decoration: BoxDecoration(
              color: Colors.grey[100],
              shape: BoxShape.circle,
            ),
            child: const Icon(
              Icons.close,
              size: 20.0,
              color: Color(0xFF212121),
            ),
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建头部

  // AI-generated START - 构建标签
  /// 构建标签
  Widget _buildTag(String tag) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8.0, vertical: 4.0),
      decoration: BoxDecoration(
        color: const Color(0xFFE3F2FD), // 浅蓝色背景
        borderRadius: BorderRadius.circular(12.0),
      ),
      child: Text(
        tag,
        style: const TextStyle(
          fontSize: 12.0,
          fontWeight: FontWeight.w500,
          color: Color(0xFF2196F3), // 蓝色文字
        ),
      ),
    );
  }
  // AI-generated END - 构建标签

  // AI-generated START - 构建保存按钮
  /// 构建保存按钮
  Widget _buildSaveButton(BuildContext context) {
    return ElevatedButton(
      onPressed: () {
        if (widget.onSave != null) {
          widget.onSave!(_contentController.text);
        }
        Navigator.of(context).pop();
      },
      style: ElevatedButton.styleFrom(
        backgroundColor: const Color(0xFF9C27B0), // 紫色
        foregroundColor: Colors.white,
        padding: const EdgeInsets.symmetric(vertical: 16.0),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12.0),
        ),
        elevation: 0,
      ),
      child: const Text(
        'Save Memo',
        style: TextStyle(
          fontSize: 16.0,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }
  // AI-generated END - 构建保存按钮
}
// AI-generated END - inspiration_detail_popup.dart
