// AI-generated START - 更多操作弹窗组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';

/// 更多操作弹窗组件
/// 展示重命名、添加标签、复制、重新生成、删除等操作
class MoreActionsPopup extends StatelessWidget {
  // AI-generated START - 图片资源路径常量
  static final String kRenameIcon = Assets.images.mpIconMoreRename.path;
  static final String kAddTagIcon = Assets.images.mpIconMoreAddTag.path;
  static final String kCopyTranscriptIcon = Assets.images.mpIconMoreCopyTranscript.path;
  static final String kCopySummaryIcon = Assets.images.mpIconMoreCopySummary.path;
  static final String kRegenerateIcon = Assets.images.mpIconMoreRegenerate.path;
  static final String kDeleteIcon = Assets.images.iconMoreDeletemp.path;
  // AI-generated END - 图片资源路径常量

  // AI-generated START - 构造函数
  const MoreActionsPopup({
    super.key,
    this.onRename,
    this.onAddTag,
    this.onCopyTranscript,
    this.onCopySummary,
    this.onRegenerateSummary,
    this.onDelete,
    this.onClose,
  });
  // AI-generated END - 构造函数

  /// 重命名回调
  final VoidCallback? onRename;

  /// 添加标签回调
  final VoidCallback? onAddTag;

  /// 复制转写回调
  final VoidCallback? onCopyTranscript;

  /// 复制摘要回调
  final VoidCallback? onCopySummary;

  /// 重新生成摘要回调
  final VoidCallback? onRegenerateSummary;

  /// 删除回调
  final VoidCallback? onDelete;

  /// 关闭回调
  final VoidCallback? onClose;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 16.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16.0),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 10.0,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Padding(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            _buildHeader(context),
            const SizedBox(height: 12.0),
            _buildActionItem(
              icon: Icons.edit,
              iconColor: Colors.indigo,
              title: 'Rename Memory',
              imagePath: kRenameIcon,
              onTap: onRename,
            ),
            const SizedBox(height: 8.0),
            _buildActionItem(
              icon: Icons.label_outline,
              iconColor: Colors.purple,
              title: 'Add Tag',
              imagePath: kAddTagIcon,
              onTap: onAddTag,
            ),
            const SizedBox(height: 8.0),
            _buildActionItem(
              icon: Icons.copy_outlined,
              iconColor: Colors.green,
              title: 'Copy Transcript',
              imagePath: kCopyTranscriptIcon,
              onTap: onCopyTranscript,
            ),
            const SizedBox(height: 8.0),
            _buildActionItem(
              icon: Icons.article_outlined,
              iconColor: Colors.orange,
              title: 'Copy Summary',
              imagePath: kCopySummaryIcon,
              onTap: onCopySummary,
            ),
            const SizedBox(height: 8.0),
            _buildActionItem(
              icon: Icons.refresh,
              iconColor: Colors.blue,
              title: 'Regenerate Summary',
              imagePath: kRegenerateIcon,
              onTap: onRegenerateSummary,
            ),
            const SizedBox(height: 8.0),
            _buildActionItem(
              icon: Icons.delete_outline,
              iconColor: Colors.red,
              title: 'Delete Memory',
              imagePath: kDeleteIcon,
              onTap: onDelete,
            ),
            const SizedBox(height: 24.0),
            _buildCloseButton(context),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建头部
  Widget _buildHeader(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        const Text(
          '更多操作',
          style: TextStyle(
            fontSize: 18.0,
            fontWeight: FontWeight.bold,
            color: Color(0xFF212121),
          ),
        ),
        GestureDetector(
          onTap: () {
            if (onClose != null) {
              onClose!();
            } else {
              Navigator.of(context).pop();
            }
          },
          child: Container(
            width: 32.0,
            height: 32.0,
            decoration: BoxDecoration(
              color: Colors.grey[200],
              shape: BoxShape.circle,
            ),
            child: const Icon(
              Icons.close,
              size: 20.0,
              color: Color(0xFF212121),
            ),
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建头部

  // AI-generated START - 构建操作项
  Widget _buildActionItem({
    required IconData icon,
    required Color iconColor,
    required String title,
    String? imagePath,
    VoidCallback? onTap,
  }) {
    return GestureDetector(
      onTap: () {
        if (onTap != null) onTap();
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 12.0, vertical: 12.0),
        decoration: BoxDecoration(
          color: Colors.grey[50],
          borderRadius: BorderRadius.circular(12.0),
        ),
        child: Row(
          children: [
            Container(
              width: 32.0,
              height: 32.0,
              decoration: BoxDecoration(
                color: iconColor.withOpacity(0.1),
                shape: BoxShape.circle,
              ),
              child: imagePath != null
                  ? ClipOval(
                      child: Image.asset(
                        imagePath,
                        width: 32.0,
                        height: 32.0,
                        fit: BoxFit.cover,
                        errorBuilder: (context, error, stackTrace) {
                          return Icon(
                            icon,
                            size: 18.0,
                            color: iconColor,
                          );
                        },
                      ),
                    )
                  : Icon(
                      icon,
                      size: 18.0,
                      color: iconColor,
                    ),
            ),
            const SizedBox(height: 8.0, width: 12.0),
            Expanded(
              child: Text(
                title,
                style: const TextStyle(
                  fontSize: 15.0,
                  fontWeight: FontWeight.w500,
                  color: Color(0xFF212121),
                ),
              ),
            ),
            Icon(
              Icons.chevron_right,
              size: 20.0,
              color: Colors.grey[400],
            ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建操作项

  // AI-generated START - 构建关闭按钮
  Widget _buildCloseButton(BuildContext context) {
    return GestureDetector(
      onTap: () {
        if (onClose != null) {
          onClose!();
        } else {
          Navigator.of(context).pop();
        }
      },
      child: Container(
        width: 44.0,
        height: 44.0,
        decoration: BoxDecoration(
          color: Colors.grey[300],
          shape: BoxShape.circle,
        ),
        child: const Icon(
          Icons.close,
          size: 20.0,
          color: Colors.white,
        ),
      ),
    );
  }
  // AI-generated END - 构建关闭按钮

  // AI-generated START - 显示弹窗静态方法
  /// 显示更多操作弹窗
  static Future<T?> show<T>({
    required BuildContext context,
    VoidCallback? onRename,
    VoidCallback? onAddTag,
    VoidCallback? onCopyTranscript,
    VoidCallback? onCopySummary,
    VoidCallback? onRegenerateSummary,
    VoidCallback? onDelete,
    VoidCallback? onClose,
  }) {
    return showDialog<T>(
      context: context,
      barrierColor: Colors.black54,
      builder: (context) {
        return Dialog(
          backgroundColor: Colors.transparent,
          child: MoreActionsPopup(
            onRename: onRename,
            onAddTag: onAddTag,
            onCopyTranscript: onCopyTranscript,
            onCopySummary: onCopySummary,
            onRegenerateSummary: onRegenerateSummary,
            onDelete: onDelete,
            onClose: onClose ?? () => Navigator.of(context).pop(),
          ),
        );
      },
    );
  }
  // AI-generated END - 显示弹窗静态方法
}
// AI-generated END - more_actions_popup.dart
