// AI-generated START - 居中弹窗组件 - Generated by AI
import 'package:flutter/material.dart';

/// 中间弹窗
/// 最大：宽度：屏幕宽度，高度：屏幕高度 - 关闭按钮区域高度
/// 最小：32px * 32px
class MPCenterPopup extends StatefulWidget {
  // AI-generated START - 构造函数
  const MPCenterPopup({
    super.key,
    required this.contentWidget,
    this.maxWidthScale = 1.0,
    this.maxHeightScale = 1.0,
    this.onCloseButtonTap,
    this.barrierDismissible = true,
  }) : assert(contentWidget != null);
  // AI-generated END - 构造函数


  /// 自定义的content组件
  final Widget contentWidget;


  /// 最大宽度相对屏幕缩放系数
  final double maxWidthScale;

  /// 最大高度相对屏幕缩放系数
  final double maxHeightScale;


  /// 关闭按钮点击回调
  final Function(BuildContext context)? onCloseButtonTap;

  /// 点击遮罩是否关闭（默认true）
  final bool barrierDismissible;

  // AI-generated START - 创建状态
  @override
  State<MPCenterPopup> createState() => _MPCenterPopupState();
  // AI-generated END - 创建状态

  // AI-generated START - 显示弹窗静态方法
  /// 显示居中弹窗
  static Future<T?> show<T>({
    required BuildContext context,
    required Widget contentWidget,
    bool showCloseButton = true,
    double maxWidthScale = 1.0,
    double maxHeightScale = 1.0,
    BorderRadiusGeometry? borderRadius,
    Function(BuildContext context)? onCloseButtonTap,
    bool barrierDismissible = true,
    Color? barrierColor,
  }) {
    return showDialog<T>(
      context: context,
      barrierDismissible: barrierDismissible,
      barrierColor: barrierColor ?? Colors.black54,
      builder: (context) {
        return Dialog.fullscreen(
          backgroundColor: const Color(0x00000000),
          child: MPCenterPopup(
            contentWidget: contentWidget,
            maxWidthScale: maxWidthScale,
            maxHeightScale: maxHeightScale,
            onCloseButtonTap: onCloseButtonTap ?? (ctx) => Navigator.pop(ctx),
            barrierDismissible: barrierDismissible,
          ),
        );
      },
    );
  }
  // AI-generated END - 显示弹窗静态方法
}

class _MPCenterPopupState extends State<MPCenterPopup> {
 

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    
    final screenWidth = MediaQuery.of(context).size.width;
    final screenHeight = MediaQuery.of(context).size.height;
    
    double maxDialogWidth = screenWidth * widget.maxWidthScale;
    double maxDialogHeight = screenHeight * widget.maxHeightScale;
    
    const double minDialogWidth = 32.0;
    const double minDialogHeight = 32.0;
    
    
    Widget contentWidget = Container(
      color: Colors.transparent,
      child: ConstrainedBox(
        constraints: BoxConstraints(
          maxHeight: maxDialogHeight,
          maxWidth: maxDialogWidth,
          minHeight: minDialogHeight,
          minWidth: minDialogWidth,
        ),
        child: widget.contentWidget,
      ),
    );
      
    List<Widget> columnChildren = [];
    columnChildren.add(contentWidget);
       
    return GestureDetector(
      onTap: widget.barrierDismissible ? _onCloseButtonTap : null,
      child: Container(
        color: Colors.black54,
        child: Material(
          color: const Color(0x00000000),
          child: Center(
            child: GestureDetector(
              onTap: () {}, // 阻止事件冒泡
              child: Column(
                mainAxisSize: MainAxisSize.min,
                mainAxisAlignment: MainAxisAlignment.center,
                children: columnChildren,
              ),
            ),
          ),
        ),
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 关闭按钮点击处理
  void _onCloseButtonTap() {
    if (widget.onCloseButtonTap != null) {
      widget.onCloseButtonTap!(context);
      return;
    }
    Navigator.pop(context);
  }
  // AI-generated END - 关闭按钮点击处理
}
// AI-generated END - mp_center_popup.dart
