// AI-generated START - 新建任务弹窗组件 - Generated by AI
import 'package:flutter/material.dart';

/// 任务优先级枚举
enum TaskPriority {
  low, // 低优先级
  normal, // 普通优先级
  high, // 高优先级
}

/// 新建任务弹窗组件
/// 用于创建新的任务
class NewTaskPopup extends StatefulWidget {
  // AI-generated START - 构造函数
  const NewTaskPopup({
    super.key,
    this.title,
    this.initialTitle,
    this.initialDueDate,
    this.initialPriority,
    this.onComplete,
    this.onCancel,
    this.maxTitleLength = 200,
    this.showMarkComplete = false,
    this.showDeleteTask = false,
    this.isCompleted = false,
    this.onDelete,
  });
  // AI-generated END - 构造函数

  /// 弹窗标题（头部显示的标题）
  final String? title;

  /// 初始任务标题（用于回显）
  final String? initialTitle;

  /// 初始截止日期（用于回显）
  final DateTime? initialDueDate;

  /// 初始优先级（用于回显）
  final TaskPriority? initialPriority;

  /// 完成回调，参数为任务标题、截止日期和优先级
  final Function(bool, String title, DateTime? dueDate, TaskPriority? priority)? onComplete;

  /// 取消回调
  final VoidCallback? onCancel;

  /// 标题最大字符长度（默认200）
  final int maxTitleLength;

  /// 是否显示 Mark complete 复选框
  final bool showMarkComplete;

  /// 是否显示删除任务按钮
  final bool showDeleteTask;

  /// 是否已完成（用于 Mark complete 复选框的初始状态）
  final bool isCompleted;

  /// 删除任务回调
  final VoidCallback? onDelete;

  // AI-generated START - 创建状态
  @override
  State<NewTaskPopup> createState() => _NewTaskPopupState();
  // AI-generated END - 创建状态

  // AI-generated START - 显示弹窗静态方法
  /// 显示新建任务弹窗（底部显示）
  static Future<T?> show<T>({
    required BuildContext context,
    String? todoId,
    String? title,
    String? initialTitle,
    DateTime? initialDueDate,
    TaskPriority? initialPriority,
    Function(bool isCompleted, String title, DateTime? dueDate, TaskPriority? priority)? onComplete,
    VoidCallback? onCancel,
    int maxTitleLength = 200,
    bool showMarkComplete = false,
    bool showDeleteTask = false,
    bool isCompleted = false,
    VoidCallback? onDelete,
  }) {
    return showModalBottomSheet<T>(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) {
        final keyboardHeight = MediaQuery.of(context).viewInsets.bottom;

        return Padding(
          padding: EdgeInsets.only(bottom: keyboardHeight),
          child: GestureDetector(
            onTap: () {}, // 阻止事件冒泡
            child: Container(
              decoration: const BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(20.0),
                  topRight: Radius.circular(20.0),
                ),
              ),
              child: SafeArea(
                child: NewTaskPopup(
                  title: title,
                  initialTitle: initialTitle,
                  initialDueDate: initialDueDate,
                  initialPriority: initialPriority,
                  onComplete: onComplete,
                  onCancel: onCancel ?? () => Navigator.of(context).pop(),
                  maxTitleLength: maxTitleLength,
                  showMarkComplete: showMarkComplete,
                  showDeleteTask: showDeleteTask,
                  isCompleted: isCompleted,
                  onDelete: onDelete,
                ),
              ),
            ),
          ),
        );
      },
    );
  }
  // AI-generated END - 显示弹窗静态方法
}

class _NewTaskPopupState extends State<NewTaskPopup> {
  // AI-generated START - 文本编辑控制器
  late final TextEditingController _titleController;
  // AI-generated END - 文本编辑控制器

  // AI-generated START - 截止日期
  DateTime? _dueDate;
  // AI-generated END - 截止日期

  // AI-generated START - 优先级
  TaskPriority? _priority;
  // AI-generated END - 优先级

  // AI-generated START - 完成状态
  late bool _isCompleted;
  // AI-generated END - 完成状态

  // AI-generated START - 初始化状态
  @override
  void initState() {
    super.initState();
    // 初始化文本控制器，如果有初始标题则设置
    _titleController = TextEditingController(text: widget.initialTitle ?? '');
    // 初始化截止日期
    _dueDate = widget.initialDueDate;
    // 初始化优先级
    _priority = widget.initialPriority;
    // 初始化完成状态
    _isCompleted = widget.isCompleted;
  }
  // AI-generated END - 初始化状态

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(12.0),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // 顶部：关闭按钮、标题和完成按钮
          _buildHeader(context),
          const SizedBox(height: 12.0),
          const Divider(
            height: 1.0,
            color: Color(0xFFE5E7EB),
          ),
          const SizedBox(height: 12.0),
          // Mark complete复选框（如果启用）
          if (widget.showMarkComplete) ...[
            _buildCompleteCheckbox(),
            const SizedBox(height: 12.0),
          ],
          // 任务标题输入框
          _buildTitleInput(),

          // Due date字段
          _buildDueDateField(context),
          const SizedBox(height: 12.0),
          // Priority字段
          _buildPriorityField(context),
          const SizedBox(height: 20.0),
          // 删除任务按钮（如果启用）
          if (widget.showDeleteTask) ...[
            _buildDeleteButton(context),
            const SizedBox(height: 12.0),
          ],
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建头部
  /// 构建头部：关闭按钮、标题和完成按钮
  Widget _buildHeader(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        // 关闭按钮
        GestureDetector(
          onTap: () {
            if (widget.onCancel != null) {
              widget.onCancel!();
            } else {
              Navigator.of(context).pop();
            }
          },
          child: Container(
            width: 40.0,
            height: 40.0,
            decoration: const BoxDecoration(
              color: Color(0xFFF3F4F6),
              shape: BoxShape.circle,
            ),
            child: const Icon(
              Icons.close,
              size: 20.0,
              color: Color(0xFF374151),
            ),
          ),
        ),
        // 标题
        Text(
          widget.title ?? '新建任务',
          style: const TextStyle(
            fontSize: 14.0,
            fontWeight: FontWeight.bold,
            color: Color(0xFF1F2937),
          ),
        ),
        // 完成按钮
        TextButton(
          onPressed: () {
            if (widget.onComplete != null) {
              widget.onComplete!(
                _isCompleted,
                _titleController.text.trim(),
                _dueDate,
                _priority,
              );
            }
            Navigator.of(context).pop();
          },
          style: TextButton.styleFrom(
            foregroundColor: const Color(0xFF2196F3),
            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
          ),
          child: const Text(
            '完成',
            style: TextStyle(
              fontSize: 14.0,
              fontWeight: FontWeight.w600,
              color: Color(0xFF2563EB),
            ),
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建头部

  // AI-generated START - 构建标题输入框
  /// 构建任务标题输入框
  Widget _buildTitleInput() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        TextField(
          controller: _titleController,
          maxLength: widget.maxTitleLength,
          decoration: const InputDecoration(
            hintText: '输入任务详情...',
            hintStyle: TextStyle(
              fontSize: 14.0,
              color: Color(0xFF9CA3AF),
            ),
            border: InputBorder.none,
            contentPadding: EdgeInsets.zero,
            counterText: '',
          ),
          style: const TextStyle(
            fontSize: 14.0,
            color: Color(0xFF374151),
          ),
          onChanged: (value) {
            setState(() {});
          },
        ),
        const SizedBox(height: 4.0),
        const Divider(
          height: 1.0,
          color: Color(0xFFE5E7EB),
        ),
        const SizedBox(height: 8.0),
        // 字符计数
        Text(
          '${_titleController.text.length}/${widget.maxTitleLength}',
          textAlign: TextAlign.right,
          style: const TextStyle(
            fontSize: 12.0,
            color: Color(0xFF6B7280),
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建标题输入框

  // AI-generated START - 构建截止日期字段
  /// 构建截止日期字段
  Widget _buildDueDateField(BuildContext context) {
    return GestureDetector(
      onTap: () async {
        final pickedDate = await showDatePicker(
          context: context,
          initialDate: _dueDate ?? DateTime.now(),
          firstDate: DateTime.now(),
          lastDate: DateTime.now().add(const Duration(days: 365)),
        );
        if (pickedDate != null) {
          setState(() {
            _dueDate = pickedDate;
          });
        }
      },
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12.0, horizontal: 8.0),
        decoration: BoxDecoration(
          color: const Color(0xFFF9FAFB),
          borderRadius: BorderRadius.circular(16.0),
        ),
        child: Row(
          children: [
            Image.asset(
              'assets/images/mp_todo_add_canlendar.png',
              width: 17.0,
              height: 16.0,
              fit: BoxFit.contain,
            ),
            const SizedBox(width: 8.0),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                  const Text(
                    'Due date',
                    style: TextStyle(
                      fontSize: 12.0,
                      fontWeight: FontWeight.normal,
                      color: Color(0xFF6B7280),
                    ),
                  ),
                  const SizedBox(height: 4.0),
                  Text(
                    _dueDate != null
                        ? '${_dueDate!.year}-${_dueDate!.month.toString().padLeft(2, '0')}-${_dueDate!.day.toString().padLeft(2, '0')}'
                        : '-/-/-',
                    style: TextStyle(
                      fontSize: 14.0,
                      color: _dueDate != null ? const Color(0xFF1F2937) : Colors.grey[400],
                    ),
                  ),
                ],
              ),
            ),
            if (_dueDate != null)
              GestureDetector(
                onTap: () {
                  setState(() {
                    _dueDate = null;
                  });
                },
                child: const Icon(
                  Icons.close,
                  size: 14.0,
                  color: Color(0xFF4B5563),
                ),
              )
            else
              const Icon(
                Icons.calendar_today,
                size: 14.0,
                color: Color(0xFF4B5563),
              ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建截止日期字段

  // AI-generated START - 构建优先级字段
  /// 构建优先级字段
  Widget _buildPriorityField(BuildContext context) {
    return GestureDetector(
      onTap: () {
        showModalBottomSheet(
          context: context,
          builder: (context) {
            return SafeArea(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  ListTile(
                    title: const Text('低'),
                    onTap: () {
                      setState(() {
                        _priority = TaskPriority.low;
                      });
                      Navigator.pop(context);
                    },
                  ),
                  ListTile(
                    title: const Text('普通'),
                    onTap: () {
                      setState(() {
                        _priority = TaskPriority.normal;
                      });
                      Navigator.pop(context);
                    },
                  ),
                  ListTile(
                    title: const Text('高'),
                    onTap: () {
                      setState(() {
                        _priority = TaskPriority.high;
                      });
                      Navigator.pop(context);
                    },
                  ),
                ],
              ),
            );
          },
        );
      },
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12.0, horizontal: 8.0),
        decoration: BoxDecoration(
          color: const Color(0xFFF9FAFB),
          borderRadius: BorderRadius.circular(16.0),
        ),
        child: Row(
          children: [
            Image.asset(
              'assets/images/mp_todo_add_priority.png',
              width: 17.0,
              height: 24.0,
              fit: BoxFit.contain,
            ),
            const SizedBox(width: 8.0),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                  const Text(
                    'Priority',
                    style: TextStyle(
                      fontSize: 12.0,
                      fontWeight: FontWeight.w400,
                      color: Color(0xFF6B7280),
                    ),
                  ),
                  const SizedBox(height: 2.0),
                  Text(
                    _getPriorityText(),
                    style: TextStyle(
                      fontSize: 14.0,
                      color: _priority != null ? const Color(0xFF1F2937) : Colors.grey[400],
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(width: 8.0),
            const Icon(
              Icons.keyboard_arrow_down,
              size: 16.0,
              color: Color(0xFF000000),
            ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建优先级字段

  // AI-generated START - 获取优先级文本
  /// 获取优先级文本
  String _getPriorityText() {
    switch (_priority) {
      case TaskPriority.low:
        return '低';
      case TaskPriority.normal:
        return '普通';
      case TaskPriority.high:
        return '高';
      case null:
        return '选择优先级';
    }
  }
  // AI-generated END - 获取优先级文本

  // AI-generated START - 构建完成复选框
  /// 构建Mark complete复选框
  Widget _buildCompleteCheckbox() {
    return Container(
      height: 36,
      decoration: BoxDecoration(
        color: const Color(0xFFF9FAFB),
        borderRadius: BorderRadius.circular(12.0),
      ),
      child: Center(
        child: Row(
          children: [
            Checkbox(
              value: _isCompleted,
              activeColor: const Color(0xFF3B82F6), // 选中时的背景颜色
              checkColor: Colors.white, // 选中时的勾选标记颜色
              fillColor: WidgetStateProperty.resolveWith<Color?>(
                (Set<WidgetState> states) {
                  if (states.contains(WidgetState.selected)) {
                    return const Color(0xFF3B82F6); // 选中时的背景颜色
                  }
                  return null; // 未选中时使用默认颜色
                },
              ),
              onChanged: (value) {
                setState(() {
                  _isCompleted = value ?? false;
                });
              },
            ),
            const Text(
              'Mark complete',
              style: TextStyle(
                fontSize: 14.0,
                color: Color(0xFF1F2937),
              ),
            ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建完成复选框

  // AI-generated START - 构建删除按钮
  /// 构建删除任务按钮
  Widget _buildDeleteButton(BuildContext context) {
    return GestureDetector(
      onTap: () {
        if (widget.onDelete != null) {
          widget.onDelete!();
        }
        Navigator.of(context).pop();
      },
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12.0, horizontal: 16.0),
        decoration: BoxDecoration(
          color: Colors.transparent,
          borderRadius: BorderRadius.circular(8.0),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.delete_outline,
              size: 16.0,
              color: Color(0xFFDC2626),
            ),
            const SizedBox(width: 8.0),
            Text(
              '删除任务',
              style: TextStyle(
                fontSize: 14.0,
                color: Color(0xFFDC2626),
                fontWeight: FontWeight.w500,
              ),
            ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建删除按钮

  // AI-generated START - 清理资源
  @override
  void dispose() {
    _titleController.dispose();
    super.dispose();
  }
  // AI-generated END - 清理资源
}
// AI-generated END - new_task_popup.dart
