// AI-generated START - 新建记忆弹窗组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_custom_utils/mp_toast_utils.dart';

/// 新建记忆弹窗组件
/// 用于创建新的记忆/备忘录
class NewMemoPopup extends StatefulWidget {
  // AI-generated START - 输入框高度常量
  static const double kInputFieldHeight = 200.0;
  // AI-generated END - 输入框高度常量

  // AI-generated START - 构造函数
  const NewMemoPopup({
    super.key,
    this.onSave,
    this.onCancel,
    this.maxLength = 500,
  });
  // AI-generated END - 构造函数

  /// 保存回调，参数为输入的文本内容
  final ValueChanged<String>? onSave;

  /// 取消回调
  final VoidCallback? onCancel;

  /// 最大字符长度（默认500）
  final int maxLength;

  // AI-generated START - 创建状态
  @override
  State<NewMemoPopup> createState() => _NewMemoPopupState();
  // AI-generated END - 创建状态

  // AI-generated START - 显示弹窗静态方法
  /// 显示新建记忆弹窗（底部显示）
  static Future<T?> show<T>({
    required BuildContext context,
    ValueChanged<String>? onSave,
    VoidCallback? onCancel,
    int maxLength = 500,
  }) {
    return showModalBottomSheet<T>(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) {
        final mediaQuery = MediaQuery.of(context);
        final screenHeight = mediaQuery.size.height;
        final keyboardHeight = mediaQuery.viewInsets.bottom;
        final safeAreaTop = mediaQuery.padding.top;
        final safeAreaBottom = mediaQuery.padding.bottom;

        // 估算弹窗内容高度（顶部栏 + 间距 + 输入框 + 间距 + 按钮区域）
        const estimatedPopupHeight = 32.0 + 24.0 + NewMemoPopup.kInputFieldHeight + 24.0 + 80.0;
        const topMargin = 16.0;

        // 计算可用高度（屏幕高度 - 安全区域 - 顶部边距）
        final availableHeight = screenHeight - safeAreaTop - safeAreaBottom - topMargin;

        // 如果弹窗高度 + 键盘高度超过可用高度，则固定在距离顶部16px
        final shouldPinToTop = (estimatedPopupHeight + keyboardHeight) > availableHeight;

        // 计算弹窗最大高度（考虑键盘）
        final maxPopupHeight =
            shouldPinToTop ? availableHeight : screenHeight - safeAreaTop - safeAreaBottom - keyboardHeight;

        return Padding(
          padding: EdgeInsets.only(
            top: shouldPinToTop ? topMargin : 0,
            bottom: shouldPinToTop ? 0 : keyboardHeight,
          ),
          child: GestureDetector(
            onTap: () {}, // 阻止事件冒泡
            child: Container(
              constraints: BoxConstraints(
                maxHeight: maxPopupHeight,
              ),
              decoration: const BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(20.0),
                  topRight: Radius.circular(20.0),
                ),
              ),
              child: SafeArea(
                child: SingleChildScrollView(
                  child: NewMemoPopup(
                    onSave: onSave,
                    onCancel: onCancel ?? () => Navigator.of(context).pop(),
                    maxLength: maxLength,
                  ),
                ),
              ),
            ),
          ),
        );
      },
    );
  }
  // AI-generated END - 显示弹窗静态方法
}

class _NewMemoPopupState extends State<NewMemoPopup> {
  // AI-generated START - 文本编辑控制器
  final TextEditingController _textController = TextEditingController();
  // AI-generated END - 文本编辑控制器

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(20.0),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          // 顶部：关闭按钮和New Memo按钮
          _buildTopBar(),
          const SizedBox(height: 24.0),
          const Divider(
            color: Color(0xFFE5E7EB),
            height: 1.0,
          ),
          // 输入框
          Flexible(
            child: _buildInputField(),
          ),
          const SizedBox(height: 24.0),
          // 保存按钮和字符计数
          _buildBottomSection(),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建顶部栏
  /// 构建顶部栏：关闭按钮和New Memo按钮
  Widget _buildTopBar() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        // 关闭按钮
        GestureDetector(
          onTap: () {
            if (widget.onCancel != null) {
              widget.onCancel!();
            } else {
              Navigator.of(context).pop();
            }
          },
          child: Container(
            width: 40.0,
            height: 40.0,
            decoration: const BoxDecoration(
              color: Color(0xFFF3F4F6),
              shape: BoxShape.circle,
            ),
            child: const Icon(
              Icons.close,
              size: 20.0,
              color: Color(0xFF374151),
            ),
          ),
        ),
        // New Memo按钮
        GestureDetector(
          onTap: () {
            // TODO: 实现New Memo功能
          },
          child: Container(
            width: 116.0,
            height: 38.0,
            decoration: BoxDecoration(
              color: const Color(0xFFF3F4F6),
              borderRadius: BorderRadius.circular(19.0),
            ),
            child: const Center(
              child: Text(
                'New Memo',
                style: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.w500,
                  color: Color(0xFF374151),
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建顶部栏

  // AI-generated START - 构建输入框
  /// 构建输入框
  Widget _buildInputField() {
    return SizedBox(
      height: NewMemoPopup.kInputFieldHeight,
      child: TextField(
        controller: _textController,
        maxLength: widget.maxLength,
        maxLines: null,
        textAlignVertical: TextAlignVertical.top,
        cursorColor: Color(0xFF1F2937),
        decoration: const InputDecoration(
          hintText: 'I have a very good idea',
          hintStyle: TextStyle(
            fontSize: 16.0,
            color: Color(0xFF9CA3AF),
          ),
          border: InputBorder.none,
          contentPadding: EdgeInsets.all(16.0),
          counterText: '',
        ),
        style: const TextStyle(
          fontSize: 16.0,
          color: Color(0xFF374151),
        ),
        onChanged: (value) {
          setState(() {});
        },
      ),
    );
  }
  // AI-generated END - 构建输入框

  // AI-generated START - 构建底部区域
  /// 构建底部区域：保存按钮和字符计数
  Widget _buildBottomSection() {
    final currentLength = _textController.text.length;
    final maxLength = widget.maxLength;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        // 保存按钮
        ElevatedButton(
          onPressed: () {
            if (_textController.text.isEmpty) {
              MPToastUtils.showMessage('Please enter a memo');
              return;
            }
            if (widget.onSave != null) {
              widget.onSave!(_textController.text);
            }
            Navigator.of(context).pop();
          },
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF9333EA), // 紫色
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(vertical: 16.0),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(16.0),
            ),
            elevation: 0,
          ),
          child: const Text(
            'Save Memory',
            style: TextStyle(
              fontSize: 16.0,
              fontWeight: FontWeight.w600,
            ),
          ),
        ),
        const SizedBox(height: 12.0),
        // 字符计数
        Text(
          '$currentLength/$maxLength',
          textAlign: TextAlign.center,
          style: const TextStyle(
            fontSize: 14.0,
            color: Color(0xFF6B7280),
          ),
        ),
        const SizedBox(height: 12.0),
      ],
    );
  }
  // AI-generated END - 构建底部区域

  // AI-generated START - 清理资源
  @override
  void dispose() {
    _textController.dispose();
    super.dispose();
  }
  // AI-generated END - 清理资源
}
// AI-generated END - new_memo_popup.dart
