// AI-generated START - 新建记忆弹窗组件 - Generated by AI
import 'package:flutter/material.dart';

/// 新建记忆弹窗组件
/// 用于创建新的记忆/备忘录
class NewMemoPopup extends StatefulWidget {
  // AI-generated START - 输入框高度常量
  static const double kInputFieldHeight = 200.0;
  // AI-generated END - 输入框高度常量

  // AI-generated START - 构造函数
  const NewMemoPopup({
    super.key,
    this.onSave,
    this.onCancel,
    this.maxLength = 500,
  });
  // AI-generated END - 构造函数

  /// 保存回调，参数为输入的文本内容
  final ValueChanged<String>? onSave;

  /// 取消回调
  final VoidCallback? onCancel;

  /// 最大字符长度（默认500）
  final int maxLength;

  // AI-generated START - 创建状态
  @override
  State<NewMemoPopup> createState() => _NewMemoPopupState();
  // AI-generated END - 创建状态

  // AI-generated START - 显示弹窗静态方法
  /// 显示新建记忆弹窗（底部显示）
  static Future<T?> show<T>({
    required BuildContext context,
    ValueChanged<String>? onSave,
    VoidCallback? onCancel,
    int maxLength = 500,
  }) {
    return showModalBottomSheet<T>(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) {
        final mediaQuery = MediaQuery.of(context);
        final screenHeight = mediaQuery.size.height;
        final keyboardHeight = mediaQuery.viewInsets.bottom;
        final safeAreaTop = mediaQuery.padding.top;
        final safeAreaBottom = mediaQuery.padding.bottom;
        
        // 估算弹窗内容高度（顶部栏 + 间距 + 输入框 + 间距 + 按钮区域）
        const estimatedPopupHeight = 32.0 + 24.0 + NewMemoPopup.kInputFieldHeight + 24.0 + 80.0;
        const topMargin = 16.0;
        
        // 计算可用高度（屏幕高度 - 安全区域 - 顶部边距）
        final availableHeight = screenHeight - safeAreaTop - safeAreaBottom - topMargin;
        
        // 如果弹窗高度 + 键盘高度超过可用高度，则固定在距离顶部16px
        final shouldPinToTop = (estimatedPopupHeight + keyboardHeight) > availableHeight;
        
        // 计算弹窗最大高度（考虑键盘）
        final maxPopupHeight = shouldPinToTop
            ? availableHeight
            : screenHeight - safeAreaTop - safeAreaBottom - keyboardHeight;
        
        return Padding(
          padding: EdgeInsets.only(
            top: shouldPinToTop ? topMargin : 0,
            bottom: shouldPinToTop ? 0 : keyboardHeight,
          ),
          child: GestureDetector(
            onTap: () {}, // 阻止事件冒泡
            child: Container(
              constraints: BoxConstraints(
                maxHeight: maxPopupHeight,
              ),
              decoration: const BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(20.0),
                  topRight: Radius.circular(20.0),
                ),
              ),
              child: SafeArea(
                child: SingleChildScrollView(
                  child: NewMemoPopup(
                    onSave: onSave,
                    onCancel: onCancel ?? () => Navigator.of(context).pop(),
                    maxLength: maxLength,
                  ),
                ),
              ),
            ),
          ),
        );
      },
    );
  }
  // AI-generated END - 显示弹窗静态方法
}

class _NewMemoPopupState extends State<NewMemoPopup> {
  // AI-generated START - 文本编辑控制器
  final TextEditingController _textController = TextEditingController();
  // AI-generated END - 文本编辑控制器

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(20.0),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          // 顶部：关闭按钮和New Memo按钮
          _buildTopBar(),
          const SizedBox(height: 24.0),
          // 输入框
          Flexible(
            child: _buildInputField(),
          ),
          const SizedBox(height: 24.0),
          // 保存按钮和字符计数
          _buildBottomSection(),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建顶部栏
  /// 构建顶部栏：关闭按钮和New Memo按钮
  Widget _buildTopBar() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        // 关闭按钮
        GestureDetector(
          onTap: () {
            if (widget.onCancel != null) {
              widget.onCancel!();
            } else {
              Navigator.of(context).pop();
            }
          },
          child: Container(
            width: 32.0,
            height: 32.0,
            decoration: BoxDecoration(
              color: Colors.grey[200],
              shape: BoxShape.circle,
            ),
            child: const Icon(
              Icons.close,
              size: 20.0,
              color: Color(0xFF212121),
            ),
          ),
        ),
        // New Memo按钮
        GestureDetector(
          onTap: () {
            // TODO: 实现New Memo功能
          },
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
            decoration: BoxDecoration(
              color: Colors.grey[200],
              borderRadius: BorderRadius.circular(8.0),
            ),
            child: const Text(
              'New Memo',
              style: TextStyle(
                fontSize: 14.0,
                fontWeight: FontWeight.w500,
                color: Color(0xFF212121),
              ),
            ),
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建顶部栏

  // AI-generated START - 构建输入框
  /// 构建输入框
  Widget _buildInputField() {
    return Container(
      height: NewMemoPopup.kInputFieldHeight,
      decoration: BoxDecoration(
        color: Colors.grey[50],
        borderRadius: BorderRadius.circular(12.0),
        border: Border.all(
          color: Colors.grey[300]!,
          width: 1.0,
        ),
      ),
      child: TextField(
        controller: _textController,
        maxLength: widget.maxLength,
        maxLines: null,
        textAlignVertical: TextAlignVertical.top,
        decoration: const InputDecoration(
          hintText: 'I have a very good idea',
          hintStyle: TextStyle(
            fontSize: 16.0,
            color: Color(0xFF999999),
          ),
          border: InputBorder.none,
          contentPadding: EdgeInsets.all(16.0),
          counterText: '',
        ),
        style: const TextStyle(
          fontSize: 16.0,
          color: Color(0xFF212121),
        ),
        onChanged: (value) {
          setState(() {});
        },
      ),
    );
  }
  // AI-generated END - 构建输入框

  // AI-generated START - 构建底部区域
  /// 构建底部区域：保存按钮和字符计数
  Widget _buildBottomSection() {
    final currentLength = _textController.text.length;
    final maxLength = widget.maxLength;
    
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        // 保存按钮
        ElevatedButton(
          onPressed: currentLength > 0
              ? () {
                  if (widget.onSave != null) {
                    widget.onSave!(_textController.text);
                  }
                  Navigator.of(context).pop();
                }
              : null,
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF9C27B0), // 紫色
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(vertical: 16.0),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12.0),
            ),
            elevation: 0,
          ),
          child: const Text(
            'Save Memory',
            style: TextStyle(
              fontSize: 16.0,
              fontWeight: FontWeight.w600,
            ),
          ),
        ),
        const SizedBox(height: 8.0),
        // 字符计数
        Text(
          '$currentLength/$maxLength',
          textAlign: TextAlign.center,
          style: TextStyle(
            fontSize: 12.0,
            color: Colors.grey[500],
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建底部区域

  // AI-generated START - 清理资源
  @override
  void dispose() {
    _textController.dispose();
    super.dispose();
  }
  // AI-generated END - 清理资源
}
// AI-generated END - new_memo_popup.dart

