// AI-generated START - 录音选项卡片组件 - Generated by AI

import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';

/// 录音选项卡片组件
/// 用于显示开始录音和导入音频的选项
class RecordAudioOptionCard extends StatelessWidget {
  // AI-generated START - 图片资源路径常量
  static final String kStartRecordingIcon = Assets.images.mpStartRecordingIcon.path;
  static final String kImportAudioIcon = Assets.images.mpImportAudioIcon.path;
  static final String kCloseIcon = Assets.images.mpImportAudioClose.path;
  final bool autoClose;

  // AI-generated END - 图片资源路径常量
  // AI-generated START - 构造函数
  const RecordAudioOptionCard({
    super.key,
    this.onStartRecording,
    this.onImportAudio,
    this.onClose,
    this.autoClose = true,
  });
  // AI-generated END - 构造函数

  /// 开始录音回调
  final VoidCallback? onStartRecording;

  /// 导入音频回调
  final VoidCallback? onImportAudio;

  /// 关闭回调
  final VoidCallback? onClose;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 16.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16.0),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.1),
            blurRadius: 10.0,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Padding(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // 开始录音按钮
            _buildOptionButton(
              icon: Icons.mic,
              iconColor: Colors.red,
              backgroundColor: Colors.red[50]!,
              title: '开始录音',
              imagePath: kStartRecordingIcon,
              onTap: () {
                if (autoClose) {
                  _close(context);
                }
                onStartRecording?.call();
              },
            ),
            const SizedBox(height: 16.0),
            // 导入音频按钮
            _buildOptionButton(
              icon: Icons.upload_file,
              iconColor: Colors.blue,
              backgroundColor: Colors.blue[50]!,
              title: '导入音频',
              imagePath: kImportAudioIcon,
              onTap: (){
                if (autoClose) {
                  _close(context);
                }
                onImportAudio?.call();
              },
            ),
            const SizedBox(height: 24.0),
            // 关闭按钮
            _buildCloseButton(context),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建选项按钮
  /// 构建选项按钮
  Widget _buildOptionButton({
    required IconData icon,
    required Color iconColor,
    required Color backgroundColor,
    required String title,
    required String imagePath,
    VoidCallback? onTap,
  }) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 16.0),
        decoration: BoxDecoration(
          color: backgroundColor,
          borderRadius: BorderRadius.circular(12.0),
        ),
        child: Row(
          children: [
            // 图标/图片
            Image.asset(imagePath, width: 40.0, height: 40.0, fit: BoxFit.cover),
            const SizedBox(width: 16.0),
            // 标题
            Expanded(
              child: Text(
                title,
                style: const TextStyle(
                  fontSize: 16.0,
                  fontWeight: FontWeight.w500,
                  color: Color(0xFF212121),
                ),
              ),
            ),
            // 右箭头
            Image.asset(Assets.images.settingRightArrow2.path, width: 20.0, height: 20.0, fit: BoxFit.cover),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建选项按钮

  // AI-generated START - 构建关闭按钮
  /// 构建关闭按钮
  Widget _buildCloseButton(BuildContext context) {
    return GestureDetector(
      onTap: () {
        _close(context);
      },
      child: Image.asset(kCloseIcon, width: 20.0, height: 20.0, fit: BoxFit.cover),
    );
  }
  // AI-generated END - 构建关闭按钮

  void _close(BuildContext context) {
if (onClose != null) {
          onClose!();
        } else {
          Navigator.of(context).pop();
        }
  }

  // AI-generated START - 显示弹窗静态方法
  /// 显示录音选项弹窗
  static Future<T?> show<T>({
    required BuildContext context,
    VoidCallback? onStartRecording,
    VoidCallback? onImportAudio,
    VoidCallback? onClose,
  }) {
    return showDialog<T>(
      context: context,
      barrierColor: Colors.black54,
      builder: (context) {
        return Dialog(
          backgroundColor: Colors.transparent,
          child: RecordAudioOptionCard(
            onStartRecording: onStartRecording,
            onImportAudio: onImportAudio,
            onClose: onClose ?? () => Navigator.of(context).pop(),
          ),
        );
      },
    );
  }
  // AI-generated END - 显示弹窗静态方法
}
// AI-generated END - record_audio_option_card.dart
