// AI-generated START - 说话人命名弹窗组件 - Generated by AI
import 'package:flutter/material.dart';

/// 说话人条目数据
class SpeakerItem {
  // AI-generated START - 构造函数
  const SpeakerItem({
    required this.id,
    required this.name,
    required this.duration,
    required this.transcript,
  });
  // AI-generated END - 构造函数

  /// 唯一标识
  final String id;

  /// 初始名称
  final String name;

  /// 时长文本（如 3m 38s）
  final String duration;

  /// 文本内容
  final String transcript;
}

/// 说话人命名弹窗组件
class SpeakerNamingPopup extends StatefulWidget {
  // AI-generated START - 构造函数
  const SpeakerNamingPopup({
    super.key,
    required this.items,
    this.onNameChanged,
    this.onConfirm,
    this.onCancel,
  });
  // AI-generated END - 构造函数

  /// 说话人列表
  final List<SpeakerItem> items;

  /// 名称修改回调：返回 id 和新名称
  final void Function(String id, String name)? onNameChanged;

  /// 确认回调：返回所有修改后的名称映射
  final void Function(Map<String, String> names)? onConfirm;

  /// 取消回调
  final VoidCallback? onCancel;

  // AI-generated START - 创建状态
  @override
  State<SpeakerNamingPopup> createState() => _SpeakerNamingPopupState();
  // AI-generated END - 创建状态

  // AI-generated START - 显示弹窗静态方法
  static Future<T?> show<T>({
    required BuildContext context,
    required List<SpeakerItem> items,
    void Function(String id, String name)? onNameChanged,
    void Function(Map<String, String> names)? onConfirm,
    VoidCallback? onCancel,
  }) {
    return showDialog<T>(
      context: context,
      barrierColor: Colors.black54,
      builder: (context) {
        return Dialog(
          backgroundColor: Colors.transparent,
          child: SpeakerNamingPopup(
            items: items,
            onNameChanged: onNameChanged,
            onConfirm: onConfirm,
            onCancel: onCancel ?? () => Navigator.of(context).pop(),
          ),
        );
      },
    );
  }
  // AI-generated END - 显示弹窗静态方法
}

class _SpeakerNamingPopupState extends State<SpeakerNamingPopup> {
  // AI-generated START - 名称控制器
  late final Map<String, TextEditingController> _nameControllers;
  // AI-generated END - 名称控制器

  // AI-generated START - 初始化
  @override
  void initState() {
    super.initState();
    _nameControllers = {
      for (final item in widget.items)
        item.id: TextEditingController(text: item.name),
    };
  }
  // AI-generated END - 初始化

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 24.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16.0),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 10.0,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          _buildHeader(context),
          const Divider(height: 1.0, color: Color(0xFFF0F0F0)),
          Flexible(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                children: widget.items.map((item) => _buildItemCard(item)).toList(),
              ),
            ),
          ),
          const Divider(height: 1.0, color: Color(0xFFF0F0F0)),
          _buildFooter(context),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建头部
  Widget _buildHeader(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 12.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          const Text(
            '为说话人命名',
            style: TextStyle(
              fontSize: 18.0,
              fontWeight: FontWeight.w600,
              color: Color(0xFF212121),
            ),
          ),
          GestureDetector(
            onTap: () {
              if (widget.onCancel != null) {
                widget.onCancel!();
              } else {
                Navigator.of(context).pop();
              }
            },
            child: Container(
              width: 32.0,
              height: 32.0,
              decoration: BoxDecoration(
                color: Colors.grey[200],
                shape: BoxShape.circle,
              ),
              child: const Icon(
                Icons.close,
                size: 18.0,
                color: Color(0xFF212121),
              ),
            ),
          ),
        ],
      ),
    );
  }
  // AI-generated END - 构建头部

  // AI-generated START - 构建条目卡片
  Widget _buildItemCard(SpeakerItem item) {
    final controller = _nameControllers[item.id]!;
    return Container(
      margin: const EdgeInsets.only(bottom: 12.0),
      padding: const EdgeInsets.all(12.0),
      decoration: BoxDecoration(
        color: const Color(0xFFF7F7F7),
        borderRadius: BorderRadius.circular(12.0),
        border: Border.all(color: const Color(0xFFE6E6E6)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              const Icon(Icons.play_arrow, size: 16.0, color: Color(0xFF8C8C8C)),
              const SizedBox(width: 6.0),
              Text(
                item.duration,
                style: const TextStyle(
                  fontSize: 12.0,
                  color: Color(0xFF8C8C8C),
                ),
              ),
              const Spacer(),
              const Text(
                '41s',
                style: TextStyle(
                  fontSize: 12.0,
                  color: Color(0xFF8C8C8C),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8.0),
          TextField(
            controller: controller,
            decoration: InputDecoration(
              isDense: true,
              contentPadding: const EdgeInsets.symmetric(horizontal: 12.0, vertical: 10.0),
              filled: true,
              fillColor: Colors.white,
              hintText: 'Speaker',
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8.0),
                borderSide: const BorderSide(color: Color(0xFFE6E6E6)),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8.0),
                borderSide: const BorderSide(color: Color(0xFFE6E6E6)),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8.0),
                borderSide: const BorderSide(color: Color(0xFF4D8DFF)),
              ),
            ),
            style: const TextStyle(
              fontSize: 14.0,
              color: Color(0xFF212121),
            ),
            onChanged: (value) {
              if (widget.onNameChanged != null) {
                widget.onNameChanged!(item.id, value);
              }
            },
          ),
          const SizedBox(height: 8.0),
          Text(
            item.transcript,
            style: const TextStyle(
              fontSize: 14.0,
              color: Color(0xFF4B4B4B),
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }
  // AI-generated END - 构建条目卡片

  // AI-generated START - 构建底部操作
  Widget _buildFooter(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 12.0),
      child: Row(
        children: [
          Expanded(
            child: OutlinedButton(
              onPressed: () {
                if (widget.onCancel != null) {
                  widget.onCancel!();
                } else {
                  Navigator.of(context).pop();
                }
              },
              style: OutlinedButton.styleFrom(
                side: const BorderSide(color: Color(0xFFE6E6E6)),
                foregroundColor: const Color(0xFF4B4B4B),
                padding: const EdgeInsets.symmetric(vertical: 14.0),
              ),
              child: const Text('取消', style: TextStyle(fontSize: 16.0)),
            ),
          ),
          const SizedBox(width: 12.0),
          Expanded(
            child: ElevatedButton(
              onPressed: () {
                if (widget.onConfirm != null) {
                  final names = <String, String>{};
                  for (final entry in _nameControllers.entries) {
                    names[entry.key] = entry.value.text.trim();
                  }
                    widget.onConfirm!(names);
                }
                Navigator.of(context).pop();
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF1E81FF),
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 14.0),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8.0),
                ),
                elevation: 0,
              ),
              child: const Text('确认', style: TextStyle(fontSize: 16.0, fontWeight: FontWeight.w600)),
            ),
          ),
        ],
      ),
    );
  }
  // AI-generated END - 构建底部操作

  // AI-generated START - 清理资源
  @override
  void dispose() {
    for (final controller in _nameControllers.values) {
      controller.dispose();
    }
    super.dispose();
  }
  // AI-generated END - 清理资源
}
// AI-generated END - 说话人命名弹窗组件

