// AI-generated START - 说话人命名弹窗组件 - Generated by AI
import 'package:flutter/material.dart';

import '../../backend/http/mp_api/mp_speaker.dart';
import '../../backend/schema/mp/mp_data_model.dart';
import '../../backend/schema/mp/mp_speaker.dart';

class SpeakerNamingItemModel {
  final String name;
  int duration;
  List<MPSummaryConversationStruct> items;

  SpeakerNamingItemModel({
    required this.name,
    this.items = const [],
    this.duration = 0,
  });
}

/// 说话人命名弹窗组件
// ignore: must_be_immutable
class SpeakerNamingPopup extends StatefulWidget {
  // AI-generated START - 构造函数
  SpeakerNamingPopup({
    super.key,
    required this.memoryId,
    required this.items,
    this.confirmSucc,
    this.onCancel,
  });
  // AI-generated END - 构造函数

  /// 说话人列表
  final List<MPSummaryConversationStruct> items;

  /// 确认回调：返回所有修改后的名称映射
  VoidCallback? confirmSucc;

  final String memoryId;

  /// 取消回调
  final VoidCallback? onCancel;

  // AI-generated START - 创建状态
  @override
  State<SpeakerNamingPopup> createState() => _SpeakerNamingPopupState();
  // AI-generated END - 创建状态

  // AI-generated START - 显示弹窗静态方法
  static Future<T?> show<T>({
    required BuildContext context,
    required List<MPSummaryConversationStruct> items,
    void Function(String id, String name)? onNameChanged,
    VoidCallback? onfirm,
    VoidCallback? onCancel,
    required String memeryId,
  }) {
    return showDialog<T>(
      context: context,
      barrierColor: Colors.black54,
      builder: (context) {
        return Dialog(
          backgroundColor: Colors.transparent,
          insetPadding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 24),
          child: SpeakerNamingPopup(
            items: items,
            confirmSucc: onfirm,
            onCancel: onCancel ?? () => Navigator.of(context).pop(),
            memoryId: memeryId,
          ),
        );
      },
    );
  }
  // AI-generated END - 显示弹窗静态方法
}

class _SpeakerNamingPopupState extends State<SpeakerNamingPopup> {
  // AI-generated START - 名称控制器
  final Map<String, TextEditingController> _nameControllers = {};
  // AI-generated END - 名称控制器

  Map<String, SpeakerNamingItemModel> _itemModels = {};

  // AI-generated START - 初始化
  @override
  void initState() {
    super.initState();

    for (final item in widget.items) {
      final name = item.speaker.name;
      if (_itemModels.containsKey(name)) {
        _itemModels[name]!.duration += item.speaker.duration ?? 0;
        _itemModels[name]!.items.add(item);
      } else {
        _itemModels[name] = SpeakerNamingItemModel(name: name, items: [item], duration: item.speaker.duration ?? 0);
        _nameControllers[name] = TextEditingController(text: item.speaker.name);
      }
    }
  }
  // AI-generated END - 初始化

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16.0),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.1),
            blurRadius: 10.0,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          _buildHeader(context),
          const Divider(height: 1.0, color: Color(0xFFF0F0F0)),
          Flexible(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                children: _itemModels.values.map((model) => _buildItemCard(model)).toList(),
              ),
            ),
          ),
          const Divider(height: 1.0, color: Color(0xFFF0F0F0)),
          _buildFooter(context),
          const Text('本文件中的说话人名称将自动更新', style: TextStyle(fontSize: 12.0, color: Color(0xFF8C8C8C))),
          const SizedBox(height: 16.0),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建头部
  Widget _buildHeader(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 12.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          const Text(
            '为说话人命名',
            style: TextStyle(
              fontSize: 18.0,
              fontWeight: FontWeight.w600,
              color: Color(0xFF212121),
            ),
          ),
          GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: () {
              if (widget.onCancel != null) {
                widget.onCancel!();
              } else {
                Navigator.of(context).pop();
              }
            },
            child: const SizedBox(
              width: 32.0,
              height: 32.0,
              child: Icon(
                Icons.close,
                size: 18.0,
                color: Color(0xFF212121),
              ),
            ),
          ),
        ],
      ),
    );
  }
  // AI-generated END - 构建头部

  // AI-generated START - 构建条目卡片
  Widget _buildItemCard(SpeakerNamingItemModel model) {
    final controller = _nameControllers[model.name]!;
    return Container(
      margin: const EdgeInsets.only(bottom: 12.0),
      padding: const EdgeInsets.all(12.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12.0),
        border: Border.all(color: const Color(0xFFE6E6E6)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // 名称输入框
          TextField(
            controller: controller,
            decoration: InputDecoration(
              isDense: true,
              contentPadding: const EdgeInsets.symmetric(horizontal: 12.0, vertical: 10.0),
              filled: true,
              fillColor: Colors.white,
              hintText: 'Speaker',
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8.0),
                borderSide: const BorderSide(color: Color(0xFFE6E6E6)),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8.0),
                borderSide: const BorderSide(color: Color(0xFFE6E6E6)),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8.0),
                borderSide: const BorderSide(color: Color(0xFF4D8DFF)),
              ),
            ),
            style: const TextStyle(
              fontSize: 14.0,
              color: Color(0xFF212121),
            ),
            onChanged: (value) {},
          ),
          const SizedBox(height: 8.0),
          // 总时长
          Text(
            _formatDuration(model.duration),
            style: const TextStyle(
              fontSize: 12.0,
              color: Color(0xFF8C8C8C),
            ),
          ),
          const SizedBox(height: 12.0),
          // 转录片段列表
          ...model.items.map((item) => _buildSegmentItem(item)),
        ],
      ),
    );
  }
  // AI-generated END - 构建条目卡片

  /// 构建单个转录片段
  Widget _buildSegmentItem(MPSummaryConversationStruct item) {
    // 从时间戳字符串中解析时长，格式：00:00:00 - 00:00:24
    final segmentDuration = _parseDurationFromTime(item.time);

    return Padding(
      padding: const EdgeInsets.only(bottom: 12.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              const Icon(Icons.play_arrow, size: 16.0, color: Color(0xFF212121)),
              const SizedBox(width: 6.0),
              Expanded(
                child: Text(
                  item.time,
                  style: const TextStyle(
                    fontSize: 12.0,
                    color: Color(0xFF8C8C8C),
                  ),
                ),
              ),
              Text(
                '${segmentDuration}s',
                style: const TextStyle(
                  fontSize: 12.0,
                  color: Color(0xFF8C8C8C),
                ),
              ),
            ],
          ),
          const SizedBox(height: 6.0),
          Text(
            item.content,
            maxLines: 3,
            overflow: TextOverflow.ellipsis,
            style: const TextStyle(
              fontSize: 14.0,
              color: Color(0xFF4B4B4B),
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }

  /// 从时间戳字符串中解析时长（秒数）
  /// 时间戳格式：00:00:00 - 00:00:24
  int _parseDurationFromTime(String timeStr) {
    try {
      final parts = timeStr.split(' - ');
      if (parts.length != 2) return 0;

      final startTime = _parseTimeToSeconds(parts[0]);
      final endTime = _parseTimeToSeconds(parts[1]);

      return endTime - startTime;
    } catch (e) {
      return 0;
    }
  }

  /// 将时间字符串（HH:MM:SS）转换为秒数
  int _parseTimeToSeconds(String timeStr) {
    try {
      final parts = timeStr.split(':');
      if (parts.length != 3) return 0;

      final hours = int.parse(parts[0]);
      final minutes = int.parse(parts[1]);
      final seconds = int.parse(parts[2]);

      return hours * 3600 + minutes * 60 + seconds;
    } catch (e) {
      return 0;
    }
  }

  /// 格式化时长：将秒数转换为 "总时长 Xm Ys" 格式
  String _formatDuration(int seconds) {
    if (seconds < 60) {
      return '总时长 ${seconds}s';
    }
    final minutes = seconds ~/ 60;
    final remainingSeconds = seconds % 60;
    if (remainingSeconds == 0) {
      return '总时长 ${minutes}m';
    }
    return '总时长 ${minutes}m ${remainingSeconds}s';
  }

  // AI-generated START - 构建底部操作
  Widget _buildFooter(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 12.0),
      child: Row(
        children: [
          Expanded(
            child: OutlinedButton(
              onPressed: () {
                if (widget.onCancel != null) {
                  widget.onCancel!();
                } else {
                  Navigator.of(context).pop();
                }
              },
              style: OutlinedButton.styleFrom(
                side: const BorderSide(color: Color(0xFFE6E6E6)),
                foregroundColor: const Color(0xFF4B4B4B),
                padding: const EdgeInsets.symmetric(vertical: 14.0),
              ),
              child: const Text('取消', style: TextStyle(fontSize: 16.0)),
            ),
          ),
          const SizedBox(width: 12.0),
          Expanded(
            child: ElevatedButton(
              onPressed: () async {
                await _updateSpeakName();
                Navigator.of(context).pop();
                if (widget.confirmSucc != null) {
                  widget.confirmSucc!();
                }
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.black,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 14.0),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8.0),
                ),
                elevation: 0,
              ),
              child: const Text('确认', style: TextStyle(fontSize: 16.0, fontWeight: FontWeight.w600)),
            ),
          ),
        ],
      ),
    );
  }
  // AI-generated END - 构建底部操作

  // AI-generated START - 清理资源
  @override
  void dispose() {
    for (final controller in _nameControllers.values) {
      controller.dispose();
    }
    super.dispose();
  }
  // AI-generated END - 清理资源

  /// 更新说话人名称
  /// 遍历所有item，比较原始名称与输入框中的名称，如果不一致则发起更新请求
  /// 使用 Future.wait 并发执行所有更新请求
  Future<void> _updateSpeakName() async {
    // 收集需要更新的请求列表
    final List<Future<MPMarkSpeakerResponse?>> updateFutures = [];

    // 遍历所有itemModel
    for (final model in _itemModels.values) {
      // 通过model.id从_nameControllers中获取controller
      final controller = _nameControllers[model.name];
      if (controller == null) continue;

      // 比较model.name与controller文本是否一致
      final newName = controller.text.trim();
      if (model.name != newName && newName.isNotEmpty) {
        // 如果不一致，创建更新请求并添加到列表
        // 使用第一个item的speaker.id作为speakerId
        if (model.items.isNotEmpty) {
          final request = MPMarkSpeakerRequest(
            memoryId: widget.memoryId,
            name: newName,
            templateSpeakerName: model.name,
            avatar: '',
          );
          updateFutures.add(markSpeaker(request));
        }
      }
    }

    // 判断需要发起的请求list是否为空
    if (updateFutures.isEmpty) {
      // 为空直接return
      return;
    }

    // 不为空，等待所有请求执行完成
    await Future.wait(updateFutures);
  }
}
// AI-generated END - 说话人命名弹窗组件
