// AI-generated START - 录制声纹卡片组件 - Generated by AI
import 'package:flutter/material.dart';

/// 录制声纹卡片组件
/// 显示录制新声纹的按钮和说明文字
class RecordVoiceprintCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const RecordVoiceprintCard({
    super.key,
    this.onRecordTap,
    this.hintText = '您也可以到具体的记忆卡片里面去标记某个人的声音',
  });
  // AI-generated END - 构造函数

  /// 录制按钮点击回调
  final VoidCallback? onRecordTap;

  /// 提示文字
  final String hintText;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      child: Column(
        children: [
          // 录制按钮
          _buildRecordButton(),
          const SizedBox(height: 12.0),
          // 提示文字
          _buildHintText(),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建录制按钮
  Widget _buildRecordButton() {
    return SizedBox(
      width: double.infinity,
      child: ElevatedButton.icon(
        onPressed: onRecordTap,
        icon: const Icon(
          Icons.mic_off,
          color: Colors.white,
          size: 24.0,
        ),
        label: const Text(
          '录制新的声纹',
          style: TextStyle(
            fontSize: 16.0,
            fontWeight: FontWeight.w500,
            color: Colors.white,
          ),
        ),
        style: ElevatedButton.styleFrom(
          padding: const EdgeInsets.symmetric(vertical: 16.0),
          backgroundColor: const Color(0xFF7B68EE), // 紫色-蓝色
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.0),
          ),
        ),
      ),
    );
  }
  // AI-generated END - 构建录制按钮

  // AI-generated START - 构建提示文字
  Widget _buildHintText() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16.0),
      child: Text(
        hintText,
        textAlign: TextAlign.center,
        style: TextStyle(
          fontSize: 14.0,
          color: Colors.grey[600],
        ),
      ),
    );
  }
  // AI-generated END - 构建提示文字
}
// AI-generated END - record_voiceprint_card.dart

