// AI-generated START - 已保存的声音卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/newsetting/voice_recognition/widgets/my_voice_card.dart';
import 'package:omi/pages/newsetting/voice_recognition/widgets/voice_item_card.dart';

/// 已保存的声音卡片组件
/// 显示已保存的声音列表，每个项都有删除操作
class SavedVoicesCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const SavedVoicesCard({
    super.key,
    required this.items,
  });
  // AI-generated END - 构造函数

  /// 声音数据项列表
  final List<MyVoiceItem> items;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    if (items.isEmpty) {
      return const SizedBox.shrink();
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // 标题（在外面，没有圆角）
        _buildHeader(),
        // 显示多个 item，每个 item 都是独立的圆角卡片，默认使用删除操作
        ...items.map((item) => VoiceItemCard(
              item: item,
              actionType: item.actionType ?? VoiceItemActionType.delete, // 默认使用删除操作
            )),
      ],
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建标题
  Widget _buildHeader() {
    return Padding(
      padding: const EdgeInsets.fromLTRB(16.0, 8.0, 16.0, 8.0),
      child: Text(
        '已保存的声音',
        style: const TextStyle(
          fontSize: 18.0,
          fontWeight: FontWeight.w600,
          color: Color(0xFF212121),
        ),
      ),
    );
  }
  // AI-generated END - 构建标题
}
// AI-generated END - saved_voices_card.dart
