// AI-generated START - 个人中心状态管理Provider - Generated by AI
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:omi/backend/http/mp_api/mp_user.dart';
import 'package:omi/backend/schema/mp/mp_user.dart';

/// 用户资料数据模型
class UserProfile {
  // AI-generated START - 构造函数
  const UserProfile({
    required this.name,
    required this.email,
    this.avatarUrl,
    this.avatarSize = 80.0,
  });
  // AI-generated END - 构造函数

  /// 用户姓名
  final String name;

  /// 用户邮箱
  final String email;

  /// 头像URL
  final String? avatarUrl;

  /// 头像大小
  final double avatarSize;
}

/// 个人中心状态管理Provider
/// 管理用户个人信息数据
class PersonalProvider with ChangeNotifier {
  // AI-generated START - 用户姓名
  String _name = '';
  // AI-generated END - 用户姓名

  // AI-generated START - 用户邮箱
  String _email = '';
  // AI-generated END - 用户邮箱

  // AI-generated START - 头像URL
  String? _avatarUrl;
  // AI-generated END - 头像URL

  // AI-generated START - 头像大小
  double _avatarSize = 80.0;
  // AI-generated END - 头像大小

  // AI-generated START - 是否正在加载
  bool _isLoading = false;
  // AI-generated END - _isLoading

  // AI-generated START - 错误信息
  String? _error;
  // AI-generated END - _error

  // AI-generated START - 获取用户姓名
  String get name => _name;
  // AI-generated END - 获取用户姓名

  // AI-generated START - 获取用户邮箱
  String get email => _email;
  // AI-generated END - 获取用户邮箱

  // AI-generated START - 获取头像URL
  String? get avatarUrl => _avatarUrl;
  // AI-generated END - 获取头像URL

  // AI-generated START - 获取是否正在加载
  bool get isLoading => _isLoading;
  // AI-generated END - isLoading

  // AI-generated START - 获取错误信息
  String? get error => _error;
  // AI-generated END - error

  // AI-generated START - 更新用户姓名
  void updateName(String name) {
    _name = name;
    notifyListeners();
  }
  // AI-generated END - 更新用户姓名

  // AI-generated START - 更新用户邮箱
  void updateEmail(String email) {
    _email = email;
    notifyListeners();
  }
  // AI-generated END - 更新用户邮箱

  // AI-generated START - 更新头像URL
  void updateAvatarUrl(String? avatarUrl) {
    _avatarUrl = avatarUrl;
    notifyListeners();
  }
  // AI-generated END - 更新头像URL

  // AI-generated START - 更新头像大小
  void updateAvatarSize(double avatarSize) {
    _avatarSize = avatarSize;
    notifyListeners();
  }
  // AI-generated END - 更新头像大小

  // AI-generated START - 更新用户资料（部分更新）
  void updateProfile({
    String? name,
    String? email,
    String? avatarUrl,
    double? avatarSize,
  }) {
    if (name != null) _name = name;
    if (email != null) _email = email;
    if (avatarUrl != null) _avatarUrl = avatarUrl;
    if (avatarSize != null) _avatarSize = avatarSize;
    notifyListeners();
  }
  // AI-generated END - 更新用户资料（部分更新）

  // AI-generated START - 一次性设置所有用户资料（从API或数据源同时返回）
  void setProfile(UserProfile profile) {
    _name = profile.name;
    _email = profile.email;
    _avatarUrl = profile.avatarUrl;
    _avatarSize = profile.avatarSize;
    notifyListeners();
  }
  // AI-generated END - 一次性设置所有用户资料

  // AI-generated START - 获取完整的用户资料
  UserProfile get profile => UserProfile(
        name: _name,
        email: _email,
        avatarUrl: _avatarUrl,
        avatarSize: _avatarSize,
      );
  // AI-generated END - 获取完整的用户资料

  // AI-generated START - 从API加载用户资料
  Future<void> loadUserProfile() async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      final request = MPGetUserProfileRequest();
      final response = await getUserProfile(request);

      if (response != null) {
        if (response.baseResp.code == 0) {
          // 将 API 返回的数据映射到本地字段
          _name = response.user.userName;
          _email = response.user.email;
          _avatarUrl = response.user.avatar.isNotEmpty ? response.user.avatar : null;
          _error = null;
          notifyListeners();
        } else {
          _error = response.baseResp.message;
        }
      } else {
        _error = '获取用户资料失败';
      }
    } catch (e) {
      _error = '加载用户资料时出错: $e';
      debugPrint('Error loading user profile: $e');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }
  // AI-generated END - loadUserProfile

  // AI-generated START - 刷新用户资料
  Future<void> refreshUserProfile() async {
    await loadUserProfile();
  }
  // AI-generated END - refreshUserProfile
}
// AI-generated END - personal_provider.dart
