// AI-generated START - 应用集成卡片组件 - Generated by AI
import 'package:flutter/material.dart';

/// 功能标签数据模型
class FeatureTag {
  // AI-generated START - 构造函数
  const FeatureTag({
    required this.label,
  });
  // AI-generated END - 构造函数

  /// 标签文字
  final String label;
}

/// 应用集成卡片组件
/// 显示应用集成信息，支持已连接和未连接状态
class AppIntegrationCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const AppIntegrationCard({
    super.key,
    required this.appName,
    required this.description,
    required this.icon,
    required this.iconColor,
    this.isConnected = false,
    this.features = const [],
    this.onViewDetails,
    this.onConnect,
    this.onDisconnect,
  });
  // AI-generated END - 构造函数

  /// 应用名称
  final String appName;

  /// 描述文字
  final String description;

  /// 应用图标
  final IconData icon;

  /// 图标背景颜色
  final Color iconColor;

  /// 是否已连接
  final bool isConnected;

  /// 功能标签列表
  final List<FeatureTag> features;

  /// 查看详情回调
  final VoidCallback? onViewDetails;

  /// 连接回调
  final VoidCallback? onConnect;

  /// 断开连接回调
  final VoidCallback? onDisconnect;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
        margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
        padding: const EdgeInsets.all(16.0),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16.0),
          border: Border.all(
            color: const Color(0xFFF3F4F6),
            width: 1.0,
          ),
        ),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.start,
          children: [
            _buildHeader(),
            const SizedBox(width: 12.0),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // 头部：图标、名称和连接状态
                  Row(
                    children: [
                      // 应用名称
                      Expanded(
                        child: Text(
                          appName,
                          style: const TextStyle(
                            fontSize: 16.0,
                            fontWeight: FontWeight.w600,
                            color: Color(0xFF1F2937),
                          ),
                        ),
                      ),
                      // 连接状态标签
                      if (isConnected) _buildConnectedTag(),
                    ],
                  ),
                  // 描述文字
                  _buildDescription(),
                  const SizedBox(height: 8.0),
                  // 功能标签
                  if (features.isNotEmpty) _buildFeatures(),
                  const SizedBox(height: 8.0),
                  // 操作按钮
                  _buildActions(),
                ],
              ),
            ),
          ],
        ));
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建头部
  Widget _buildHeader() {
    return Row(
      children: [
        // 应用图标
        Container(
          width: 48.0,
          height: 48.0,
          decoration: BoxDecoration(
            color: iconColor,
            borderRadius: BorderRadius.circular(8.0),
          ),
          child: Icon(
            icon,
            color: Colors.white,
            size: 24.0,
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建头部

  // AI-generated START - 构建连接状态标签
  Widget _buildConnectedTag() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8.0, vertical: 4.0),
      decoration: BoxDecoration(
        color: const Color(0xFFF0FDF4), // 浅绿色
        borderRadius: BorderRadius.circular(20.0),
      ),
      child: const Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(
            Icons.check,
            color: Color(0xFF16A34A),
            size: 12.0,
          ),
          SizedBox(width: 2.0),
          Text(
            '已连接',
            style: TextStyle(
              fontSize: 12.0,
              color: Color(0xFF16A34A),
              fontWeight: FontWeight.normal,
            ),
          ),
        ],
      ),
    );
  }
  // AI-generated END - 构建连接状态标签

  // AI-generated START - 构建描述
  Widget _buildDescription() {
    return Text(
      description,
      style: const TextStyle(
        fontSize: 14.0,
        color: Color(0xFF4B5563),
      ),
    );
  }
  // AI-generated END - 构建描述

  // AI-generated START - 构建功能标签
  Widget _buildFeatures() {
    return Wrap(
      spacing: 6.0,
      runSpacing: 6.0,
      children: features.map((feature) {
        return Container(
          padding: const EdgeInsets.symmetric(horizontal: 10.0, vertical: 6.0),
          decoration: BoxDecoration(
            color: const Color(0xFFF9FAFB),
            borderRadius: BorderRadius.circular(20.0),
          ),
          child: Text(
            feature.label,
            style: const TextStyle(
              fontSize: 12.0,
              color: Color(0xFF6B7280),
            ),
          ),
        );
      }).toList(),
    );
  }
  // AI-generated END - 构建功能标签

  // AI-generated START - 构建操作按钮
  Widget _buildActions() {
    return Row(
      children: [
        // 查看详情按钮
        Expanded(
          child: OutlinedButton(
            onPressed: onViewDetails,
            style: OutlinedButton.styleFrom(
              padding: const EdgeInsets.symmetric(vertical: 12.0),
              side: const BorderSide(color: Color(0xFFE5E7EB), width: 1.0),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12.0),
              ),
            ),
            child: const Text(
              '管理连接',
              style: TextStyle(
                fontSize: 14.0,
                color: Color(0xFF374151),
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ),

        const SizedBox(width: 8.0),
        // 连接/断开连接按钮
        Expanded(
          child: OutlinedButton(
            onPressed: isConnected ? onDisconnect : onConnect,
            style: ElevatedButton.styleFrom(
              padding: const EdgeInsets.symmetric(vertical: 12.0),
              backgroundColor: isConnected ? Colors.white : const Color(0xFF4CAF50), // 绿色（连接）或白色（断开）
              side: BorderSide(
                color: isConnected
                    ? const Color(0xFFFECACA) // 浅红色边框
                    : const Color(0xFF16A34A), // 绿色边框
                width: 1.0,
              ),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12.0),
              ),
            ),
            child: Text(
              isConnected ? '断开连接' : '立即连接',
              style: TextStyle(
                fontSize: 14.0,
                fontWeight: FontWeight.w600,
                color: isConnected
                    ? const Color(0xFFDC2626) // 浅红色文字
                    : Colors.white, // 白色文字
              ),
            ),
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建操作按钮
}
// AI-generated END - app_integration_card.dart
