// AI-generated START - 自动化工作流卡片组件 - Generated by AI
import 'package:flutter/material.dart';

/// 自动化工作流卡片组件
/// 显示自动化工作流信息和统计数据
class AutomationWorkflowCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const AutomationWorkflowCard({
    super.key,
    this.title = '自动化工作流',
    this.subtitle = '连接你喜欢的应用,让工作更高效',
    this.connectedCount = 1,
    this.availableAppsCount = 10,
    this.showAutoSync = true,
    this.onTap,
  });
  // AI-generated END - 构造函数

  /// 标题
  final String title;

  /// 副标题
  final String subtitle;

  /// 已连接数量
  final int connectedCount;

  /// 可用应用数量
  final int availableAppsCount;

  /// 是否显示自动同步
  final bool showAutoSync;

  /// 卡片点击回调
  final VoidCallback? onTap;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          begin: Alignment.centerLeft,
          end: Alignment.centerRight,
          colors: [
            Color(0xFF4CAF50), // 浅绿色
            Color(0xFF388E3C), // 深绿色
          ],
        ),
        borderRadius: BorderRadius.circular(12.0),
      ),
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(12.0),
        child: Padding(
          padding: const EdgeInsets.all(20.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // 顶部：图标和文字
              _buildHeader(),
              const SizedBox(height: 24.0),
              // 底部：统计数据
              _buildStats(),
            ],
          ),
        ),
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建顶部内容
  Widget _buildHeader() {
    return Row(
      children: [
        // 左侧图标
        Container(
          width: 56.0,
          height: 56.0,
          decoration: BoxDecoration(
            color: const Color(0xFF66BB6A), // 浅绿色背景
            borderRadius: BorderRadius.circular(12.0),
          ),
          child: const Icon(
            Icons.apps,
            color: Colors.white,
            size: 28.0,
          ),
        ),
        const SizedBox(width: 16.0),
        // 右侧文字
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                title,
                style: const TextStyle(
                  fontSize: 18.0,
                  fontWeight: FontWeight.w600,
                  color: Colors.white,
                ),
              ),
              const SizedBox(height: 4.0),
              Text(
                subtitle,
                style: TextStyle(
                  fontSize: 14.0,
                  color: Colors.white.withOpacity(0.9),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建顶部内容

  // AI-generated START - 构建统计数据
  Widget _buildStats() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceAround,
      children: [
        // 已连接
        _buildStatItem(
          value: connectedCount.toString(),
          label: '已连接',
        ),
        // 可用应用
        _buildStatItem(
          value: availableAppsCount.toString(),
          label: '可用应用',
        ),
        // 自动同步
        if (showAutoSync)
          _buildStatItem(
            value: '∞',
            label: '自动同步',
          ),
      ],
    );
  }
  // AI-generated END - 构建统计数据

  // AI-generated START - 构建单个统计项
  Widget _buildStatItem({
    required String value,
    required String label,
  }) {
    return Column(
      children: [
        Text(
          value,
          style: const TextStyle(
            fontSize: 24.0,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
        ),
        const SizedBox(height: 4.0),
        Text(
          label,
          style: TextStyle(
            fontSize: 12.0,
            color: Colors.white.withOpacity(0.9),
          ),
        ),
      ],
    );
  }
  // AI-generated END - 构建单个统计项
}
// AI-generated END - automation_workflow_card.dart

