// AI-generated START - 分类标签栏卡片组件 - Generated by AI
import 'package:flutter/material.dart';

/// 分类标签数据模型
class CategoryTab {
  // AI-generated START - 构造函数
  const CategoryTab({
    required this.label,
    required this.icon,
    this.id,
  });
  // AI-generated END - 构造函数

  /// 标签ID（可选，用于标识）
  final String? id;

  /// 标签文字
  final String label;

  /// 标签图标
  final IconData icon;
}

/// 分类标签栏卡片组件
/// 显示应用分类标签，支持切换选择
class CategoryTabsCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const CategoryTabsCard({
    super.key,
    required this.categories,
    this.selectedIndex = 0,
    this.onCategoryChanged,
  });
  // AI-generated END - 构造函数

  /// 分类列表
  final List<CategoryTab> categories;

  /// 当前选中的索引
  final int selectedIndex;

  /// 分类切换回调
  final ValueChanged<int>? onCategoryChanged;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: Row(
          children: [
            ...categories.asMap().entries.map((entry) {
              final index = entry.key;
              final category = entry.value;
              final isSelected = index == selectedIndex;
              return _buildCategoryButton(category, index, isSelected);
            }).toList(),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建分类按钮
  Widget _buildCategoryButton(CategoryTab category, int index, bool isSelected) {
    return Padding(
      padding: const EdgeInsets.only(right: 8.0),
      child: InkWell(
        onTap: () {
          onCategoryChanged?.call(index);
        },
        borderRadius: BorderRadius.circular(20.0),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 10.0),
          decoration: BoxDecoration(
            color: isSelected
                ? const Color(0xFF4CAF50) // 绿色背景（激活状态）
                : Colors.white, // 白色背景（未激活状态）
            borderRadius: BorderRadius.circular(20.0),
            border: isSelected
                ? null
                : Border.all(
                    color: Colors.grey[300]!,
                    width: 1.0,
                  ),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(
                category.icon,
                color: isSelected
                    ? Colors.white
                    : Colors.grey[600],
                size: 18.0,
              ),
              const SizedBox(width: 6.0),
              Text(
                category.label,
                style: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.w500,
                  color: isSelected
                      ? Colors.white
                      : Colors.grey[600],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
  // AI-generated END - 构建分类按钮
}
// AI-generated END - category_tabs_card.dart

