// AI-generated START - 帮助指南卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';

/// 帮助指南卡片组件
/// 显示帮助提示和教程链接
class HelpGuideCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const HelpGuideCard({
    super.key,
    this.title = '需要帮助?',
    this.description = '查看集成指南,了解如何设置自动化工作流',
    this.linkText = '查看教程',
    this.onTap,
  });
  // AI-generated END - 构造函数

  /// 标题
  final String title;

  /// 描述文字
  final String description;

  /// 链接文字
  final String linkText;

  /// 点击回调
  final VoidCallback? onTap;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      padding: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: const Color(0xFFEFF6FF), // 浅蓝色背景
        borderRadius: BorderRadius.circular(16.0),
        border: Border.all(
          color: const Color(0xFFDBEAFE),
          width: 1.0,
        ),
      ),
      child: InkWell(
        onTap: onTap,
        child: Row(
          children: [
            // 左侧图标
            _buildIcon(),
            const SizedBox(width: 16.0),
            // 右侧文字内容
            Expanded(
              child: _buildContent(),
            ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建图标
  Widget _buildIcon() {
    return Image.asset(
      Assets.images.mpAppIntegrationHelp.path,
      width: 40.0,
      height: 40.0,
      fit: BoxFit.cover,
    );
  }
  // AI-generated END - 构建图标

  // AI-generated START - 构建内容
  Widget _buildContent() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // 标题
        Text(
          title,
          style: const TextStyle(
            fontSize: 16.0,
            fontWeight: FontWeight.w600,
            color: Color(0xFF1F2937),
          ),
        ),
        const SizedBox(height: 2.0),
        // 描述文字
        Text(
          description,
          style: const TextStyle(
            fontSize: 12.0,
            color: Color(0xFF4B5563),
          ),
        ),
        const SizedBox(height: 4.0),
        // 链接文字
        Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              linkText,
              style: const TextStyle(
                fontSize: 14.0,
                color: Color(0xFF2563EB), // 蓝色
                fontWeight: FontWeight.w500,
              ),
            ),
            const SizedBox(width: 4.0),
            const Icon(
              Icons.arrow_forward,
              size: 16.0,
              color: Color(0xFF2563EB), // 蓝色
            ),
          ],
        ),
      ],
    );
  }
  // AI-generated END - 构建内容
}
// AI-generated END - help_guide_card.dart
