// AI-generated START - 基本信息卡片组件 - Generated by AI
import 'package:flutter/material.dart';

/// 基本信息项数据模型
class BasicInfoItem {
  // AI-generated START - 构造函数
  const BasicInfoItem({
    required this.title,
    required this.subtitle,
    required this.icon,
    required this.iconColor,
    this.onTap,
  });
  // AI-generated END - 构造函数

  /// 标题
  final String title;

  /// 副标题
  final String subtitle;

  /// 图标
  final IconData icon;

  /// 图标背景颜色
  final Color iconColor;

  /// 点击回调
  final VoidCallback? onTap;
}

/// 基本信息卡片组件
/// 显示用户的基本信息列表，包括用户名、邮箱和修改密码等选项
class BasicInfoCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const BasicInfoCard({
    super.key,
    this.items,
    this.username = '叶志伟',
    this.email = 'ye.zhiwei@example.com',
    this.onUsernameTap,
    this.onEmailTap,
    this.onPasswordTap,
  });
  // AI-generated END - 构造函数

  /// 基本信息项列表（可选，如果传入则使用传入的，否则使用默认生成的）
  final List<BasicInfoItem>? items;

  /// 用户名
  final String username;

  /// 邮箱
  final String email;

  /// 用户名点击回调
  final VoidCallback? onUsernameTap;

  /// 邮箱点击回调
  final VoidCallback? onEmailTap;

  /// 密码修改点击回调
  final VoidCallback? onPasswordTap;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    // 如果传入了 items，则使用传入的；否则使用默认生成的
    final displayItems = items ??
        [
          BasicInfoItem(
            title: '用户名',
            subtitle: username,
            icon: Icons.person_outline,
            iconColor: const Color(0xFF64B5F6), // 浅蓝色
            onTap: onUsernameTap,
          ),
          BasicInfoItem(
            title: '邮箱',
            subtitle: email,
            icon: Icons.email_outlined,
            iconColor: const Color(0xFF81C784), // 浅绿色
            onTap: onEmailTap,
          ),
          BasicInfoItem(
            title: '修改密码',
            subtitle: '更改账户密码',
            icon: Icons.lock_outline,
            iconColor: const Color(0xFFBA68C8), // 浅紫色
            onTap: onPasswordTap,
          ),
        ];

    return Container(
      margin: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12.0),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // 标题
          _buildHeader(),
          // 列表项
          ...displayItems.asMap().entries.map((entry) {
            final index = entry.key;
            final item = entry.value;
            return _buildListItem(item, index < displayItems.length - 1);
          }).toList(),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建标题
  Widget _buildHeader() {
    return Padding(
      padding: const EdgeInsets.fromLTRB(16.0, 16.0, 16.0, 12.0),
      child: Text(
        '基本信息',
        style: const TextStyle(
          fontSize: 18.0,
          fontWeight: FontWeight.w600,
          color: Color(0xFF212121),
        ),
      ),
    );
  }
  // AI-generated END - 构建标题

  // AI-generated START - 构建列表项
  Widget _buildListItem(BasicInfoItem item, bool showDivider) {
    return Column(
      children: [
        InkWell(
          onTap: item.onTap,
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 16.0),
            child: Row(
              children: [
                // 图标
                Container(
                  width: 40.0,
                  height: 40.0,
                  decoration: BoxDecoration(
                    color: item.iconColor,
                    shape: BoxShape.circle,
                  ),
                  child: Icon(
                    item.icon,
                    color: Colors.white,
                    size: 20.0,
                  ),
                ),
                const SizedBox(width: 16.0),
                // 文本内容
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        item.title,
                        style: const TextStyle(
                          fontSize: 16.0,
                          fontWeight: FontWeight.w500,
                          color: Color(0xFF212121),
                        ),
                      ),
                      const SizedBox(height: 4.0),
                      Text(
                        item.subtitle,
                        style: TextStyle(
                          fontSize: 14.0,
                          color: Colors.grey[600],
                        ),
                      ),
                    ],
                  ),
                ),
                // 右箭头
                Icon(
                  Icons.chevron_right,
                  color: Colors.grey[400],
                  size: 20.0,
                ),
              ],
            ),
          ),
        ),
        // 分隔线
        if (showDivider)
          Divider(
            height: 1.0,
            thickness: 1.0,
            color: Colors.grey[200],
            indent: 72.0, // 对齐到文本开始位置
          ),
      ],
    );
  }
  // AI-generated END - 构建列表项
}
// AI-generated END - basic_info_card.dart

