// AI-generated START - 关注我们卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';
import 'package:omi/pages/mp_newsetting/personal/widgets/basic_info_card.dart';
import 'package:omi/pages/mp_newsetting/personal/widgets/mp_follow_us_list_item.dart';

/// 关注我们卡片组件
/// 显示社交媒体和官方渠道的关注选项
class FollowUsCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const FollowUsCard({
    super.key,
    this.items,
    this.onOfficialWebsiteTap,
    this.onTwitterTap,
    this.onFacebookTap,
    this.onInstagramTap,
    this.onTiktokTap,
    this.onRatingTap,
  });
  // AI-generated END - 构造函数

  /// 关注我们项列表（可选，如果传入则使用传入的，否则使用默认生成的）
  final List<BasicInfoItem>? items;

  /// 官方网站点击回调
  final VoidCallback? onOfficialWebsiteTap;

  /// X (Twitter) 点击回调
  final VoidCallback? onTwitterTap;

  /// Facebook 点击回调
  final VoidCallback? onFacebookTap;

  /// Instagram 点击回调
  final VoidCallback? onInstagramTap;

  /// Tiktok 点击回调
  final VoidCallback? onTiktokTap;

  /// 评分与反馈点击回调
  final VoidCallback? onRatingTap;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    // 如果传入了 items，则使用传入的；否则使用默认生成的
    final displayItems = items ??
        [
          BasicInfoItem(
            title: '官方网站',
            subtitle: '',
            icon: Assets.images.mpPersonalNet.path,
            iconColor: const Color(0xFF2196F3), // 蓝色
            onTap: onOfficialWebsiteTap,
          ),
          BasicInfoItem(
            title: 'X (原 Twitter)',
            subtitle: '',
            icon: Assets.images.mpPersonalTwitter.path,
            iconColor: const Color(0xFF000000), // 黑色
            onTap: onTwitterTap,
          ),
          BasicInfoItem(
            title: 'Facebook',
            subtitle: '',
            icon: Assets.images.mpPersonalFacebook.path,
            iconColor: const Color(0xFF1877F2), // Facebook 蓝色
            onTap: onFacebookTap,
          ),
          BasicInfoItem(
            title: 'Instagram',
            subtitle: '',
            icon: Assets.images.mpPersonalInstagram.path,
            iconColor: const Color(0xFFE4405F), // Instagram 粉红色
            onTap: onInstagramTap,
          ),
          BasicInfoItem(
            title: 'Tiktok',
            subtitle: '',
            icon: Assets.images.mpPersonalTiktok.path,
            iconColor: const Color(0xFF000000), // 黑色
            onTap: onTiktokTap,
          ),
          BasicInfoItem(
            title: '评分与反馈',
            subtitle: '',
            icon: Assets.images.mpPersonalFeedback.path,
            iconColor: const Color(0xFFFFC107), // 黄色
            onTap: onRatingTap,
          ),
        ];

    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12.0),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // 标题
          _buildHeader(),
          // 列表项
          ...displayItems.asMap().entries.map((entry) {
            final index = entry.key;
            final item = entry.value;
            return MPFollowUsListItem(
              item: item,
              showDivider: index < displayItems.length - 1,
            );
          }),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建标题
  Widget _buildHeader() {
    return const Padding(
      padding: EdgeInsets.fromLTRB(16.0, 16.0, 16.0, 12.0),
      child: Text(
        '关注我们',
        style: TextStyle(
          fontSize: 14.0,
          fontWeight: FontWeight.w600,
          color: Color(0xFF212121),
        ),
      ),
    );
  }
  // AI-generated END - 构建标题
}
// AI-generated END - follow_us_card.dart
