// AI-generated START - 关注我们列表项组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';
import 'package:omi/pages/mp_newsetting/personal/widgets/basic_info_card.dart';

/// 关注我们列表项组件
/// 显示单个关注我们选项，包括图标、标题和分隔线
class MPFollowUsListItem extends StatelessWidget {
  // AI-generated START - 构造函数
  const MPFollowUsListItem({
    super.key,
    required this.item,
    this.showDivider = false,
  });
  // AI-generated END - 构造函数

  /// 基本信息项数据
  final BasicInfoItem item;

  /// 是否显示分隔线
  final bool showDivider;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        InkWell(
          onTap: item.onTap,
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 12.0),
            child: Row(
              children: [
                // 图标
                Container(
                  width: 40.0,
                  height: 40.0,
                  decoration: BoxDecoration(
                    color: item.iconColor,
                    shape: BoxShape.circle,
                  ),
                  child: Image.asset(item.icon!, width: 32.0, height: 32.0, fit: BoxFit.contain),
                ),
                const SizedBox(width: 16.0),
                // 文本内容
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text(
                        item.title,
                        style: const TextStyle(
                          fontSize: 14.0,
                          fontWeight: FontWeight.normal,
                          color: Color(0xFF1F2937),
                        ),
                      ),
                      Visibility(
                        visible: item.subtitle.isNotEmpty,
                        child: Text(
                          item.subtitle,
                          style: const TextStyle(
                            fontSize: 12.0,
                            color: Color(0xFF6B7280),
                            fontWeight: FontWeight.normal,
                          ),
                        ),
                      )
                    ],
                  ),
                ),
                // 右箭头
                Image.asset(Assets.images.settingRightArrow1.path, width: 19.0, height: 18.0, fit: BoxFit.contain),
              ],
            ),
          ),
        ),
        // 分隔线
        if (showDivider)
          Container(
            height: 1.0,
            color: const Color(0xFFF3F4F6),
            margin: const EdgeInsets.symmetric(horizontal: 16.0),
          ),
      ],
    );
  }
  // AI-generated END - 构建方法
}
// AI-generated END - mp_follow_us_list_item.dart
