// AI-generated START - 个人资料卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_newsetting/personal/providers/personal_provider.dart';
import 'package:provider/provider.dart';

/// 个人资料卡片组件
/// 显示用户头像、姓名和邮箱信息
class ProfileCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const ProfileCard({
    super.key,
  });
  // AI-generated END - 构造函数

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    // 从 Provider 获取数据，如果传入了参数则优先使用参数
    final personalProvider = Provider.of<PersonalProvider>(context);
    final displayName = personalProvider.name;
    final displayEmail = personalProvider.email;
    final displayAvatarUrl = personalProvider.avatarUrl;

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(vertical: 32.0, horizontal: 16.0),
      decoration: BoxDecoration(
        color: const Color(0xFFF5F5F5), // 浅灰色背景
        borderRadius: BorderRadius.circular(0),
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          // 圆形头像
          _buildAvatar(displayAvatarUrl, 80),
          const SizedBox(height: 16.0),
          // 姓名
          _buildName(displayName),
          const SizedBox(height: 8.0),
          // 邮箱
          _buildEmail(displayEmail),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建头像
  Widget _buildAvatar(String? avatarUrl, double avatarSize) {
    return CircleAvatar(
      radius: avatarSize / 2,
      backgroundColor: const Color(0xFFE0E0E0), // 浅灰色背景
      backgroundImage: avatarUrl != null ? NetworkImage(avatarUrl) : null,
      child: avatarUrl == null
          ? Icon(
              Icons.person,
              size: avatarSize * 0.6,
              color: Colors.grey[600],
            )
          : null,
    );
  }
  // AI-generated END - 构建头像

  // AI-generated START - 构建姓名
  Widget _buildName(String name) {
    return Text(
      name,
      style: const TextStyle(
        fontSize: 20.0,
        fontWeight: FontWeight.w500,
        color: Color(0xFF212121),
        fontFamily: 'PingFang SC', // 中文字体
      ),
    );
  }
  // AI-generated END - 构建姓名

  // AI-generated START - 构建邮箱
  Widget _buildEmail(String email) {
    return Text(
      email,
      style: TextStyle(
        fontSize: 14.0,
        color: Colors.grey[700],
        fontWeight: FontWeight.normal,
      ),
    );
  }
  // AI-generated END - 构建邮箱
}
// AI-generated END - profile_card.dart
