// AI-generated START - 个人资料卡片组件 - Generated by AI
import 'package:flutter/material.dart';

/// 个人资料卡片组件
/// 显示用户头像、姓名和邮箱信息
class ProfileCard extends StatelessWidget {
  final String name;
  final String email;
  final String avatarUrl;
  // AI-generated START - 构造函数
  const ProfileCard({
    super.key,
    this.name = '',
    this.email = '',
    this.avatarUrl = '',
  });
  // AI-generated END - 构造函数

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(vertical: 10.0, horizontal: 16.0),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          // 圆形头像
          _buildAvatar(avatarUrl, 80),
          const SizedBox(height: 12.0),
          // 姓名
          _buildName(name),
          const SizedBox(height: 4.0),
          // 邮箱
          _buildEmail(email),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建头像
  Widget _buildAvatar(String? avatarUrl, double avatarSize) {
    return CircleAvatar(
      radius: avatarSize / 2,
      backgroundColor: const Color(0xFFE0E0E0), // 浅灰色背景
      backgroundImage: avatarUrl != null ? NetworkImage(avatarUrl) : null,
      child: avatarUrl == null
          ? Icon(
              Icons.person,
              size: avatarSize * 0.6,
              color: Colors.grey[600],
            )
          : null,
    );
  }
  // AI-generated END - 构建头像

  // AI-generated START - 构建姓名
  Widget _buildName(String name) {
    return Text(
      name,
      style: const TextStyle(
        fontSize: 16.0,
        fontWeight: FontWeight.w600,
        color: Color(0xFF1F2937),
        fontFamily: 'PingFang SC', // 中文字体
      ),
    );
  }
  // AI-generated END - 构建姓名

  // AI-generated START - 构建邮箱
  Widget _buildEmail(String email) {
    return Text(
      email,
      style: TextStyle(
        fontSize: 12.0,
        color: Color(0xFF4B5563),
        fontWeight: FontWeight.normal,
      ),
    );
  }
  // AI-generated END - 构建邮箱
}
// AI-generated END - profile_card.dart
