// AI-generated START - 个人中心页面 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/newsetting/personal/providers/personal_provider.dart';
import 'package:omi/pages/newsetting/personal/widgets/account_management_card.dart';
import 'package:omi/pages/newsetting/personal/widgets/basic_info_card.dart';
import 'package:omi/pages/newsetting/personal/widgets/delete_account_card.dart';
import 'package:omi/pages/newsetting/personal/widgets/follow_us_card.dart';
import 'package:omi/pages/newsetting/personal/widgets/profile_card.dart';
import 'package:provider/provider.dart';

/// 个人中心页面
/// 显示用户个人信息、基本信息和账户管理等功能
class PersonalPage extends StatefulWidget {
  // AI-generated START - 构造函数
  const PersonalPage({
    super.key,
    this.title = '个人中心',
  });
  // AI-generated END - 构造函数

  /// 页面标题
  final String title;

  // AI-generated START - 创建状态
  @override
  State<PersonalPage> createState() => _PersonalPageState();
  // AI-generated END - 创建状态
}

class _PersonalPageState extends State<PersonalPage> {
  // AI-generated START - 初始化方法
  @override
  void initState() {
    super.initState();
    // AI-generated START - 初始化个人中心数据
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted) return;
      // 获取 PersonalProvider 实例，用于后续数据加载
      final provider = Provider.of<PersonalProvider>(context, listen: false);
      // 可以在这里加载用户数据
      provider.loadUserProfile();
    });
    // AI-generated END - 初始化个人中心数据
  }
  // AI-generated END - 初始化方法

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Consumer<PersonalProvider>(
      builder: (context, personalProvider, child) {
        return Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: const SingleChildScrollView(
            child: Column(
              children: [
                ProfileCard(),
                BasicInfoCard(),
                AccountManagementCard(),
                FollowUsCard(),
                DeleteAccountCard(),
              ],
            ),
          ),
        );
      },
    );
  }
  // AI-generated END - 构建方法
}
// AI-generated END - personal_page.dart
