// AI-generated START - AI总结模版标题卡片组件 - Generated by AI
import 'package:flutter/material.dart';

/// AI总结模版标题卡片组件
/// 显示AI总结模版的标题和说明
class AISummaryTemplateHeaderCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const AISummaryTemplateHeaderCard({
    super.key,
    this.title = 'AI总结模版',
    this.subtitle = '选择适合的模版,让AI为你生成更精准的总结',
  });
  // AI-generated END - 构造函数

  /// 标题
  final String title;

  /// 副标题
  final String subtitle;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.fromLTRB(16.0, 16.0, 16.0, 12.0),
      decoration: const BoxDecoration(
        color: Colors.white,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // 标题
          Text(
            title,
            style: const TextStyle(
              fontSize: 18.0,
              fontWeight: FontWeight.w600,
              color: Color(0xFF212121),
            ),
          ),
          const SizedBox(height: 8.0),
          // 副标题
          Text(
            subtitle,
            style: TextStyle(
              fontSize: 14.0,
              color: Colors.grey[600],
            ),
          ),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法
}
// AI-generated END - ai_summary_template_header_card.dart

