// AI-generated START - 横向滑动模版卡片组件 - Generated by AI
import 'package:flutter/material.dart';

/// 横向滑动模版项数据模型
class HorizontalScrollTemplateItem {
  // AI-generated START - 构造函数
  const HorizontalScrollTemplateItem({
    required this.id,
    required this.title,
    this.icon,
    this.iconColor,
    this.backgroundColor,
  });
  // AI-generated END - 构造函数

  /// 项ID
  final String id;

  /// 标题文字
  final String title;

  /// 图标（可选）
  final IconData? icon;

  /// 图标颜色（可选）
  final Color? iconColor;

  /// 背景颜色（可选）
  final Color? backgroundColor;
}

/// 横向滑动模版卡片组件
/// 显示一个标题和多个可横向滑动的模版项
class HorizontalScrollTemplateCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const HorizontalScrollTemplateCard({
    super.key,
    required this.title,
    required this.items,
    this.onItemTap,
    this.itemWidth = 120.0,
    this.itemHeight = 120.0,
  });
  // AI-generated END - 构造函数

  /// 卡片标题
  final String title;

  /// 模版项列表
  final List<HorizontalScrollTemplateItem> items;

  /// 项点击回调，参数为被点击的项
  final Function(HorizontalScrollTemplateItem item)? onItemTap;

  /// 每个项的宽度（默认120.0）
  final double itemWidth;

  /// 每个项的高度（默认120.0）
  final double itemHeight;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // 标题
          _buildTitle(),
          const SizedBox(height: 16.0),
          // 横向滑动的项列表
          _buildScrollableItems(),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建标题
  /// 构建标题
  Widget _buildTitle() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          title,
          style: const TextStyle(
            fontSize: 18.0,
            fontWeight: FontWeight.bold,
            color: Color(0xFF1F2937),
          ),
        ),
        const Icon(
          Icons.arrow_forward_ios,
          size: 14.0,
          color: Color(0xFF9CA3AF),
        ),
      ],
    );
  }
  // AI-generated END - 构建标题

  // AI-generated START - 构建可滑动的项列表
  /// 构建横向滑动的项列表
  Widget _buildScrollableItems() {
    if (items.isEmpty) {
      return const SizedBox.shrink();
    }

    return SizedBox(
      height: itemHeight,
      child: ListView.builder(
        scrollDirection: Axis.horizontal,
        itemCount: items.length,
        itemBuilder: (context, index) {
          final item = items[index];
          return _buildItem(item);
        },
      ),
    );
  }
  // AI-generated END - 构建可滑动的项列表

  // AI-generated START - 构建单个项
  /// 构建单个模版项
  Widget _buildItem(HorizontalScrollTemplateItem item) {
    return GestureDetector(
      onTap: () {
        onItemTap?.call(item);
      },
      child: Container(
        width: itemWidth,
        height: itemHeight,
        margin: const EdgeInsets.only(right: 12.0),
        decoration: BoxDecoration(
          color: item.backgroundColor ?? Colors.white,
          borderRadius: BorderRadius.circular(12.0),
          boxShadow: [
            BoxShadow(
              color: Colors.grey.withOpacity(0.1),
              spreadRadius: 1,
              blurRadius: 4,
              offset: const Offset(0, 2),
            ),
          ],
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            // 图标
            if (item.icon != null)
              Container(
                width: 48.0,
                height: 48.0,
                decoration: BoxDecoration(
                  color: item.iconColor ?? const Color(0xFF374151),
                  borderRadius: BorderRadius.circular(8.0),
                ),
                child: Icon(
                  item.icon,
                  color: Colors.white,
                  size: 24.0,
                ),
              )
            else
              Container(
                width: 48.0,
                height: 48.0,
                decoration: BoxDecoration(
                  color: const Color(0xFF374151),
                  borderRadius: BorderRadius.circular(8.0),
                ),
              ),
            const SizedBox(height: 12.0),
            // 标题文字
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 8.0),
              child: Text(
                item.title,
                textAlign: TextAlign.center,
                maxLines: 2,
                overflow: TextOverflow.ellipsis,
                style: const TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.w500,
                  color: Color(0xFF1F2937),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建单个项
}
// AI-generated END - horizontal_scroll_template_card.dart

