// AI-generated START - 模版卡片组件 - Generated by AI
import 'package:flutter/material.dart';

/// 模版功能项数据模型
class TemplateFeature {
  // AI-generated START - 构造函数
  const TemplateFeature({
    required this.label,
  });
  // AI-generated END - 构造函数

  /// 功能标签文字
  final String label;
}

/// 模版卡片组件
/// 显示AI总结模版信息，包括图标、标题、描述、功能列表和预览按钮
class TemplateCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const TemplateCard({
    super.key,
    required this.title,
    required this.description,
    required this.icon,
    required this.iconColor,
    this.isSelected = false,
    this.isHot = false,
    this.features = const [],
    this.onPreview,
    this.onSelect,
  });
  // AI-generated END - 构造函数

  /// 模版标题
  final String title;

  /// 描述文字
  final String description;

  /// 图标
  final IconData icon;

  /// 图标背景颜色
  final Color iconColor;

  /// 是否已选中
  final bool isSelected;

  /// 是否热门
  final bool isHot;

  /// 功能列表
  final List<TemplateFeature> features;

  /// 预览回调
  final VoidCallback? onPreview;

  /// 选择回调
  final VoidCallback? onSelect;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      padding: const EdgeInsets.all(16.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12.0),
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.1),
            spreadRadius: 1,
            blurRadius: 4,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // 头部：图标、标题、标签和选择状态
          _buildHeader(),
          const SizedBox(height: 12.0),
          // 描述文字
          _buildDescription(),
          const SizedBox(height: 12.0),
          // 功能列表
          if (features.isNotEmpty) _buildFeatures(),
          const SizedBox(height: 16.0),
          // 预览按钮
          _buildPreviewButton(),
        ],
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建头部
  Widget _buildHeader() {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // 左侧图标
        Container(
          width: 48.0,
          height: 48.0,
          decoration: BoxDecoration(
            color: iconColor,
            borderRadius: BorderRadius.circular(8.0),
          ),
          child: Icon(
            icon,
            color: Colors.white,
            size: 24.0,
          ),
        ),
        const SizedBox(width: 12.0),
        // 中间：标题和标签
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Text(
                    title,
                    style: const TextStyle(
                      fontSize: 18.0,
                      fontWeight: FontWeight.w600,
                      color: Color(0xFF212121),
                    ),
                  ),
                  if (isHot) ...[
                    const SizedBox(width: 8.0),
                    _buildHotTag(),
                  ],
                ],
              ),
            ],
          ),
        ),
        // 右侧：选择状态
        _buildSelectIndicator(),
      ],
    );
  }
  // AI-generated END - 构建头部

  // AI-generated START - 构建热门标签
  Widget _buildHotTag() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8.0, vertical: 2.0),
      decoration: BoxDecoration(
        color: const Color(0xFFE57373), // 红色
        borderRadius: BorderRadius.circular(10.0),
      ),
      child: const Text(
        '热门',
        style: TextStyle(
          fontSize: 10.0,
          color: Colors.white,
          fontWeight: FontWeight.w500,
        ),
      ),
    );
  }
  // AI-generated END - 构建热门标签

  // AI-generated START - 构建选择指示器
  Widget _buildSelectIndicator() {
    return InkWell(
      onTap: onSelect,
      child: Container(
        width: 24.0,
        height: 24.0,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          border: Border.all(
            color: isSelected
                ? const Color(0xFF2196F3) // 蓝色边框
                : Colors.grey[300]!,
            width: 2.0,
          ),
          color: isSelected
              ? const Color(0xFF2196F3) // 蓝色背景
              : Colors.transparent,
        ),
        child: isSelected
            ? const Icon(
                Icons.check,
                color: Colors.white,
                size: 16.0,
              )
            : null,
      ),
    );
  }
  // AI-generated END - 构建选择指示器

  // AI-generated START - 构建描述
  Widget _buildDescription() {
    return Text(
      description,
      style: TextStyle(
        fontSize: 14.0,
        color: Colors.grey[700],
        height: 1.5,
      ),
    );
  }
  // AI-generated END - 构建描述

  // AI-generated START - 构建功能列表
  Widget _buildFeatures() {
    return LayoutBuilder(
      builder: (context, constraints) {
        // 计算每个功能项的宽度，确保每行只有2个
        // 减去间距：16px (spacing) + 左右padding
        final itemWidth = (constraints.maxWidth - 16.0) / 2;

        return Wrap(
          spacing: 16.0, // 水平间距
          runSpacing: 8.0, // 垂直间距
          children: features.map((feature) {
            return SizedBox(
              width: itemWidth,
              child: Row(
                children: [
                  Icon(
                    Icons.circle,
                    size: 4.0,
                    color: Colors.grey[600],
                  ),
                  const SizedBox(width: 8.0),
                  Expanded(
                    child: Text(
                      feature.label,
                      style: TextStyle(
                        fontSize: 13.0,
                        color: Colors.grey[700],
                      ),
                    ),
                  ),
                ],
              ),
            );
          }).toList(),
        );
      },
    );
  }
  // AI-generated END - 构建功能列表

  // AI-generated START - 构建预览按钮
  Widget _buildPreviewButton() {
    return SizedBox(
      width: double.infinity,
      child: OutlinedButton.icon(
        onPressed: onPreview,
        icon: const Icon(
          Icons.visibility_outlined,
          size: 18.0,
        ),
        label: const Text('预览模版效果'),
        style: OutlinedButton.styleFrom(
          padding: const EdgeInsets.symmetric(vertical: 12.0),
          side: BorderSide(
            color: const Color(0xFF2196F3).withOpacity(0.5), // 浅蓝色边框
            width: 1.0,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8.0),
          ),
        ),
      ),
    );
  }
  // AI-generated END - 构建预览按钮
}
// AI-generated END - template_card.dart

