// AI-generated START - 添加专家页面 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_custom_utils/mp_const_utils.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/providers/mp_add_export_provider.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/widgets/mp_expert_avatar_name_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/widgets/mp_expert_category_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/widgets/mp_expert_feedback_time_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/widgets/mp_expert_introduction_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/widgets/mp_expert_prompt_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/widgets/mp_expert_skills_card.dart';
import 'package:omi/pages/mp_newsetting/home/widgets/mp_common_app_bar.dart';
import 'package:provider/provider.dart';

/// 添加专家页面
/// 用于创建和添加新的AI专家
class MPAddExportPage extends StatefulWidget {
  // AI-generated START - 构造函数
  const MPAddExportPage({
    super.key,
    this.title = '创建AI专家',
  });
  // AI-generated END - 构造函数

  /// 页面标题
  final String title;

  @override
  State<MPAddExportPage> createState() => _MPAddExportPageState();
}

class _MPAddExportPageState extends State<MPAddExportPage> {
  // AI-generated START - 表单控制器
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _aboutController = TextEditingController();
  // AI-generated END - 表单控制器

  // AI-generated START - 初始化方法
  @override
  void initState() {
    super.initState();
  }
  // AI-generated END - 初始化方法

  // AI-generated START - 清理资源
  @override
  void dispose() {
    _nameController.dispose();
    _aboutController.dispose();
    super.dispose();
  }
  // AI-generated END - 清理资源

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => MPAddExportProvider(),
      child: Consumer<MPAddExportProvider>(
        builder: (context, provider, child) {
          return Scaffold(
            backgroundColor: MPConstUtils.backgroundColorGrey,
            appBar: MPCommonAppBar(
              title: widget.title,
            ),
            body: Form(
              key: _formKey,
              child: SingleChildScrollView(
                padding: const EdgeInsets.symmetric(vertical: 8.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    // AI-generated START - 专家头像和名字卡片
                    MPExpertAvatarNameCard(
                      nameController: _nameController,
                    ),
                    // AI-generated END - 专家头像和名字卡片

                    // AI-generated START - 专家介绍卡片
                    MPExpertIntroductionCard(
                      aboutController: _aboutController,
                    ),
                    // AI-generated END - 专家介绍卡片

                    // AI-generated START - 专家技能卡片
                    const MPExpertSkillsCard(),
                    // AI-generated END - 专家技能卡片

                    // AI-generated START - 专家类别卡片
                    const MPExpertCategoryCard(),
                    // AI-generated END - 专家类别卡片

                    // AI-generated START - 根据技能类型显示不同的 Prompt 卡片（支持多选）
                    if (provider.selectedSkills.contains(MPExpertSkillType.chat))
                      const MPExpertPromptCard(
                        skillType: MPExpertSkillType.chat,
                      ),

                    if (provider.selectedSkills.contains(MPExpertSkillType.feedback)) ...[
                      const MPExpertPromptCard(
                        skillType: MPExpertSkillType.feedback,
                      ),
                      // AI-generated START - 反馈时间卡片（仅 Feedback 技能显示）
                      const MPExpertFeedbackTimeCard(),
                      // AI-generated END - 反馈时间卡片
                    ],
                    // AI-generated END - 根据技能类型显示不同的 Prompt 卡片

                    // AI-generated START - 提交按钮
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 16.0),
                      child: _buildSubmitButton(provider),
                    ),
                    // AI-generated END - 提交按钮
                  ],
                ),
              ),
            ),
          );
        },
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建提交按钮
  Widget _buildSubmitButton(MPAddExportProvider provider) {
    return SizedBox(
      height: 56.0,
      child: ElevatedButton(
        onPressed: provider.isSubmitting
            ? null
            : () async {
                final success = await provider.submitForm();
                if (mounted) {
                  if (success) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text('创建成功'),
                        duration: Duration(seconds: 1),
                      ),
                    );
                    Navigator.of(context).pop(true);
                  }
                }
              },
        style: ElevatedButton.styleFrom(
          backgroundColor: const Color(0xFF2563EB),
          disabledBackgroundColor: Colors.grey.shade300,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.0),
          ),
          elevation: 0,
        ),
        child: provider.isSubmitting
            ? const SizedBox(
                width: 20.0,
                height: 20.0,
                child: CircularProgressIndicator(
                  strokeWidth: 2.0,
                  valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                ),
              )
            : const Text(
                '提交审核',
                style: TextStyle(
                  fontSize: 16.0,
                  fontWeight: FontWeight.w600,
                  color: Colors.white,
                ),
              ),
      ),
    );
  }
  // AI-generated END - _buildSubmitButton
}
// AI-generated END - mp_add_export_page.dart
