// AI-generated START - 专家详情页面 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_custom_utils/mp_const_utils.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/providers/mp_add_export_provider.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/providers/mp_export_detail_provider.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_avatar_name_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_category_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_feedback_time_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_introduction_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_prompt_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_skills_card.dart';
import 'package:omi/pages/mp_newsetting/home/widgets/mp_common_app_bar.dart';
import 'package:provider/provider.dart';

/// 专家详情页面
/// 用于查看和编辑专家详情（仅反馈时间可编辑）
class MPExportDetailPage extends StatefulWidget {
  // AI-generated START - 构造函数
  const MPExportDetailPage({
    super.key,
    required this.expertId,
    this.title = '专家详情',
  });
  // AI-generated END - 构造函数

  /// 专家ID
  final String expertId;

  /// 页面标题
  final String title;

  @override
  State<MPExportDetailPage> createState() => _MPExportDetailPageState();
}

class _MPExportDetailPageState extends State<MPExportDetailPage> {
  // AI-generated START - 初始化方法
  @override
  void initState() {
    super.initState();
    // 加载专家详情
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final provider = Provider.of<MPExportDetailProvider>(context, listen: false);
      provider.loadExpertDetail();
    });
  }
  // AI-generated END - 初始化方法

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => MPExportDetailProvider(expertId: widget.expertId),
      child: Consumer<MPExportDetailProvider>(
        builder: (context, provider, child) {
          if (provider.isLoading) {
            return Scaffold(
              backgroundColor: MPConstUtils.backgroundColorGrey,
              appBar: MPCommonAppBar(title: widget.title),
              body: const Center(
                child: CircularProgressIndicator(),
              ),
            );
          }

          if (provider.expert == null) {
            return Scaffold(
              backgroundColor: MPConstUtils.backgroundColorGrey,
              appBar: MPCommonAppBar(title: widget.title),
              body: const Center(
                child: Text('加载失败'),
              ),
            );
          }

          return Scaffold(
            backgroundColor: MPConstUtils.backgroundColorGrey,
            appBar: MPCommonAppBar(title: widget.title),
            body: SingleChildScrollView(
              padding: const EdgeInsets.symmetric(vertical: 8.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // AI-generated START - 专家头像和名字卡片（只读）
                  MPExpertDetailAvatarNameCard(
                    name: provider.expert!.name,
                    avatar: provider.expert!.avatar,
                  ),
                  // AI-generated END - 专家头像和名字卡片

                  // AI-generated START - 专家介绍卡片（只读）
                  MPExpertDetailIntroductionCard(
                    about: provider.expert!.about,
                  ),
                  // AI-generated END - 专家介绍卡片

                  // AI-generated START - 专家技能卡片（只读）
                  MPExpertDetailSkillsCard(
                    capabilities: provider.expert!.capabilities,
                  ),
                  // AI-generated END - 专家技能卡片

                  // AI-generated START - 专家类别卡片（只读）
                  MPExpertDetailCategoryCard(
                    type: provider.expert!.capabilities.isNotEmpty ? 'business' : 'business',
                  ),
                  // AI-generated END - 专家类别卡片

                  // AI-generated START - 根据技能类型显示不同的 Prompt 卡片（只读）
                  if (provider.selectedSkills.contains(MPExpertSkillType.chat))
                    MPExpertDetailPromptCard(
                      skillType: MPExpertSkillType.chat,
                      prompt: provider.expert!.prompt,
                    ),

                  if (provider.selectedSkills.contains(MPExpertSkillType.feedback)) ...[
                    MPExpertDetailPromptCard(
                      skillType: MPExpertSkillType.feedback,
                      prompt: provider.expert!.prompt,
                    ),
                    // AI-generated START - 反馈时间卡片（可编辑）
                    const MPExpertDetailFeedbackTimeCard(),
                    // AI-generated END - 反馈时间卡片
                  ],
                  // AI-generated END - 根据技能类型显示不同的 Prompt 卡片

                  // AI-generated START - 保存按钮
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 16.0),
                    child: _buildSaveButton(provider),
                  ),
                  // AI-generated END - 保存按钮
                ],
              ),
            ),
          );
        },
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建保存按钮
  Widget _buildSaveButton(MPExportDetailProvider provider) {
    return SizedBox(
      height: 56.0,
      child: ElevatedButton(
        onPressed: provider.isSubmitting
            ? null
            : () async {
                final success = await provider.saveFeedbackTime();
                if (mounted && success) {
                  Navigator.of(context).pop(true);
                }
              },
        style: ElevatedButton.styleFrom(
          backgroundColor: const Color(0xFF2563EB),
          disabledBackgroundColor: Colors.grey.shade300,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.0),
          ),
          elevation: 0,
        ),
        child: provider.isSubmitting
            ? const SizedBox(
                width: 20.0,
                height: 20.0,
                child: CircularProgressIndicator(
                  strokeWidth: 2.0,
                  valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                ),
              )
            : const Text(
                '保存',
                style: TextStyle(
                  fontSize: 16.0,
                  fontWeight: FontWeight.w600,
                  color: Colors.white,
                ),
              ),
      ),
    );
  }
  // AI-generated END - _buildSaveButton
}
// AI-generated END - mp_export_detail_page.dart
