// AI-generated START - 专家详情页面 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_custom_utils/mp_const_utils.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/providers/mp_add_export_provider.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/providers/mp_export_detail_provider.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_action_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_avatar_name_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_category_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_feedback_time_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_introduction_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_prompt_card.dart';
import 'package:omi/pages/mp_expert_feedback/mp_export_detail/widgets/mp_expert_detail_skills_card.dart';
import 'package:omi/pages/mp_newsetting/home/widgets/mp_common_app_bar.dart';
import 'package:provider/provider.dart';

/// 专家详情页面
/// 用于查看和编辑专家详情（仅反馈时间可编辑）
class MPExportDetailPage extends StatefulWidget {
  // AI-generated START - 构造函数
  const MPExportDetailPage({
    super.key,
    required this.expertId,
    this.title = '专家详情',
  });
  // AI-generated END - 构造函数

  /// 专家ID
  final String expertId;

  /// 页面标题
  final String title;

  @override
  State<MPExportDetailPage> createState() => _MPExportDetailPageState();
}

class _MPExportDetailPageState extends State<MPExportDetailPage> {
  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) {
        final provider = MPExportDetailProvider(expertId: widget.expertId);
        // 在 Provider 创建后立即加载数据
        WidgetsBinding.instance.addPostFrameCallback((_) {
          provider.loadExpertDetail();
        });
        return provider;
      },
      child: Consumer<MPExportDetailProvider>(
        builder: (context, provider, child) {
          if (provider.isLoading) {
            return Scaffold(
              backgroundColor: MPConstUtils.backgroundColorGrey,
              appBar: MPCommonAppBar(title: widget.title),
              body: const Center(
                child: CircularProgressIndicator(),
              ),
            );
          }

          if (provider.expert == null) {
            return Scaffold(
              backgroundColor: MPConstUtils.backgroundColorGrey,
              appBar: MPCommonAppBar(title: widget.title),
              body: const Center(
                child: Text('加载失败'),
              ),
            );
          }

          return Scaffold(
            backgroundColor: MPConstUtils.backgroundColorGrey,
            appBar: MPCommonAppBar(title: widget.title),
            body: SingleChildScrollView(
              padding: const EdgeInsets.symmetric(vertical: 8.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // AI-generated START - 专家头像和名字卡片（只读）
                  MPExpertDetailAvatarNameCard(
                    name: provider.expert!.name,
                    avatar: provider.expert!.avatar ?? '',
                  ),
                  // AI-generated END - 专家头像和名字卡片

                  // AI-generated START - 专家介绍卡片（只读）
                  MPExpertDetailIntroductionCard(
                    about: provider.expert!.about ?? '',
                  ),
                  // AI-generated END - 专家介绍卡片

                  // AI-generated START - 专家技能卡片（只读）
                  MPExpertDetailSkillsCard(
                    capabilities: provider.expert!.capabilities ?? [],
                  ),
                  // AI-generated END - 专家技能卡片

                  // AI-generated START - 专家类别卡片（只读）
                  MPExpertDetailCategoryCard(
                    type: (provider.expert!.capabilities?.isNotEmpty ?? false) ? 'business' : 'business',
                  ),
                  // AI-generated END - 专家类别卡片

                  // AI-generated START - 根据技能类型显示不同的 Prompt 卡片（只读）
                  if (provider.selectedSkills.contains(MPExpertSkillType.chat))
                    MPExpertDetailPromptCard(
                      skillType: MPExpertSkillType.chat,
                      prompt: provider.expert!.chatPrompt ?? '',
                    ),

                  if (provider.selectedSkills.contains(MPExpertSkillType.feedback)) ...[
                    MPExpertDetailPromptCard(
                      skillType: MPExpertSkillType.feedback,
                      prompt: provider.expert!.feedPrompt ?? '',
                    ),
                    // AI-generated START - 反馈时间卡片（可编辑）
                    const MPExpertDetailFeedbackTimeCard(),
                    // AI-generated END - 反馈时间卡片
                  ],
                  // AI-generated END - 根据技能类型显示不同的 Prompt 卡片

                  // AI-generated START - 操作按钮卡片（添加/取消添加/保存）
                  const MPExpertDetailActionCard(),
                  // AI-generated END - 操作按钮卡片
                ],
              ),
            ),
          );
        },
      ),
    );
  }
  // AI-generated END - 构建方法
}
// AI-generated END - mp_export_detail_page.dart
