// AI-generated START - 日历Provider - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/backend/http/mp_api/mp_memory.dart';
import 'package:omi/backend/schema/mp/mp_memory.dart';

/// 日历Provider
/// 管理日历的日期数据、选中状态和事件标记
class CalendarProvider extends ChangeNotifier {
  // AI-generated START - 构造函数
  CalendarProvider() {
    _initializeDates();
  }
  // AI-generated END - 构造函数

  /// 当前显示的月份
  DateTime _currentMonth = DateTime.now();

  /// 当前选中的日期
  DateTime? _selectedDate;

  /// 有事件的日期列表（用于标记哪些日期有事件）
  final Set<DateTime> _eventDates = {};

  /// 是否正在加载数据
  bool _isLoading = false;

  /// 月份数据缓存，key为月份字符串（如 "2025-12"），value为日期列表，null表示已查询但为空
  final Map<String, List<String>?> _monthDataCache = {};

  /// 获取当前月份
  DateTime get currentMonth => _currentMonth;

  /// 获取当前选中的日期
  DateTime? get selectedDate => _selectedDate;

  /// 获取有事件的日期集合
  Set<DateTime> get eventDates => _eventDates;

  // AI-generated START - 初始化日期数据
  void _initializeDates() {
    // 设置默认显示月份为当前月份
    final now = DateTime.now();
    _currentMonth = DateTime(now.year, now.month, 1);

    // 设置默认选中日期为今天
    _selectedDate = DateTime(now.year, now.month, now.day);

    // 加载当前月份的数据
    loadMemoryDays(_currentMonth);
  }
  // AI-generated END - 初始化日期数据

  // AI-generated START - 从接口加载有记忆的日期
  /// 从接口加载指定月份有记忆的日期
  /// 优先从缓存中获取，缓存中没有则调用接口
  Future<void> loadMemoryDays(DateTime month) async {
    // 格式化月份为 "2025-12" 格式
    final monthStr = '${month.year}-${month.month.toString().padLeft(2, '0')}';

    // 优先从缓存中获取
    if (_monthDataCache.containsKey(monthStr)) {
      final cachedData = _monthDataCache[monthStr];
      if (cachedData == null) {
        // 缓存中标记为空，不需要再次调用接口
        _updateEventDatesForMonth(month, []);
        return;
      } else {
        // 使用缓存数据
        _updateEventDatesForMonth(month, cachedData);
        return;
      }
    }

    // 缓存中没有，调用接口获取
    if (_isLoading) return;

    _isLoading = true;
    notifyListeners();

    try {
      final request = MPGetMemoryDaysRequest(month: monthStr);
      final response = await getMemoryDays(request);

      List<String> days = [];
      if (response != null && response.days.isNotEmpty) {
        days = response.days;
      }

      // 将结果存入缓存（即使是空列表也要缓存，避免重复调用）
      _monthDataCache[monthStr] = days.isEmpty ? null : days;

      // 更新事件日期
      _updateEventDatesForMonth(month, days);
    } catch (e) {
      debugPrint('Failed to load memory days: $e');
      // 接口调用失败，标记为空，避免重复调用
      _monthDataCache[monthStr] = null;
      _updateEventDatesForMonth(month, []);
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  /// 更新指定月份的事件日期
  void _updateEventDatesForMonth(DateTime month, List<String> days) {
    // 清空当前月份的事件日期
    _eventDates.removeWhere((date) => date.year == month.year && date.month == month.month);

    // 将返回的日期字符串转换为 DateTime 对象
    for (final dayStr in days) {
      try {
        // 解析日期字符串，格式如 "2025-11-10"
        final parts = dayStr.split('-');
        if (parts.length == 3) {
          final year = int.parse(parts[0]);
          final monthNum = int.parse(parts[1]);
          final day = int.parse(parts[2]);
          _eventDates.add(DateTime(year, monthNum, day));
        }
      } catch (e) {
        debugPrint('Failed to parse date: $dayStr, error: $e');
      }
    }
    notifyListeners();
  }
  // AI-generated END - 从接口加载有记忆的日期

  // AI-generated START - 设置当前月份
  /// 设置当前显示的月份
  void setCurrentMonth(DateTime month) {
    final newMonth = DateTime(month.year, month.month, 1);
    if (_currentMonth.year != newMonth.year || _currentMonth.month != newMonth.month) {
      _currentMonth = newMonth;
      loadMemoryDays(_currentMonth);
    }
  }
  // AI-generated END - 设置当前月份

  // AI-generated START - 选择日期
  /// 选择日期
  void selectDate(DateTime date) {
    _selectedDate = DateTime(date.year, date.month, date.day);
    notifyListeners();
  }
  // AI-generated END - 选择日期

  // AI-generated START - 回到今天
  /// 回到今天并选中今天
  void goToToday() {
    final today = DateTime.now();
    final newMonth = DateTime(today.year, today.month, 1);
    if (_currentMonth.year != newMonth.year || _currentMonth.month != newMonth.month) {
      _currentMonth = newMonth;
      loadMemoryDays(_currentMonth);
    }
    _selectedDate = DateTime(today.year, today.month, today.day);
    notifyListeners();
  }
  // AI-generated END - 回到今天

  // AI-generated START - 上一个月
  /// 切换到上一个月
  void previousMonth() {
    final newMonth = DateTime(
      _currentMonth.year,
      _currentMonth.month - 1,
      1,
    );
    _currentMonth = newMonth;
    loadMemoryDays(_currentMonth);
  }
  // AI-generated END - 上一个月

  // AI-generated START - 下一个月
  /// 切换到下一个月
  void nextMonth() {
    final newMonth = DateTime(
      _currentMonth.year,
      _currentMonth.month + 1,
      1,
    );
    _currentMonth = newMonth;
    loadMemoryDays(_currentMonth);
  }
  // AI-generated END - 下一个月

  // AI-generated START - 判断日期是否有事件
  /// 判断指定日期是否有事件
  bool hasEvent(DateTime date) {
    final normalizedDate = DateTime(date.year, date.month, date.day);
    return _eventDates.any((eventDate) =>
        eventDate.year == normalizedDate.year &&
        eventDate.month == normalizedDate.month &&
        eventDate.day == normalizedDate.day);
  }
  // AI-generated END - 判断日期是否有事件

  // AI-generated START - 添加事件日期
  /// 添加事件日期
  void addEventDate(DateTime date) {
    _eventDates.add(DateTime(date.year, date.month, date.day));
    notifyListeners();
  }
  // AI-generated END - 添加事件日期

  // AI-generated START - 移除事件日期
  /// 移除事件日期
  void removeEventDate(DateTime date) {
    _eventDates.removeWhere(
        (eventDate) => eventDate.year == date.year && eventDate.month == date.month && eventDate.day == date.day);
    notifyListeners();
  }
  // AI-generated END - 移除事件日期
}
// AI-generated END - calendar_provider.dart
