// AI-generated START - 日历Provider - Generated by AI
import 'package:flutter/material.dart';

/// 日历Provider
/// 管理日历的日期数据、选中状态和事件标记
class CalendarProvider extends ChangeNotifier {
  // AI-generated START - 构造函数
  CalendarProvider() {
    _initializeDates();
  }
  // AI-generated END - 构造函数

  /// 当前显示的月份
  DateTime _currentMonth = DateTime.now();

  /// 当前选中的日期
  DateTime? _selectedDate;

  /// 有事件的日期列表（用于标记哪些日期有事件）
  final Set<DateTime> _eventDates = {};

  /// 获取当前月份
  DateTime get currentMonth => _currentMonth;

  /// 获取当前选中的日期
  DateTime? get selectedDate => _selectedDate;

  /// 获取有事件的日期集合
  Set<DateTime> get eventDates => _eventDates;

  // AI-generated START - 初始化日期数据
  void _initializeDates() {
    // 添加一些模拟的事件日期（2025年12月有事件的日期）
    final eventYear = 2025;
    final eventMonth = 12;
    
    _eventDates.addAll([
      DateTime(eventYear, eventMonth, 4),
      DateTime(eventYear, eventMonth, 8),
      DateTime(eventYear, eventMonth, 10),
      DateTime(eventYear, eventMonth, 12),
      DateTime(eventYear, eventMonth, 13),
      DateTime(eventYear, eventMonth, 16),
      DateTime(eventYear, eventMonth, 17),
      DateTime(eventYear, eventMonth, 21),
      DateTime(eventYear, eventMonth, 25),
      DateTime(eventYear, eventMonth, 26),
      DateTime(eventYear, eventMonth, 28),
      DateTime(eventYear, eventMonth, 29),
    ]);
    
    // 设置默认显示月份为2025年12月
    _currentMonth = DateTime(eventYear, eventMonth, 1);
    
    // 设置默认选中日期为12月3日（根据图片）
    _selectedDate = DateTime(eventYear, eventMonth, 3);
    notifyListeners();
  }
  // AI-generated END - 初始化日期数据

  // AI-generated START - 设置当前月份
  /// 设置当前显示的月份
  void setCurrentMonth(DateTime month) {
    _currentMonth = DateTime(month.year, month.month, 1);
    notifyListeners();
  }
  // AI-generated END - 设置当前月份

  // AI-generated START - 选择日期
  /// 选择日期
  void selectDate(DateTime date) {
    _selectedDate = DateTime(date.year, date.month, date.day);
    notifyListeners();
  }
  // AI-generated END - 选择日期

  // AI-generated START - 回到今天
  /// 回到今天并选中今天
  void goToToday() {
    final today = DateTime.now();
    _currentMonth = DateTime(today.year, today.month, 1);
    _selectedDate = DateTime(today.year, today.month, today.day);
    notifyListeners();
  }
  // AI-generated END - 回到今天

  // AI-generated START - 上一个月
  /// 切换到上一个月
  void previousMonth() {
    _currentMonth = DateTime(
      _currentMonth.year,
      _currentMonth.month - 1,
      1,
    );
    notifyListeners();
  }
  // AI-generated END - 上一个月

  // AI-generated START - 下一个月
  /// 切换到下一个月
  void nextMonth() {
    _currentMonth = DateTime(
      _currentMonth.year,
      _currentMonth.month + 1,
      1,
    );
    notifyListeners();
  }
  // AI-generated END - 下一个月

  // AI-generated START - 判断日期是否有事件
  /// 判断指定日期是否有事件
  bool hasEvent(DateTime date) {
    final normalizedDate = DateTime(date.year, date.month, date.day);
    return _eventDates.any((eventDate) =>
        eventDate.year == normalizedDate.year &&
        eventDate.month == normalizedDate.month &&
        eventDate.day == normalizedDate.day);
  }
  // AI-generated END - 判断日期是否有事件

  // AI-generated START - 添加事件日期
  /// 添加事件日期
  void addEventDate(DateTime date) {
    _eventDates.add(DateTime(date.year, date.month, date.day));
    notifyListeners();
  }
  // AI-generated END - 添加事件日期

  // AI-generated START - 移除事件日期
  /// 移除事件日期
  void removeEventDate(DateTime date) {
    _eventDates.removeWhere((eventDate) =>
        eventDate.year == date.year &&
        eventDate.month == date.month &&
        eventDate.day == date.day);
    notifyListeners();
  }
  // AI-generated END - 移除事件日期
}
// AI-generated END - calendar_provider.dart

