// AI-generated START - 创建AI专家卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';

/// 创建AI专家卡片组件
/// 显示创建AI专家的按钮，带有渐变背景和加号图标
class MPCreateExpertCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const MPCreateExpertCard({
    super.key,
    this.onTap,
    this.title = '创建AI专家',
  });
  // AI-generated END - 构造函数

  /// 点击回调
  final VoidCallback? onTap;

  /// 按钮标题文本
  final String title;

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
      height: 56.0,
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          begin: Alignment.centerLeft,
          end: Alignment.centerRight,
          colors: [
            Color(0xFF2563EB), // 蓝色
            Color(0xFF9333EA), // 紫色
          ],
        ),
        borderRadius: BorderRadius.circular(28.0),
      ),
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          onTap: onTap,
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 16.0),
            alignment: Alignment.center,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                // 加号图标
                Assets.images.mpAddAiExport.image(
                  width: 20.0,
                  height: 20.0,
                  fit: BoxFit.contain,
                ),
                const SizedBox(width: 4.0),
                // 文本
                Text(
                  title,
                  style: const TextStyle(
                    fontSize: 14.0,
                    fontWeight: FontWeight.w500,
                    color: Colors.white,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
  // AI-generated END - 构建方法
}
// AI-generated END - mp_create_expert_card.dart
