// AI-generated START - 声纹识别状态管理Provider - Generated by AI
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:omi/backend/http/mp_api/mp_speaker.dart';
import 'package:omi/backend/schema/mp/mp_data_model.dart';
import 'package:omi/backend/schema/mp/mp_speaker.dart';
import 'package:omi/gen/assets.gen.dart';
import 'package:omi/pages/mp_custom_utils/mp_timestamp_utils.dart';
import 'package:omi/pages/mp_newsetting/voice_recognition/widgets/my_voice_card.dart';

/// 声纹识别状态管理Provider
/// 管理声音列表数据
class VoiceRecognitionProvider with ChangeNotifier {
  // AI-generated START - 声音列表
  List<MyVoiceItem> _voiceList = [];
  // AI-generated END - 声音列表

  // AI-generated START - 已保存的声音列表
  List<MyVoiceItem> _savedVoicesList = [];
  // AI-generated END - 已保存的声音列表

  // AI-generated START - 获取声音列表
  List<MyVoiceItem> get voiceList => _voiceList;
  // AI-generated END - 获取声音列表

  // AI-generated START - 获取已保存的声音列表
  List<MyVoiceItem> get savedVoicesList => _savedVoicesList;
  // AI-generated END - 获取已保存的声音列表

  // AI-generated START - 是否正在加载
  bool _isLoading = false;
  // AI-generated END - _isLoading

  // AI-generated START - 错误信息
  String? _error;
  // AI-generated END - _error

  // AI-generated START - 获取是否正在加载
  bool get isLoading => _isLoading;
  // AI-generated END - isLoading

  // AI-generated START - 获取错误信息
  String? get error => _error;
  // AI-generated END - error

  // AI-generated START - 构造函数
  VoiceRecognitionProvider() {
    loadSpeakerList();
  }
  // AI-generated END - 构造函数

  // AI-generated START - 从接口加载声音列表
  Future<void> loadSpeakerList() async {
    if (_isLoading) return;

    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      final request = MPGetSpeakerListRequest(
        pageSize: 100, // 获取足够多的数据
        cursor: '', // 从第一页开始
      );
      final response = await getSpeakerList(request);
      if (response != null && response.speakers.isNotEmpty) {
        // 清空现有列表
        _voiceList = [];
        _savedVoicesList = [];

        // 根据 myself_voice 字段分类
        for (final speaker in response.speakers) {
          print('audioUrlloadSpeakerList response11: ${speaker.duration}');
          print('audioUrlloadSpeakerList response: ${speaker.audioUrl}');

          final voiceItem = _convertSpeakerToVoiceItem(speaker);

          if (speaker.myselfVoice == true) {
            // myself_voice = true 的是"我的声音"
            _voiceList.add(voiceItem);
          } else if (speaker.myselfVoice == false) {
            // myself_voice = false 的是"保存的声音"
            _savedVoicesList.add(voiceItem);
          }
          // 如果 myself_voice 为 null，则不添加到任何列表
        }
      }
    } catch (e) {
      debugPrint('Failed to load speaker list: $e');
      _error = 'Failed to load speaker list: $e';
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }
  // AI-generated END - loadSpeakerList

  // AI-generated START - 将 MPSpeakerStruct 转换为 MyVoiceItem
  MyVoiceItem _convertSpeakerToVoiceItem(MPSpeakerStruct speaker) {
    // 默认值，因为 API 可能没有提供这些字段

    // 使用 createdAt 转换为日期字符串
    String date = '今天';
    if (speaker.createdAt != null) {
      date = MPTimestampUtils.timestampToRelativeDateString(speaker.createdAt!);
    }

    return MyVoiceItem(
      id: speaker.id,
      title: speaker.name.isNotEmpty ? speaker.name : '未命名',
      duration: speaker.duration != null ? '${speaker.duration}秒' : '0秒',
      date: date,
      icon: speaker.myselfVoice == true ? Assets.images.mpMyVoice.path : null,
      imageUrl: speaker.avatar.isNotEmpty ? speaker.avatar : null,
      audioUrl: speaker.audioUrl,
    );
  }
  // AI-generated END - _convertSpeakerToVoiceItem

  // AI-generated START - 添加声音
  void addVoice(MyVoiceItem item) {
    _voiceList.add(item);
    notifyListeners();
  }
  // AI-generated END - 添加声音

  // AI-generated START - 删除声音
  void removeVoice(int index) {
    if (index >= 0 && index < _voiceList.length) {
      _voiceList.removeAt(index);
      notifyListeners();
    }
  }
  // AI-generated END - 删除声音

  // AI-generated START - 更新声音
  void updateVoice(int index, MyVoiceItem item) {
    if (index >= 0 && index < _voiceList.length) {
      _voiceList[index] = item;
      notifyListeners();
    }
  }
  // AI-generated END - 更新声音

  // AI-generated START - 刷新数据
  void refresh() {
    loadSpeakerList();
  }
  // AI-generated END - 刷新数据
}
// AI-generated END - voice_recognition_provider.dart
