// AI-generated START - 声纹识别状态管理Provider - Generated by AI
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';
import 'package:omi/pages/mp_newsetting/voice_recognition/widgets/my_voice_card.dart';

/// 声纹识别状态管理Provider
/// 管理声音列表数据
class VoiceRecognitionProvider with ChangeNotifier {
  // AI-generated START - 声音列表
  List<MyVoiceItem> _voiceList = [];
  // AI-generated END - 声音列表

  // AI-generated START - 已保存的声音列表
  List<MyVoiceItem> _savedVoicesList = [];
  // AI-generated END - 已保存的声音列表

  // AI-generated START - 获取声音列表
  List<MyVoiceItem> get voiceList => _voiceList;
  // AI-generated END - 获取声音列表

  // AI-generated START - 获取已保存的声音列表
  List<MyVoiceItem> get savedVoicesList => _savedVoicesList;
  // AI-generated END - 获取已保存的声音列表

  // AI-generated START - 构造函数
  VoiceRecognitionProvider() {
    _loadMockData();
    _loadSavedVoicesData();
  }
  // AI-generated END - 构造函数

  // AI-generated START - 加载模拟数据
  void _loadMockData() {
    _voiceList = [
      MyVoiceItem(
        id: '0',
        title: '我的声音',
        duration: '120秒',
        date: '2024-01-20',
        icon: Assets.images.mpMyVoice.path, // 优先显示本地图片
      ),
    ];
    notifyListeners();
  }
  // AI-generated END - 加载模拟数据

  // AI-generated START - 添加声音
  void addVoice(MyVoiceItem item) {
    _voiceList.add(item);
    notifyListeners();
  }
  // AI-generated END - 添加声音

  // AI-generated START - 删除声音
  void removeVoice(int index) {
    if (index >= 0 && index < _voiceList.length) {
      _voiceList.removeAt(index);
      notifyListeners();
    }
  }
  // AI-generated END - 删除声音

  // AI-generated START - 更新声音
  void updateVoice(int index, MyVoiceItem item) {
    if (index >= 0 && index < _voiceList.length) {
      _voiceList[index] = item;
      notifyListeners();
    }
  }
  // AI-generated END - 更新声音

  // AI-generated START - 加载已保存的声音模拟数据
  void _loadSavedVoicesData() {
    _savedVoicesList = [
      const MyVoiceItem(
        id: '3',
        title: '叶成功',
        duration: '95秒',
        date: '2024-01-15',
        imageUrl: 'assets/images/ye_chenggong.png',
      ),
      const MyVoiceItem(
        id: '4',
        title: '叶天命',
        duration: '110秒',
        date: '2024-01-14',
        imageUrl: 'assets/images/ye_tianming.png',
      ),
      const MyVoiceItem(
        id: '5',
        title: '叶无敌',
        duration: '105秒',
        date: '2024-01-12',
        imageUrl: 'assets/images/ye_wudi.png',
      ),
      const MyVoiceItem(
        id: '6',
        title: '叶疯狂',
        duration: '98秒',
        date: '2024-01-10',
        imageUrl: 'assets/images/ye_fengkuang.png',
      ),
    ];
    notifyListeners();
  }
  // AI-generated END - 加载已保存的声音模拟数据

  // AI-generated START - 刷新数据
  void refresh() {
    _loadMockData();
    _loadSavedVoicesData();
  }
  // AI-generated END - 刷新数据
}
// AI-generated END - voice_recognition_provider.dart
