// AI-generated START - 个人中心状态管理Provider - Generated by AI
import 'package:flutter/foundation.dart';

/// 用户资料数据模型
class UserProfile {
  // AI-generated START - 构造函数
  const UserProfile({
    required this.name,
    required this.email,
    this.avatarUrl,
    this.avatarSize = 80.0,
  });
  // AI-generated END - 构造函数

  /// 用户姓名
  final String name;

  /// 用户邮箱
  final String email;

  /// 头像URL
  final String? avatarUrl;

  /// 头像大小
  final double avatarSize;
}

/// 个人中心状态管理Provider
/// 管理用户个人信息数据
class PersonalProvider with ChangeNotifier {
  // AI-generated START - 用户姓名
  String _name = '叶志伟';
  // AI-generated END - 用户姓名

  // AI-generated START - 用户邮箱
  String _email = 'ye.zhiwei@example.com';
  // AI-generated END - 用户邮箱

  // AI-generated START - 头像URL
  String? _avatarUrl;
  // AI-generated END - 头像URL

  // AI-generated START - 头像大小
  double _avatarSize = 80.0;
  // AI-generated END - 头像大小

  // AI-generated START - 获取用户姓名
  String get name => _name;
  // AI-generated END - 获取用户姓名

  // AI-generated START - 获取用户邮箱
  String get email => _email;
  // AI-generated END - 获取用户邮箱

  // AI-generated START - 获取头像URL
  String? get avatarUrl => _avatarUrl;
  // AI-generated END - 获取头像URL

  // AI-generated START - 获取头像大小
  double get avatarSize => _avatarSize;
  // AI-generated END - 获取头像大小

  // AI-generated START - 更新用户姓名
  void updateName(String name) {
    _name = name;
    notifyListeners();
  }
  // AI-generated END - 更新用户姓名

  // AI-generated START - 更新用户邮箱
  void updateEmail(String email) {
    _email = email;
    notifyListeners();
  }
  // AI-generated END - 更新用户邮箱

  // AI-generated START - 更新头像URL
  void updateAvatarUrl(String? avatarUrl) {
    _avatarUrl = avatarUrl;
    notifyListeners();
  }
  // AI-generated END - 更新头像URL

  // AI-generated START - 更新头像大小
  void updateAvatarSize(double avatarSize) {
    _avatarSize = avatarSize;
    notifyListeners();
  }
  // AI-generated END - 更新头像大小

  // AI-generated START - 更新用户资料（部分更新）
  void updateProfile({
    String? name,
    String? email,
    String? avatarUrl,
    double? avatarSize,
  }) {
    if (name != null) _name = name;
    if (email != null) _email = email;
    if (avatarUrl != null) _avatarUrl = avatarUrl;
    if (avatarSize != null) _avatarSize = avatarSize;
    notifyListeners();
  }
  // AI-generated END - 更新用户资料（部分更新）

  // AI-generated START - 一次性设置所有用户资料（从API或数据源同时返回）
  void setProfile(UserProfile profile) {
    _name = profile.name;
    _email = profile.email;
    _avatarUrl = profile.avatarUrl;
    _avatarSize = profile.avatarSize;
    notifyListeners();
  }
  // AI-generated END - 一次性设置所有用户资料

  // AI-generated START - 一次性设置所有用户资料（使用命名参数）
  void setProfileData({
    required String name,
    required String email,
    String? avatarUrl,
    double? avatarSize,
  }) {
    _name = name;
    _email = email;
    _avatarUrl = avatarUrl;
    _avatarSize = avatarSize ?? 80.0;
    notifyListeners();
  }
  // AI-generated END - 一次性设置所有用户资料（使用命名参数）

  // AI-generated START - 获取完整的用户资料
  UserProfile get profile => UserProfile(
        name: _name,
        email: _email,
        avatarUrl: _avatarUrl,
        avatarSize: _avatarSize,
      );
  // AI-generated END - 获取完整的用户资料
}
// AI-generated END - personal_provider.dart

