// AI-generated START - 专家类别卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/providers/mp_add_export_provider.dart';
import 'package:provider/provider.dart';

/// 专家类别数据模型
class MPExpertCategory {
  // AI-generated START - 构造函数
  const MPExpertCategory({
    required this.id,
    required this.name,
  });
  // AI-generated END - 构造函数

  /// 类别ID
  final String id;

  /// 类别名称
  final String name;
}

/// 专家类别卡片组件
/// 显示专家类别下拉选择框
class MPExpertCategoryCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const MPExpertCategoryCard({
    super.key,
    this.onCategoryChanged,
  });
  // AI-generated END - 构造函数

  /// 类别改变回调
  final ValueChanged<String>? onCategoryChanged;

  // AI-generated START - 获取默认类别列表
  static List<MPExpertCategory> getDefaultCategories() {
    return const [
      MPExpertCategory(
        id: 'business',
        name: '商业',
      ),
      MPExpertCategory(
        id: 'technology',
        name: '技术',
      ),
      MPExpertCategory(
        id: 'creative',
        name: '创意',
      ),
      MPExpertCategory(
        id: 'life',
        name: '生活',
      ),
    ];
  }
  // AI-generated END - getDefaultCategories

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Consumer<MPAddExportProvider>(
      builder: (context, provider, child) {
        final categories = getDefaultCategories();
        final selectedCategory = provider.type.isNotEmpty
            ? categories.firstWhere(
                (cat) => cat.name == provider.type,
                orElse: () => categories.first,
              )
            : categories.first;

        return Container(
          margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
          padding: const EdgeInsets.all(16.0),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12.0),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // AI-generated START - 标题
              const Text(
                '专家类别',
                style: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.w500,
                  color: Color(0xFF374151),
                ),
              ),
              const SizedBox(height: 12.0),
              // AI-generated END - 标题

              // AI-generated START - 下拉选择框
              GestureDetector(
                onTap: () => _showCategoryPicker(context, provider, categories),
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 14.0),
                  decoration: BoxDecoration(
                    color: const Color(0xFFF9FAFB),
                    borderRadius: BorderRadius.circular(8.0),
                  ),
                  child: Row(
                    children: [
                      // AI-generated START - 选中的类别名称
                      Expanded(
                        child: Text(
                          selectedCategory.name,
                          style: const TextStyle(
                            fontSize: 14.0,
                            color: Color(0xFF111827),
                            fontWeight: FontWeight.normal,
                          ),
                        ),
                      ),
                      // AI-generated END - 选中的类别名称

                      // AI-generated START - 下拉箭头图标
                      const Icon(
                        Icons.keyboard_arrow_down,
                        color: Color(0xFF9CA3AF),
                        size: 20.0,
                      ),
                      // AI-generated END - 下拉箭头图标
                    ],
                  ),
                ),
              ),
              // AI-generated END - 下拉选择框
            ],
          ),
        );
      },
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 显示类别选择器
  void _showCategoryPicker(
    BuildContext context,
    MPAddExportProvider provider,
    List<MPExpertCategory> categories,
  ) {
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      builder: (BuildContext context) {
        return Container(
          decoration: const BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.vertical(
              top: Radius.circular(20.0),
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              // AI-generated START - 标题栏
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 16.0),
                decoration: BoxDecoration(
                  border: Border(
                    bottom: BorderSide(
                      color: Colors.grey.shade200,
                      width: 1.0,
                    ),
                  ),
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text(
                      '选择类别',
                      style: TextStyle(
                        fontSize: 18.0,
                        fontWeight: FontWeight.w600,
                        color: Color(0xFF212121),
                      ),
                    ),
                    IconButton(
                      icon: const Icon(Icons.close),
                      onPressed: () => Navigator.of(context).pop(),
                      color: Colors.grey.shade600,
                    ),
                  ],
                ),
              ),
              // AI-generated END - 标题栏

              // AI-generated START - 类别列表
              Flexible(
                child: ListView.builder(
                  shrinkWrap: true,
                  itemCount: categories.length,
                  itemBuilder: (context, index) {
                    final category = categories[index];
                    final isSelected = provider.type == category.name;

                    return ListTile(
                      title: Text(
                        category.name,
                        style: TextStyle(
                          fontSize: 16.0,
                          fontWeight: isSelected ? FontWeight.w600 : FontWeight.normal,
                          color: isSelected ? const Color(0xFF2563EB) : const Color(0xFF212121),
                        ),
                      ),
                      trailing: isSelected
                          ? const Icon(
                              Icons.check,
                              color: Color(0xFF2563EB),
                            )
                          : null,
                      onTap: () {
                        provider.updateCategory(category.name);
                        onCategoryChanged?.call(category.name);
                        Navigator.of(context).pop();
                      },
                    );
                  },
                ),
              ),
              // AI-generated END - 类别列表
            ],
          ),
        );
      },
    );
  }
  // AI-generated END - _showCategoryPicker
}
// AI-generated END - mp_expert_category_card.dart
