// AI-generated START - 专家介绍卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/providers/mp_add_export_provider.dart';
import 'package:provider/provider.dart';

/// 专家介绍卡片组件
/// 显示专家介绍输入框，带字符计数
class MPExpertIntroductionCard extends StatefulWidget {
  // AI-generated START - 构造函数
  const MPExpertIntroductionCard({
    super.key,
    this.aboutController,
    this.onAboutChanged,
    this.maxLength = 500,
  });
  // AI-generated END - 构造函数

  /// 介绍输入框控制器
  final TextEditingController? aboutController;

  /// 介绍改变回调
  final ValueChanged<String>? onAboutChanged;

  /// 最大字符数
  final int maxLength;

  @override
  State<MPExpertIntroductionCard> createState() => _MPExpertIntroductionCardState();
}

class _MPExpertIntroductionCardState extends State<MPExpertIntroductionCard> {
  late TextEditingController _controller;
  int _currentLength = 0;

  @override
  void initState() {
    super.initState();
    _controller = widget.aboutController ?? TextEditingController();
    // 如果提供了 controller，从 provider 初始化值
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) {
        final provider = Provider.of<MPAddExportProvider>(context, listen: false);
        if (_controller.text.isEmpty && provider.about.isNotEmpty) {
          _controller.text = provider.about;
          _currentLength = provider.about.length;
        }
      }
    });
    _currentLength = _controller.text.length;
    _controller.addListener(_updateLength);
  }

  @override
  void dispose() {
    if (widget.aboutController == null) {
      _controller.dispose();
    } else {
      _controller.removeListener(_updateLength);
    }
    super.dispose();
  }

  void _updateLength() {
    setState(() {
      _currentLength = _controller.text.length;
    });
  }

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Consumer<MPAddExportProvider>(
      builder: (context, provider, child) {
        return Container(
          margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
          padding: const EdgeInsets.all(16.0),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12.0),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withAlpha(5),
                blurRadius: 8.0,
                offset: const Offset(0, 2),
              ),
            ],
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // AI-generated START - 标题
              const Text(
                '专家介绍',
                style: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.w500,
                  color: Color(0xFF374151),
                ),
              ),
              const SizedBox(height: 12.0),
              // AI-generated END - 标题

              // AI-generated START - 输入框
              TextField(
                controller: _controller,
                maxLines: 4,
                maxLength: widget.maxLength,
                onChanged: (value) {
                  provider.updateAbout(value);
                  widget.onAboutChanged?.call(value);
                },
                style: const TextStyle(
                  fontSize: 14.0,
                  color: Color(0xFF212121),
                  height: 1.5,
                ),
                decoration: InputDecoration(
                  hintText: '请描述这位AI专家的专业领域和特长...',
                  hintStyle: TextStyle(
                    color: Colors.grey.shade400,
                    fontSize: 14.0,
                    height: 1.5,
                  ),
                  filled: true,
                  fillColor: Colors.white,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8.0),
                    borderSide: BorderSide(
                      color: Colors.grey.shade300,
                      width: 1.0,
                    ),
                  ),
                  enabledBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8.0),
                    borderSide: BorderSide(
                      color: Colors.grey.shade300,
                      width: 1.0,
                    ),
                  ),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8.0),
                    borderSide: const BorderSide(
                      color: Color(0xFF2563EB),
                      width: 2.0,
                    ),
                  ),
                  errorBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8.0),
                    borderSide: BorderSide(
                      color: Colors.red.shade300,
                      width: 1.0,
                    ),
                  ),
                  focusedErrorBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8.0),
                    borderSide: BorderSide(
                      color: Colors.red.shade400,
                      width: 2.0,
                    ),
                  ),
                  contentPadding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
                  counterText: '', // 隐藏默认计数器
                ),
              ),
              // AI-generated END - 输入框

              // AI-generated START - 字符计数器
              Align(
                alignment: Alignment.centerRight,
                child: Padding(
                  padding: const EdgeInsets.only(top: 4.0),
                  child: Text(
                    '$_currentLength/${widget.maxLength}',
                    style: TextStyle(
                      fontSize: 12.0,
                      color: _currentLength > widget.maxLength ? Colors.red.shade600 : Colors.grey.shade500,
                      fontWeight: FontWeight.normal,
                    ),
                  ),
                ),
              ),
              // AI-generated END - 字符计数器
            ],
          ),
        );
      },
    );
  }
  // AI-generated END - 构建方法
}
// AI-generated END - mp_expert_introduction_card.dart
