// AI-generated START - 专家 Prompt 卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/providers/mp_add_export_provider.dart';
import 'package:provider/provider.dart';

/// 专家 Prompt 卡片组件
/// 显示专家沟通技能描述或反馈技能描述的输入框，带字符计数
class MPExpertPromptCard extends StatefulWidget {
  // AI-generated START - 构造函数
  const MPExpertPromptCard({
    super.key,
    required this.skillType,
    this.promptController,
    this.onPromptChanged,
    this.maxLength = 500,
  });
  // AI-generated END - 构造函数

  /// 技能类型
  final MPExpertSkillType skillType;

  /// Prompt 输入框控制器
  final TextEditingController? promptController;

  /// Prompt 改变回调
  final ValueChanged<String>? onPromptChanged;

  /// 最大字符数
  final int maxLength;

  @override
  State<MPExpertPromptCard> createState() => _MPExpertPromptCardState();
}

class _MPExpertPromptCardState extends State<MPExpertPromptCard> {
  late TextEditingController _controller;
  int _currentLength = 0;

  @override
  void initState() {
    super.initState();
    _controller = widget.promptController ?? TextEditingController();
    // 如果提供了 controller，从 provider 初始化值
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) {
        final provider = Provider.of<MPAddExportProvider>(context, listen: false);
        String promptValue = '';
        if (widget.skillType == MPExpertSkillType.chat) {
          promptValue = provider.chatPrompt;
        } else if (widget.skillType == MPExpertSkillType.feedback) {
          promptValue = provider.feedbackPrompt;
        }
        if (_controller.text.isEmpty && promptValue.isNotEmpty) {
          _controller.text = promptValue;
          _currentLength = promptValue.length;
        }
      }
    });
    _currentLength = _controller.text.length;
    _controller.addListener(_updateLength);
  }

  @override
  void dispose() {
    if (widget.promptController == null) {
      _controller.dispose();
    } else {
      _controller.removeListener(_updateLength);
    }
    super.dispose();
  }

  void _updateLength() {
    setState(() {
      _currentLength = _controller.text.length;
    });
  }

  // AI-generated START - 获取标题
  String _getTitle() {
    switch (widget.skillType) {
      case MPExpertSkillType.chat:
        return '专家沟通技能描述 (Prompt)';
      case MPExpertSkillType.feedback:
        return '专家反馈技能描述 (Prompt)';
    }
  }
  // AI-generated END - _getTitle

  // AI-generated START - 获取占位符文本
  String _getHintText() {
    switch (widget.skillType) {
      case MPExpertSkillType.chat:
        return '请详细描述AI专家的沟通方式、回答风格、专业知识范围等...';
      case MPExpertSkillType.feedback:
        return '请详细描述AI专家的反馈方式、分析角度、建议风格等...';
    }
  }
  // AI-generated END - _getHintText

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Consumer<MPAddExportProvider>(
      builder: (context, provider, child) {
        return Container(
          margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
          padding: const EdgeInsets.all(16.0),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12.0),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.05),
                blurRadius: 8.0,
                offset: const Offset(0, 2),
              ),
            ],
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // AI-generated START - 标题
              Text(
                _getTitle(),
                style: const TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.w500,
                  color: Color(0xFF374151),
                ),
              ),
              const SizedBox(height: 12.0),
              // AI-generated END - 标题

              // AI-generated START - 输入框
              TextField(
                controller: _controller,
                maxLines: 5,
                maxLength: widget.maxLength,
                onChanged: (value) {
                  if (widget.skillType == MPExpertSkillType.chat) {
                    provider.updateChatPrompt(value);
                  } else if (widget.skillType == MPExpertSkillType.feedback) {
                    provider.updateFeedbackPrompt(value);
                  }
                  widget.onPromptChanged?.call(value);
                },
                style: const TextStyle(
                  fontSize: 14.0,
                  color: Color(0xFF212121),
                  height: 1.5,
                ),
                decoration: InputDecoration(
                  hintText: _getHintText(),
                  hintStyle: TextStyle(
                    color: Colors.grey.shade400,
                    fontSize: 14.0,
                    height: 1.5,
                  ),
                  filled: true,
                  fillColor: Colors.white,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8.0),
                    borderSide: BorderSide(
                      color: Colors.grey.shade300,
                      width: 1.0,
                    ),
                  ),
                  enabledBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8.0),
                    borderSide: BorderSide(
                      color: Colors.grey.shade300,
                      width: 1.0,
                    ),
                  ),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8.0),
                    borderSide: const BorderSide(
                      color: Color(0xFF2563EB),
                      width: 2.0,
                    ),
                  ),
                  errorBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8.0),
                    borderSide: BorderSide(
                      color: Colors.red.shade300,
                      width: 1.0,
                    ),
                  ),
                  focusedErrorBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8.0),
                    borderSide: BorderSide(
                      color: Colors.red.shade400,
                      width: 2.0,
                    ),
                  ),
                  contentPadding: const EdgeInsets.all(16.0),
                  counterText: '', // 隐藏默认计数器
                ),
              ),
              // AI-generated END - 输入框

              // AI-generated START - 字符计数器
              Align(
                alignment: Alignment.centerRight,
                child: Padding(
                  padding: const EdgeInsets.only(top: 4.0),
                  child: Text(
                    '$_currentLength/${widget.maxLength}',
                    style: TextStyle(
                      fontSize: 12.0,
                      color: _currentLength > widget.maxLength ? Colors.red.shade600 : Colors.grey.shade500,
                      fontWeight: FontWeight.normal,
                    ),
                  ),
                ),
              ),
              // AI-generated END - 字符计数器
            ],
          ),
        );
      },
    );
  }
  // AI-generated END - 构建方法
}
// AI-generated END - mp_expert_prompt_card.dart
