// AI-generated START - 专家技能卡片组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';
import 'package:omi/pages/mp_expert_feedback/mp_add_export/providers/mp_add_export_provider.dart';
import 'package:provider/provider.dart';

/// 专家技能选项数据模型
class MPExpertSkillOption {
  // AI-generated START - 构造函数
  const MPExpertSkillOption({
    required this.type,
    required this.title,
    required this.description,
    required this.icon,
    required this.selectedIcon,
    required this.color,
  });
  // AI-generated END - 构造函数

  /// 技能类型
  final MPExpertSkillType type;

  /// 标题
  final String title;

  /// 描述
  final String description;

  /// 图标
  final String? icon;

  /// 选中图标
  final String? selectedIcon;

  /// 颜色
  final Color color;
}

/// 专家技能卡片组件
/// 显示专家技能选择选项
class MPExpertSkillsCard extends StatelessWidget {
  // AI-generated START - 构造函数
  const MPExpertSkillsCard({
    super.key,
    this.onSkillChanged,
  });
  // AI-generated END - 构造函数

  /// 技能改变回调
  final ValueChanged<MPExpertSkillType>? onSkillChanged;

  // AI-generated START - 获取默认技能选项列表
  static List<MPExpertSkillOption> getDefaultSkills() {
    return [
      MPExpertSkillOption(
        type: MPExpertSkillType.chat,
        title: 'Chat',
        description: '对话交流',
        icon: Assets.images.mpAddExportChatUnselect.path,
        selectedIcon: Assets.images.mpAddExportChat.path,
        color: const Color(0xFF2563EB), // 蓝色
      ),
      MPExpertSkillOption(
        type: MPExpertSkillType.feedback,
        title: 'Feedback',
        description: '专业反馈',
        icon: Assets.images.mpAddExportFeedbackUnselect.path,
        selectedIcon: Assets.images.mpAddExportFeedback.path,
        color: const Color(0xFF10B981), // 绿色
      ),
    ];
  }
  // AI-generated END - getDefaultSkills

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Consumer<MPAddExportProvider>(
      builder: (context, provider, child) {
        final skills = getDefaultSkills();

        return Container(
          margin: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
          padding: const EdgeInsets.all(16.0),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12.0),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.05),
                blurRadius: 8.0,
                offset: const Offset(0, 2),
              ),
            ],
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // AI-generated START - 标题
              const Text(
                '专家技能',
                style: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.w500,
                  color: Color(0xFF374151),
                ),
              ),
              const SizedBox(height: 16.0),
              // AI-generated END - 标题

              // AI-generated START - 技能选项列表
              ...skills.map((skill) {
                final isSelected = provider.isSkillSelected(skill.type);
                return Padding(
                  padding: const EdgeInsets.only(bottom: 8.0),
                  child: _buildSkillOption(
                    context,
                    skill,
                    isSelected,
                    () {
                      // 切换技能选中状态（支持反选）
                      provider.toggleSkill(skill.type);
                      onSkillChanged?.call(skill.type);
                    },
                  ),
                );
              }),
              // AI-generated END - 技能选项列表
            ],
          ),
        );
      },
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建技能选项
  Widget _buildSkillOption(
    BuildContext context,
    MPExpertSkillOption skill,
    bool isSelected,
    VoidCallback onTap,
  ) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.all(12.0),
        decoration: BoxDecoration(
          color: isSelected ? skill.color.withAlpha(10) : Colors.white,
          borderRadius: BorderRadius.circular(12.0),
          border: Border.all(
            color: isSelected ? skill.color : const Color(0xFFE5E7EB),
            width: 1.0,
          ),
        ),
        child: Row(
          children: [
            // AI-generated START - 图标
            Image.asset(isSelected ? skill.selectedIcon! : skill.icon!, width: 40.0, height: 40.0, fit: BoxFit.contain),
            const SizedBox(width: 8.0),
            // AI-generated END - 图标

            // AI-generated START - 文本内容
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    skill.title,
                    style: TextStyle(
                      fontSize: 14.0,
                      fontWeight: FontWeight.w600,
                      color: isSelected ? skill.color : const Color(0xFF374151),
                    ),
                  ),
                  const SizedBox(height: 4.0),
                  Text(
                    skill.description,
                    style: const TextStyle(
                      fontSize: 12.0,
                      color: Color(0xFF6B7280),
                    ),
                  ),
                ],
              ),
            ),
            // AI-generated END - 文本内容

            // AI-generated START - 选中指示器
            isSelected
                ? Container(
                    width: 20.0,
                    height: 20.0,
                    decoration: BoxDecoration(
                      color: skill.color,
                      shape: BoxShape.circle,
                    ),
                    child: Center(
                      child: Assets.images.mpAddExportChoose.image(
                        width: 13.0,
                        height: 12.0,
                        fit: BoxFit.contain,
                      ),
                    ),
                  )
                : Assets.images.mpAddExportUnchoose.image(
                    width: 20.0,
                    height: 20.0,
                    fit: BoxFit.contain,
                  ),
            // AI-generated END - 选中指示器
          ],
        ),
      ),
    );
  }
  // AI-generated END - _buildSkillOption
}
// AI-generated END - mp_expert_skills_card.dart
