// AI-generated START - 反馈时间选择弹窗组件 - Generated by AI
import 'package:flutter/material.dart';
import 'package:omi/gen/assets.gen.dart';

/// 反馈时间选择弹窗组件
/// 显示滚轮时间选择器弹窗
class MPFeedbackTimePickerDialog extends StatefulWidget {
  // AI-generated START - 构造函数
  const MPFeedbackTimePickerDialog({
    super.key,
    this.initialTime,
  });
  // AI-generated END - 构造函数

  /// 初始时间
  final TimeOfDay? initialTime;

  /// 显示弹窗的静态方法
  static Future<TimeOfDay?> show(
    BuildContext context, {
    TimeOfDay? initialTime,
  }) {
    return showModalBottomSheet<TimeOfDay>(
      context: context,
      backgroundColor: Colors.transparent,
      isScrollControlled: true,
      builder: (context) => MPFeedbackTimePickerDialog(
        initialTime: initialTime,
      ),
    );
  }

  @override
  State<MPFeedbackTimePickerDialog> createState() => _MPFeedbackTimePickerDialogState();
}

class _MPFeedbackTimePickerDialogState extends State<MPFeedbackTimePickerDialog> {
  late FixedExtentScrollController _hourController;
  late FixedExtentScrollController _minuteController;
  int _selectedHour = 9;
  int _selectedMinute = 0;

  @override
  void initState() {
    super.initState();
    final initialTime = widget.initialTime ?? const TimeOfDay(hour: 9, minute: 0);
    _selectedHour = initialTime.hour;
    _selectedMinute = initialTime.minute;

    // 创建滚动控制器，设置初始位置
    _hourController = FixedExtentScrollController(initialItem: _selectedHour);
    _minuteController = FixedExtentScrollController(initialItem: _selectedMinute);
  }

  @override
  void dispose() {
    _hourController.dispose();
    _minuteController.dispose();
    super.dispose();
  }

  // AI-generated START - 转换为 TimeOfDay
  TimeOfDay _toTimeOfDay() {
    return TimeOfDay(hour: _selectedHour, minute: _selectedMinute);
  }
  // AI-generated END - _toTimeOfDay

  // AI-generated START - 构建方法
  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(20.0),
          topRight: Radius.circular(20.0),
        ),
      ),
      child: SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // AI-generated START - 标题栏
            Padding(
              padding: const EdgeInsets.fromLTRB(16.0, 16.0, 16.0, 0),
              child: Row(
                children: [
                  const Text(
                    '选择反馈时间',
                    style: TextStyle(
                      fontSize: 18.0,
                      fontWeight: FontWeight.w600,
                      color: Color(0xFF212121),
                    ),
                  ),
                  const Spacer(),
                  IconButton(
                    icon: Image.asset(
                      Assets.images.mpVoiceDialogClose.path,
                      width: 32.0,
                      height: 32.0,
                      fit: BoxFit.contain,
                    ),
                    onPressed: () => Navigator.of(context).pop(),
                    padding: EdgeInsets.zero,
                    constraints: const BoxConstraints(),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 20.0),
            // AI-generated END - 标题栏

            // AI-generated START - 滚轮时间选择器
            SizedBox(
              height: 200.0,
              child: Stack(
                children: [
                  // AI-generated START - 选中行背景高亮
                  Positioned(
                    left: 0,
                    right: 0,
                    top: 75.0, // 居中位置 (200 / 2 - 50 / 2 = 75)
                    height: 50.0,
                    child: Container(
                      margin: const EdgeInsets.symmetric(horizontal: 16.0),
                      decoration: BoxDecoration(
                        color: const Color(0xFFEFF6FF),
                        borderRadius: BorderRadius.circular(8.0),
                        border: Border.all(
                          color: const Color(0xFF2563EB).withOpacity(0.2),
                          width: 1.0,
                        ),
                      ),
                    ),
                  ),
                  // AI-generated END - 选中行背景高亮

                  // AI-generated START - 滚轮选择器
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      // AI-generated START - 小时选择器
                      Expanded(
                        child: _buildPickerColumn(
                          controller: _hourController,
                          itemCount: 24,
                          onSelectedItemChanged: (index) {
                            setState(() {
                              _selectedHour = index;
                            });
                          },
                          builder: (context, index) {
                            final hour = index;
                            final isSelected = hour == _selectedHour;
                            return Center(
                              child: Text(
                                hour.toString().padLeft(2, '0'),
                                style: TextStyle(
                                  fontSize: isSelected ? 20.0 : 16.0,
                                  fontWeight: isSelected ? FontWeight.w600 : FontWeight.normal,
                                  color: isSelected ? const Color(0xFF2563EB) : const Color(0xFF9CA3AF),
                                ),
                              ),
                            );
                          },
                        ),
                      ),
                      // AI-generated END - 小时选择器

                      // AI-generated START - 分隔符
                      const Padding(
                        padding: EdgeInsets.symmetric(horizontal: 8.0),
                        child: Text(
                          ':',
                          style: TextStyle(
                            fontSize: 20.0,
                            fontWeight: FontWeight.w600,
                            color: Color(0xFF2563EB),
                          ),
                        ),
                      ),
                      // AI-generated END - 分隔符

                      // AI-generated START - 分钟选择器
                      Expanded(
                        child: _buildPickerColumn(
                          controller: _minuteController,
                          itemCount: 60,
                          onSelectedItemChanged: (index) {
                            setState(() {
                              _selectedMinute = index;
                            });
                          },
                          builder: (context, index) {
                            final minute = index;
                            final isSelected = minute == _selectedMinute;
                            return Center(
                              child: Text(
                                minute.toString().padLeft(2, '0'),
                                style: TextStyle(
                                  fontSize: isSelected ? 20.0 : 16.0,
                                  fontWeight: isSelected ? FontWeight.w600 : FontWeight.normal,
                                  color: isSelected ? const Color(0xFF2563EB) : const Color(0xFF9CA3AF),
                                ),
                              ),
                            );
                          },
                        ),
                      ),
                      // AI-generated END - 分钟选择器
                    ],
                  ),
                  // AI-generated END - 滚轮选择器
                ],
              ),
            ),
            // AI-generated END - 滚轮时间选择器

            const SizedBox(height: 20.0),
            // AI-generated START - 确认按钮
            Padding(
              padding: const EdgeInsets.fromLTRB(16.0, 0, 16.0, 16.0),
              child: SizedBox(
                width: double.infinity,
                height: 45.0,
                child: ElevatedButton(
                  onPressed: () {
                    Navigator.of(context).pop(_toTimeOfDay());
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF2563EB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12.0),
                    ),
                    elevation: 0,
                  ),
                  child: const Text(
                    '确认',
                    style: TextStyle(
                      fontSize: 16.0,
                      fontWeight: FontWeight.w600,
                      color: Colors.white,
                    ),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 12.0),
            // AI-generated END - 确认按钮
          ],
        ),
      ),
    );
  }
  // AI-generated END - 构建方法

  // AI-generated START - 构建滚轮选择器列
  Widget _buildPickerColumn({
    required FixedExtentScrollController controller,
    required int itemCount,
    required ValueChanged<int> onSelectedItemChanged,
    required Widget Function(BuildContext, int) builder,
  }) {
    return ListWheelScrollView.useDelegate(
      controller: controller,
      itemExtent: 50.0,
      physics: const FixedExtentScrollPhysics(),
      onSelectedItemChanged: onSelectedItemChanged,
      childDelegate: ListWheelChildBuilderDelegate(
        builder: builder,
        childCount: itemCount,
      ),
    );
  }
  // AI-generated END - _buildPickerColumn
}
// AI-generated END - mp_feedback_time_picker_dialog.dart
