// AI-generated START - 日历日期数据模型 - Generated by AI
import 'package:flutter/material.dart';

/// 日历日期数据模型
/// 用于表示日历中的单个日期及其状态
class CalendarDate {
  // AI-generated START - 构造函数
  CalendarDate({
    required this.date,
    this.hasEvent = false,
    this.isSelected = false,
    this.isToday = false,
  });
  // AI-generated END - 构造函数

  /// 日期对象
  final DateTime date;

  /// 是否有事件（显示蓝色小点）
  final bool hasEvent;

  /// 是否被选中（显示蓝色背景）
  final bool isSelected;

  /// 是否是今天
  final bool isToday;

  /// 获取日期数字（1-31）
  int get day => date.day;

  /// 获取月份（1-12）
  int get month => date.month;

  /// 获取年份
  int get year => date.year;

  /// 判断是否是同一天
  bool isSameDay(DateTime other) {
    return date.year == other.year &&
        date.month == other.month &&
        date.day == other.day;
  }
}
// AI-generated END - calendar_date.dart

